### ISSUE TITLE
Make service registration as optional feature

### ISSUE THREAD

**Issue by aatarasoff** [spring-cloud/spring-cloud-consul#100]
After closing issue #93 `ConsulLifecycle` always register service itself. But I use external registration utility - `gliderlabs/registator` and dont want to register service with `ConsulLifecycle`. There is no possibility to turnoff lifecycle cause it depends on general flag `spring.cloud.consul.discovery.enabled`. I think that other flag is needed for this. For example `spring.cloud.consul.discovery.lifecycle.enabled` or other.

**Comment by aatarasoff** [comment]
PR in progress

**Comment by spencergibb** [comment]
Closed via 371e7ce87ae7c535050c93c1a9a2973679f99e0e
