### ISSUE TITLE
Spring cloud bus support for consul

### ISSUE THREAD

**Issue by rohan2381** [spring-cloud/spring-cloud-consul#107]
Hi,

Can you please confirm of the spring cloud bus support when using spring cloud consul config? I see there is support for the config server but was not sure on the consul. Also if you could share some example, that would be great

**Comment by spencergibb** [comment]
I'm a bit confused about your question. Spring Cloud Consul has [bus support](https://github.com/spring-cloud/spring-cloud-consul/tree/master/spring-cloud-consul-bus) but it is broken at the moment (we changed how the bus was implemented). It should be fixed for the next milestone.

**Comment by rohan2381** [comment]
Thanks Spencer. I look fwd to the next M release :)
