### ISSUE TITLE
Support new 0.5 based http health checks

### ISSUE THREAD

**Issue by cdupuis** [spring-cloud/spring-cloud-consul#11]
Since 0.5 consul supports http based health checks as per https://consul.io/docs/agent/checks.html. Would be great if this could be supported especially with the ```/health``` actuator endpoint from Boot being available out of the box.

**Comment by spencergibb** [comment]
:+1: 0.5 also has other useful stuff.

**Comment by cdupuis** [comment]
I may actually get around of submitting a PR myself. I guess I have to sign the CLA first :-)

**Comment by mattreyuk** [comment]
I have a very basic version working in https://github.com/mattreyuk/spring-cloud-consul if you're interested

**Comment by spencergibb** [comment]
Fixed via 0d3f028a5fd8241ee5a0d78d8f4e3a5de930f6e7
