### ISSUE TITLE
spring-cloud-consul-config: GitHub storage

### ISSUE THREAD

**Issue by marcellodesales** [spring-cloud/spring-cloud-consul#110]
Does the `spring-cloud-consul-config` support storage of configuration in GitHub, just like Spring Cloud Config? 

We have Spring Cloud Config and we just want to change the transport mechanism to consul for our micro-services in Docker.

Thanks

**Comment by spencergibb** [comment]
No, it's an alternative to config server. It uses consul as the key store. It you want git, use config server.
