### ISSUE TITLE
ConsulDiscoveryClient uses the node name instead of the address for the service instance URI

### ISSUE THREAD

**Issue by GuiForget** [spring-cloud/spring-cloud-consul#114]
I'm still new to Consul so I may have confused myself but when I saw the property preferIpAddress I assumed it was a switch between hostname vs ipAddress but it seems that it (also?) toggles between node names and the actual host providing the service.

The behavior is therefore very different when you run in an environment where the Consul server is not running on the same host as your services. If you have preferIpAddress false you basically get the wrong URIs.

Here is my very basic code:
```
    @Autowired
    private DiscoveryClient discoveryClient;

    public void printInstances(String serviceName) throws Exception {

        List<ServiceInstance> list = discoveryClient.getInstances(serviceName);
        if (list == null) {
            System.out.format("===== Null list returned for %s%n", serviceName);
        } else {
            System.out.format("===== Found %d instances of %s%n", list.size(), serviceName);
            for (ServiceInstance serviceInstance : list) {
                System.out.println(
                        serviceInstance.getServiceId() + " -- " + serviceInstance.getUri());
            }
        }
    }
```

With preferIpAddress=false, the output (with hostnames simplified) is:
```
===== Found 2 instances of myservice
myservice -- http://consulhost:9010
myservice -- http://consulhost:9010
```

With preferIpAddress=true, the output is then:
```
===== Found 2 instances of myservice
myservice -- http://servicehost1:9010
myservice -- http://servicehost2:9010
```

Note that Consul server runs on port 8500, so there's nothing running on port 9010 on consulhost.

**Comment by spencergibb** [comment]
This may come from a6b2519475d27767782fd53974d3457c798b64c2 which fixed #76

**Comment by spencergibb** [comment]
I'm thinking `preferIpAddress` doesn't have any business in `getCatalogServiceHost`.

**Comment by GuiForget** [comment]
:+1:
