### ISSUE TITLE
Improve logic of IpAddressUtils.getFirstNonLoopbackAddress method to fix bug with Docker overlay network 

### ISSUE THREAD

**Issue by aatarasoff** [spring-cloud/spring-cloud-consul#115]
Docker 1.9 has new overlay network for creating multi-host user SDNs. Overlay network create two network interfaces: eth0 that is overlay interface and eth1 that is swarm bridge interface. Each of them is non loopback. Method IpAddressUtils.getFirstNonLoopbackAddress always return eth1 interface, but eth0 is needed to return. I think some logic for filtering interfaces is needed. For example, by interface name or by net mask. Its will be very useful if software is launched in docker containers.

PR will be soon.

**Comment by spencergibb** [comment]
I'm trying to move this out of consul so if you could make the change [here](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/util/InetUtils.java) instead that would be helpful.

**Comment by fiunchinho** [comment]
Until the PR is sent with the changes, is there any workaround for this? I can't use it with overlay network as it is :(

**Comment by dsyer** [comment]
Can't you just set the hostname/IP address manually?

**Comment by fiunchinho** [comment]
I don't know before-hand which IP Docker will assign to the app, so I believe I can't

**Comment by dsyer** [comment]
If you use docker-compose you can use the links as hostnames. Other than that I'm not sure what we can do other than fix the issue.

**Comment by fiunchinho** [comment]
The whole point is to avoid the soon deprecated "link" feature of Docker, and avoid using /etc/hosts as discovery. If services using spring-cloud-consul advertise themselves using eth0 instead of eth1, you could just ask consul about a specific service and discover it.

**Comment by adriancole** [comment]
Jose, can you lazy-google something for me wrt "soon deprecated link" Any
favorite links on what's next etc? I'd love to borrow your knowledge.

**Comment by fiunchinho** [comment]
From [the official Docker documentation](https://docs.docker.com/engine/userguide/networking/dockernetworks/#legacy-links)

    While links are still supported in this limited capacity, you should avoid them in preference of Docker networks. The link feature is expected to be deprecated and removed in a future release.

I hope this helps.

**Comment by dsyer** [comment]
A bit (the docs are about as clear as mud, but the link is helpful as a starting point). What would be really helpful is a simple example of a `docker-compose.yml` using links being updated to the latest recommended approach.

**Comment by adriancole** [comment]
agreed. seems in this case, it would be an overlay network backed by
console as a K/V store, ya?

Though rock and hard place, as links are deprecated and compose+overlay is
experimental :D

https://docs.docker.com/compose/networking/

regardless.. Jose, wanna spin this out as a separate issue and lead the
charge on this?

**Comment by spencergibb** [comment]
Closing in favor of #123 and https://github.com/spring-cloud/spring-cloud-commons/pull/67
