### ISSUE TITLE
llegal value to be added to the service's tags '/'

### ISSUE THREAD

**Issue by domelz** [spring-cloud/spring-cloud-consul#118]
org.springframework.cloud.discovery.ConsulLifecyle#createTags() has a bug that prevents the '/' character from being replaced which causes an illegal value to be added to the service's tags.

The servletContext.getContextPath().replaceAll("/", "") will return an updated value if the context path contains any '/' characters, but this updated value is not the value that is being added to the List of "tags".

Here is the 1.0.0.M4 version:

	private List<String> createTags() {
		List<String> tags = new LinkedList<>(properties.getTags());
		if(servletContext != null
				&& StringUtils.hasText(servletContext.getContextPath())
				&& StringUtils.hasText(servletContext.getContextPath().replaceAll("/", ""))) {
			tags.add("contextPath=" + servletContext.getContextPath());
		}
		return tags;
	}

Here is a corrected version...

	private List<String> createTags() {
		List<String> tags = new LinkedList<>(properties.getTags());
		if (servletContext != null) {
			String contextPath =  servletContext.getContextPath();
			if (StringUtils.hasText(contextPath)) {
				contextPath = contextPath.replaceAll("/", "");
				if (StringUtils.hasText(contextPath)) {
					tags.add("contextPath=" + contextPath);
				}
			}
		}
		return tags;
	}

**Comment by spencergibb** [comment]
So the real problem is `/` is not allowed in consul tags?

**Comment by domelz** [comment]
Yes, that is what I  have observed.

I have an application.yml that specifies a server.contextPath of “/configuration” which is being added by ConsulLifecycle#createTags(). It appears that the intent of createTags() was to strip out ‘/’ characters from the context path, but the updated value is not being added as a tag.

application.yml
server:
  contextPath: /configuration
logging:
  level:
    com:
      sas:
        configuration: DEBUG


bootstrap.yml
spring:
  application:
    name: configuration
  cloud:
    consul:
      config:
        enabled: true
      discovery:
        enabled: true
        healthCheckInterval: 60s
        preferIpAddress: false
        tags:
          - proxy
      enabled: true


The following WARNing is observed in the consul log.

2015/12/02 10:21:49 [WARN] Service tag "contextPath=/configuration" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics
dashes.
2015/12/02 10:21:49 [INFO] agent: Synced service 'configuration:8080'
2015/12/02 10:22:42 [WARN] agent: check 'service:configuration:8080' is now critical

**Comment by domelz** [comment]
Yes, that seems to be the author's intent.

I have an application.yml that specifies a server.contextPath of “/configuration” which is being added by ConsulLifecycle#createTags(). It appears that the intent of createTags() was to strip out ‘/’ characters from the context path, but the updated value is not being added as a tag.

application.yml
server:
  contextPath: /configuration
logging:
  level:
    com:
      sas:
        configuration: DEBUG


bootstrap.yml
spring:
  application:
    name: configuration
  cloud:
    consul:
      config:
        enabled: true
      discovery:
        enabled: true
        healthCheckInterval: 60s
        preferIpAddress: false
        tags:
          - proxy
      enabled: true


The following WARNing is observed in the consul log.

2015/12/02 10:21:49 [WARN] Service tag "contextPath=/configuration" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics
dashes.
2015/12/02 10:21:49 [INFO] agent: Synced service 'configuration:8080'
2015/12/02 10:22:42 [WARN] agent: check 'service:configuration:8080' is now critical

**Comment by spencergibb** [comment]
The reason for the check for `/` was to not include a context that was just `/`.

**Comment by domelz** [comment]
Regarding the WARNing message that appears in the Consul log

2015/12/02 10:21:49 [WARN] Service tag "contextPath=/configuration" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics
dashes.

Is it valid for ConsulLifecyle#createTags() to create a tag that contains an '=' character?

**Comment by spencergibb** [comment]
It is just a warning. Not sure how tags would be looked up in DNS, but having non-dns characters prevents it.

**Comment by domelz** [comment]
OK, thanks for your comments.
