### ISSUE TITLE
Planned Release Date

### ISSUE THREAD

**Issue by yairogen** [spring-cloud/spring-cloud-consul#124]
I've been tasked to checkout the spring cloud support for consul. As far as I can see the support is only in Brixton and millstone but not released?

Can you say what's your estimation for a formal release date?

**Comment by spencergibb** [comment]
Q1 2016 is what we are committed to. Hopefully January, if not February.

**Comment by yairogen** [comment]
@spencergibb, Thanks.

Can you confirm that the issues described here:
https://github.com/spring-cloud/spring-cloud-netflix/pull/745
and here:
https://github.com/spring-cloud/spring-cloud-netflix/pull/735

are fixed?

is there a milestone that contains these fixes which I could test? I got the same error with the conflict early last week trying out the M4 release - so i'm blocked as of now and can't move to Brixton because of this issue.
