### ISSUE TITLE
How to add custom consul property source?

### ISSUE THREAD

**Issue by Ya3Sh** [spring-cloud/spring-cloud-consul#125]
Hi,
Would like to know what would be convenient way to add a custom consul property source. It seems by default config/application and config/appName property source gets created (assuming there are no active profiles). I am looking for a way to say add config/appName-2 to existing list. Possible?

**Comment by spencergibb** [comment]
No, can you tell me why you want to do this?

**Comment by Ya3Sh** [comment]
When I asked that question I was thinking of reading properties of
different application inside another application. Later realized that such
(shared) properties can be moved to "config/application" instead.
Having said that I thought there could be a way to read properties of
another app in say same product suite.

On Mon, Jan 11, 2016, 1:45 PM Spencer Gibb <notifications@github.com> wrote:

> No, can you tell me why you want to do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-consul/issues/125#issuecomment-170649274>
> .
>
-- 

Sent from mobile

**Comment by spencergibb** [comment]
Why wouldn't you use a special profile for this?

**Comment by Ya3Sh** [comment]
You meant special profile at say config/application?

On Mon, Jan 11, 2016, 6:42 PM Spencer Gibb <notifications@github.com> wrote:

> Why wouldn't you use a special profile for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-consul/issues/125#issuecomment-170733698>
> .
>
-- 

Sent from mobile

**Comment by spencergibb** [comment]
Something like `config/application,myprofile`.

**Comment by Ya3Sh** [comment]
Will think about it. Thanks.

On Mon, Jan 11, 2016, 6:50 PM Spencer Gibb <notifications@github.com> wrote:

> Something like config/application,myprofile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-consul/issues/125#issuecomment-170734972>
> .
>
-- 

Sent from mobile
