### ISSUE TITLE
Can't set server list from config

### ISSUE THREAD

**Issue by yairogen** [spring-cloud/spring-cloud-consul#132]
I'm comparing Eureka VS Consul and I can't set the server list: ConsulServerList class from config as it doesn't have a default empty constructor.

In Eureka client and ribbon-core I used this:

```
myClient.ribbon.ribbon.NIWSServerListClassName=com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
```

And this worked fine.

Trying this:

```
myClient.ribbon.ribbon.NIWSServerListClassName=org.springframework.cloud.consul.discovery.ConsulServerList
```

Fails on: 
```
java.lang.NoSuchMethodException: org.springframework.cloud.consul.discovery.ConsulServerList.<init>()
```

**Comment by spencergibb** [comment]
`ConsulServerList` requires dependencies be injected by Spring. Why are you needing to do this? Using spring-cloud-consul should autowire `ConsulServerList`. Using [`@RibbonClient`](http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_customizing_the_ribbon_client) is how we wire spring classes into ribbon.

**Comment by yairogen** [comment]
I have an existing library that wraps rxnetty. This library is initialized using a factory api and doesn't impose spring injection as default as to not change backward compatibility. 
I'd expect spring consul support to follow the lines of spring cloud eureka support. The latter does support setting classes externally and configure them based on configuration rather than injection.

**Comment by spencergibb** [comment]
Not using spring injection is not currently a goal.

**Comment by yairogen** [comment]
@spencergibb is rxnetty supported by @RibbonClient?

**Comment by spencergibb** [comment]
We don't have any explicit support for rxnetty anywhere.

**Comment by yairogen** [comment]
Hence my need to support  non injected clients as my customers need good async clients that use ribbon.

**Comment by spencergibb** [comment]
We support spring and spring-boot. There is [work being done](https://github.com/spring-projects/spring-reactive) in the spring framework to support netty and reactive workflows.
