### ISSUE TITLE
Incorrect IP address registered with Consul

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-consul#134]
When I run my service locally within my IDE (by application class annotated with @EnableDiscoveryClient), Consul (running in Docker Machine) appears to register the IP address of the VM, rather than my local machine IP.

i.e.calling http://docker.machine.vm.ip:8500/v1/catalog/service/my-service gives me

```
[
  {
    Node: "dockermachine",
    Address: "192.168.99.100",
    ServiceID: "mio-events-service-docker-compose-18102",
    ServiceName: "mio-events-service",
    ServiceTags: [ ],
    ServicePort: 18102
  }
]
```
Note that the address is 192.168.99.100, which is the IP of the VM rather than the IP of my local machine. This used to work, but I'm at a loss as to what's changed. Any ideas?

Thanks

Nick

**Comment by spencergibb** [comment]
What version are you using? What is your configuration?

**Comment by nickcodefresh** [comment]
I figured out that I can set `spring.cloud.consul.discovery.preferAgentAddress` to make Spring Cloud Consul register using the VM IP.
