### ISSUE TITLE
Spring Cloud Consul not compatabile with Docker Machine

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-consul#136]
Apologies if I'm raising a number of issues at the moment, but whilst trying to upgrade to the latest M5 release, I keep hitting different issues. I'm currently running vM5 and the latest version of Consul. I'm using Docker Machine and Docker Compose to start various service containers, and using gliderlabs/registrator to handle contain Consul registration:

```
http://dockermachine:8500/v1/catalog/service/mongo-28017
```

```
[
   {
      Node: "dockermachine",
      Address: "192.168.99.100",
      ServiceID: "b1724ed4ff00:mongodb:28017",
      ServiceName: "mongo-28017",
      ServiceTags: [ ],
      ServiceAddress: "172.20.0.4",
      ServicePort: 28017,
      ServiceEnableTagOverride: false,
      CreateIndex: 25,
      ModifyIndex: 25
      }
]
```

Notice the two IP addresses. The 192 address is the IP of the Docker Machine VM, whilst the 172 one is the IP of the container itself. Now I need to wire my application's MongoDB connection to this instance (running from IntelliJ, not a Docker container instance), and I do so using:

```
List<ServiceInstance> services = discoveryClient.getInstances("mongo-28017");
```

The ServiceInstance objects returned from org.springframework.cloud.client.discovery.DiscoveryClient returns the container IP, which means my application fails to start (as it needs to go through the docker VM to get to the container). 

The Spring Cloud Consul code that handles this appears to be ```org.springframework.cloud.consul.discovery.IpAddressUtils#getCatalogServiceHost```

```
	public static String getCatalogServiceHost(CatalogService service) {
		if (StringUtils.hasText(service.getServiceAddress())) {
			return service.getServiceAddress();
		} else if (StringUtils.hasText(service.getAddress())) {
			return service.getAddress();
		}
		return service.getNode();
	}
```

In this instance I need to use the address field, not the service address. Are we sure this is the correct way round?

Thanks

Nick

**Comment by spencergibb** [comment]
https://www.consul.io/docs/agent/services.html

`ServiceAddress` is optional. So if it is there, I use it. Address is the address of the node.

See #76 for the context.

What would you have me do differently?

**Comment by nickcodefresh** [comment]
I've figured out that was I was doing was fundamentally wrong. I'm having to manually wire up a MongoDB connection via Consul, pretty much outside of Spring Cloud (i.e. setting up the database connection via the IPs returned via Consul).  To be able to run locally within my IDE, I now have a Spring profile called "development", which overrides the hostname returned by Consul to always set it to the IP of the local Docker Machine VM. When my application runs as a container, this profile isn't active and hence, the correct container IPs are used.
