### ISSUE TITLE
Config support for failFast=false

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-consul#137]
In other words, if consul isn't available, don't worry about using consul as config.

**Comment by doktoric** [comment]
+1

**Comment by lalyos** [comment]
+1

**Comment by mhmxs** [comment]
+1

**Comment by spencergibb** [comment]
You can now set `spring.cloud.consul.config.failFast=false`.

**Comment by mhmxs** [comment]
Hi, i tried this flag, but it doesn't work with application.yml or application.properties. Doesn't take care. If i pass -Dspring.config.location=file:/path/of/property/application.properties works as well. Have you got any idea why this should happen?

**Comment by spencergibb** [comment]
It needs to go in bootstrap.yml. I'll fix the docs.

**Comment by spencergibb** [comment]
Docs updated here 9ae832f6435f9e241da0a4ab5f4490db16cd8b7f.

**Comment by mhmxs** [comment]
Works fine, thank you.

**Comment by spencergibb** [comment]
NP, thanks for the feedback.
