### ISSUE TITLE
Consul support for tomcat traditional deployment

### ISSUE THREAD

**Issue by aleuchanka** [spring-cloud/spring-cloud-consul#141]
Hi, 
Our project moves toward micro service architecture, but due to some historical reasons we want to start deployment first in tomcat container.
Right now it's working with embedded container, but consul ignored in case of traditional (war deployment) to tomcat.
I am happy to contribute if you will give some directions.
As I understood now AbstractDiscoveryLifecycle coupled ApplicationListener<EmbeddedServletContainerInitializedEvent> , if any tool exist that could make run it in tomcat container?
Where should I start?
Thank you in advance for your help.
Best Regards,
Anatoli

**Comment by spencergibb** [comment]
It's all based on Spring Boot, which supports war deployments. I haven't tried it, but nothing is preventing you from doing that. `ApplicationListener` doesn't prevent using war.

**Comment by spencergibb** [comment]
Closing for lack of feedback.
