### ISSUE TITLE
Ability to specify network for registration of services

### ISSUE THREAD

**Issue by oiavorskyi** [spring-cloud/spring-cloud-consul#142]
In most of the scenarios current behavior of registering a service with Consul using a first non-loopback interface is perfectly fine. However, in case the service is running on the node with multiple network interfaces this behavior might lead to inconsistent results. Selecting network interface by name might be a good alternative but in the situation where the node is attached to the networks dynamically (e.g. within Docker Swarm cluster with overlay networks) the interface name might not be known at configuration time.

If this feature request is implemented it would allow specification of the network in the "IP/Mask" format (e.g. `192.168.99.1/24`) in additional property (e.g. `spring.cloud.consul.discovery.service-network`). If this property is specified then instead of looking for the first non-loopback interface to identify the IP/host of the service the discovery client will look for the first interface that is bound to this network.

As far as I understand this would require new method in the `org.springframework.cloud.util.InetUtils` in addition to `findFirstNonLoopbackAddress`. Then the `ConsulDiscoveryProperties` class could use this functionality to find the address.

Some of the decisions need to be made in terms of error handling and property precedence. For example, what would happen if the node is not bound to specified network? Should the discovery client fall back to registering with agent address or first non-loopback address? Or maybe the registration should fail altogether? At the end of the day predictability is a key in the case of dynamic networking. The ipAddress property, on the other hand, most likely should take precedence over the network binding as it is most specific setting.

I would also consider having ability to specify separately networks for the service and the health endpoint. This would handle scenario where management/health endpoints are exposed on different port from the service itself for security reasons. I would not like to expose sensitive information to all neighbor services.

**Comment by spencergibb** [comment]
This should go in spring-cloud-commons. I think there is a similar issue there https://github.com/spring-cloud/spring-cloud-commons/issues/88. Please comment on that one or open a new one if you think your request is significantly different.

**Comment by oiavorskyi** [comment]
@spencergibb Thank you. I will comment there. Do you think that Spring Cloud Consul would require any  changes to support this feature? If yes then it might be an option to keep this issue open for tracking purposes.

**Comment by spencergibb** [comment]
I don't think it will. There are properties in commons that might change.
