### ISSUE TITLE
Initial 503 status at startup

### ISSUE THREAD

**Issue by kabennett** [spring-cloud/spring-cloud-consul#143]
As described at http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html under the section Why is it so Slow to Register a Service?, it is possible, although not recommended, to configure eureka.instance.leaseRenewalIntervalInSeconds when using Eureka.

Is there a similar configuration for Consul?  After our services start, we consistently receive a 503 for a varying period of time before the services start processing requests.  I assume this is because of the same reason described in the URL above (i.e., A service is not available for discovery by clients until the instance, the server and the client all have the same metadata in their local cache [so it could take 3 hearbeats]).

**Comment by spencergibb** [comment]
So the eureka client sends heartbeats to the eureka server. Consul pings your app (a http health check). So it's a different model. You can configure how often consul performs the healthcheck with `spring.cloud.consul.discovery.healthCheckInterval`. The default is `10s` (10 seconds). If you're using ribbon, you can tweak that as well.

**Comment by kabennett** [comment]
Thanks, Spencer. We are using Ribbon. What is the configuration property for configuring Ribbon's health check interval?  I haven't found it online or in the source code yet.

Also, is there, or do you plan to document, a site where all of the possible Spring Cloud project configuration properties are listed?

**Comment by kabennett** [comment]
By the way, we are using Feign with Ribbon.

**Comment by kabennett** [comment]
OK, after digging some more into the source code, I found spring.cloud.consul.discovery.heartbeat. I see that it's set by default to 30 seconds. Is this the property I need to change?

**Comment by spencergibb** [comment]
@kabennett you only need to set the heartbeat if it's enabled, which it isn't by default.

**Comment by spencergibb** [comment]
The ribbon property is `ribbon.ServerListRefreshInterval=10000` (Case is important).

**Comment by kabennett** [comment]
Thank you for your response, Spencer.  I will tweak these settings to reduce the period of time that we receive the 503 statuses.
