### ISSUE TITLE
How do I read consul configuration from property source

### ISSUE THREAD

**Issue by achilu** [spring-cloud/spring-cloud-consul#150]
I get this on spring bootstrap
```
2016-03-09 14:31:30.808  INFO 15942 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource [name='consul', propertySources=[ConsulPropertySource@1266007936 [name='configuration/SampleApp/', properties=com.ecwid.consul.v1.ConsulClient@11857203], ConsulPropertySource@2006592145 [name='configuration/apps/', properties=com.ecwid.consul.v1.ConsulClient@11857203]]]
```
Now I would like to read the values of key with name `configuration/SampleApp/` , I would like to bind this the key using  @Value such that I can get the value directly into a variable, can I achieve this?

**Comment by spencergibb** [comment]
Normal boot external configuration. Read the doc [here](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html).

If you're using actuator look at `/env` to see all available values.

`configuration/SampleApp/` is one of the the roots of your consul config, you'll never reference it directly. If there was a key named `configuration/SampleApp/foo` with value of `bar`, this is how you'd reference it.

```
@Value("${foo}")
String foo; // will have value bar
```

**Comment by achilu** [comment]
thank you Spencer, however I am unable to get this to work

I have the consul KV as configuration/SampleApp/foo, but when I use actuator I am unable to see the values for it, here is  what I see at /env
{"profiles":[],"server.ports":{"local.server.port":8080},"consul:configuration/SampleApp/":{},"consul:configuration/apps/":{},

**Comment by spencergibb** [comment]
What does `bootstrap.yml` look like?

**Comment by achilu** [comment]
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      config:
        enabled: true
        format: YAML
        prefix: configuration
        defaultContext: apps
        profileSeparator: '::'
  application:
    name: SampleApp

**Comment by achilu** [comment]
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      config:
        enabled: true
        format: YAML
        prefix: configuration
        defaultContext: apps
        profileSeparator: '::'
  application:
    name: SampleApp

**Comment by achilu** [comment]
Please edit my comment above to get the correct indentation

**Comment by achilu** [comment]
@spencergibb ,

I could get this working, here is what I did

1. I removed format: YAML from bootstrap.yml and with the following code I am able to read the consul key
@EnableDiscoveryClient
@Controller
@EnableConfigurationProperties(PropertySourceBootstrapProperties.class)
public class abc {
	    
    @Value("${foo}")
    private String foo;

I am also able to see the info in /env
{"profiles":[],"server.ports":{"local.server.port":8080},"consul:configuration/SampleApp/":{"foo":"dfdg"},"consul:configuration/apps/":{}

**Comment by achilu** [comment]
I have a new issue, which is that the configuration stays as in the bootstrap mode, even if it is changed in consul the new value is not getting picked up. 

Example if "foo" is set to "bar" before the spring boot app comes up, after the springboot app comes up it reads it as "bar" , but while the app is up, if we change the value of "foo" to "sdfjhdsjhf", the springboot app still reads it as "bar"

**Comment by achilu** [comment]
I tried to refresh as per documentation https://github.com/spring-cloud/spring-cloud-consul/blob/master/docs/src/main/asciidoc/spring-cloud-consul.adoc

curl -i -X POST http://localhost:8080/refresh
curl: (52) Empty reply from server

**Comment by achilu** [comment]
I could get the refresh working with @RefreshScope in my controller class. Many Thanks!!!
