### ISSUE TITLE
Populating Consul KV

### ISSUE THREAD

**Issue by dnathanson** [spring-cloud/spring-cloud-consul#152]
This is a question or maybe an enhancement request.

For reasons I don't want to get into, we have decided to use Spring Cloud Consul for configuration rather than Spring Cloud Config.  Spring Cloud Consul seems to do most of the stuff that Spring Cloud Config does _except_ loading configuration values into the store.  We really like the idea of using Git as a repo for configuration and so I've been looking at [git2consul](https://github.com/Cimpress-MCP/git2consul) project as a way to populate Consul's KV store. Unfortunately, even though both Spring Cloud Consul and git2consul both have some configurability with respect to how properties are loaded / read from the KV store, there doesn't seem to be enough overlap to make them compatible. 

Is this project planning on providing any way to populate Consul KV?  If not, do you have a recommended way to accomplish that in a format that is compatible with Spring Cloud Consul?

**Comment by spencergibb** [comment]
This is something I want to make sure it works.

**Comment by dnathanson** [comment]
Thanks.  I had just finished hacking at a clone of git2consul to add support for YAML -> K/V and removing the filename extension from the key.  I can abandon those changes now and use the supported version of git2consul.

**Comment by dnathanson** [comment]
Works! Although I notice it doesn't recognize files with ".yaml" vs ".yml" whereas Spring Boot does.  Not a big deal for me; I just renamed a couple of files.

**Comment by spencergibb** [comment]
Good catch, fixed c6e7db055e3c950e1f0ab5f55c88102b7747a759
