### ISSUE TITLE
EnableDiscoveryClient connects to default localhost:8500 only

### ISSUE THREAD

**Issue by hbxu** [spring-cloud/spring-cloud-consul#153]
Values are ignored in the application properties file, and defaults to "localhost:8500".

spring.cloud.consul.host & spring.cloud.consul.port are ignored.
spring.cloud.consul.discovery.ipAddress & spring.cloud.consul.discovery.port is used for health check.

**Comment by spencergibb** [comment]
They need to go in `bootstrap.properties` like it says in the documentation.

**Comment by hbxu** [comment]
I was looking at: http://cloud.spring.io/spring-cloud-consul/spring-cloud-consul.html. Is this the one that you are referencing to?

**Comment by hbxu** [comment]
But indeed, it's fixed by putting into bootstrap.properties
