### ISSUE TITLE
Enable Service Discovery thru Consul but disable the registration of current service client

### ISSUE THREAD

**Issue by gt-tech** [spring-cloud/spring-cloud-consul#155]
Hello - More of a question, than issue 

I have started to analyze the spring cloud consul in one of my new projects and have got the basic integration working, had a quick question - is there a property that allows a specific service to use Consul for discovering other services but not register itself with Consul. EnableDiscoveryClient annotation currently enables both functions, something on the lines of - eureka.client.registerWithEureka property?

**Comment by spencergibb** [comment]
Not currently. Should be a simple property.

**Comment by spencergibb** [comment]
You can now use `spring.cloud.consul.discovery.register=false`.
