### ISSUE TITLE
Service discovery/filter/selection based on tags in service discovery (Consul) backened?

### ISSUE THREAD

**Issue by gt-tech** [spring-cloud/spring-cloud-consul#156]
More of a question - It seems that using property "spring.cloud.consul.discovery.tags" we are able to provide additional metadata during registration of service. In our environment, we expect to run multiple instances of the same service on same host (docker containers) and each instance of service when registers with Consul also provides metadata like - env=dev or env=test ....but name of service stays the same - say "shopping-service" , they also seem to use/share the consul instance across environments (that's part of problem)

Question - is it possible for another service to discover this "shopping-service" but filter based on a specific metadata like env=dev such that one instance of this consuming service only picks the right environment specific service instance of downstream shopping-service? Wondering if "tags"/metadata assists in this?

fwiw for now we have gotten it working by attaching those variations within spring.application.name like below and it seems to work but doesn't look elegant

spring:
  application:
    name: api-server-${env}-${tenant}

**Comment by spencergibb** [comment]
Is this any different than #154?

**Comment by gt-tech** [comment]
I think it's same as #154 thanks can be closed as duplicate
