### ISSUE TITLE
Possible to register with a different hostname and port ?

### ISSUE THREAD

**Issue by gt-tech** [spring-cloud/spring-cloud-consul#158]
I see that there's a `hostinfo` property in `ConsulDiscoveryProperties` but it doesn't seem it can be overridden, `findFirstNonLoopbackHostInfo` method in `InetUtils` also seems to support the first non-loopback over the default properties at `InetUtils` level? Is there a way where I can configure Spring Cloud Consul to register under a different hostname (that's perhaps fed to it thru some JVM property or whatever), than it trying to find the first non-loopback port?

**Comment by gt-tech** [comment]
something like eureka.instance.hostname property in case eureka registry is used!?

**Comment by spencergibb** [comment]
@gt-tech The following properties work for me:

```
spring.cloud.consul.discovery.hostname=myhost
spring.cloud.consul.discovery.ipAddress=10.0.0.1
```

They override the values set by the `hostInfo`. Test here a6803340c2ac33cbcd08f388f2eda859b7e7fea8. 

Are you having an actual problem?

**Comment by gt-tech** [comment]
@spencergibb I perhaps over-sighted this in the document so didn't know the property name, these properties work fine, it took me a bit to track them into ConsulDiscoveryProperties class ... thanks for the tip!
