### ISSUE TITLE
Spring Cloud Consul support for new ribbon-transport module?

### ISSUE THREAD

**Issue by gt-tech** [spring-cloud/spring-cloud-consul#159]
It seems from all auto-configurations that only older RestClient (based on Jersey Client) from Netflix modules gets supported for client side, is there an example/documentation of support for LoadBalancingHttpClient in new ribbon-transport module from within Spring cloud? Not sure if this is a Consul specific question or overall Spring Cloud netflix module question ... sorry!! new to Spring cloud so still figuring things out .... appreciate any help/pointers ?

**Comment by spencergibb** [comment]
There is currently no support for https://github.com/Netflix/ribbon/tree/master/ribbon-transport. If you want to open an issue for it, it should go in spring-cloud-netflix.
