### ISSUE TITLE
Embed consul ui in a spring cloud consul app

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-consul#16]
`@EnableConsulUi`? or maybe via actuator if a `s-c-consul-ui` is on the classpath.

**Comment by aatarasoff** [comment]
Why you need this, if you may see UI on consul nodes?

**Comment by spencergibb** [comment]
I kind of like the thought that it could be protected using the same facilities as other spring-boot resources.  But your right, the reason I haven't moved on this earlier is because I just use the ui in the consul process.
