### ISSUE TITLE
Spring Cloud Consul not working with a spring boot app

### ISSUE THREAD

**Issue by coding-tyro** [spring-cloud/spring-cloud-consul#160]
Hi,

I have been trying to use spring cloud consul for service registration and discovery, but caught with an exception which I am not able to resolve.Exception, main class and pom are provided as attachments.

[Exception.txt](https://github.com/spring-cloud/spring-cloud-consul/files/182038/Exception.txt)
[Main Class.txt](https://github.com/spring-cloud/spring-cloud-consul/files/182039/Main.Class.txt)
[pom.txt](https://github.com/spring-cloud/spring-cloud-consul/files/182041/pom.txt)

Things I have tried to resolve the same:-

1. Disabled @EnableDiscoveryClient
Gives another exception:-java.lang.ClassNotFoundException: org.springframework.cloud.context.named.NamedContextFactory
2. To resolve this, added spring-cloud-commons dependency -1.1.0-BUILD SNAPSHOT
--Still caught with same exception
3. Put cloud-commons to the managed version rather than 1.1.0 BUILD-SNAPSHOT
--Gives another Exception:-ClassNotFoundException :-actuator.HasFeautres

In a jist, none of the above possible solutions is able to solve the problem. Please look into the matter and provide with any other possible solutions.

Thanks,
Anshuman

**Comment by spencergibb** [comment]
Spring cloud 1.0.x is not compatible with spring boot 1.3.x.

**Comment by spencergibb** [comment]
The bom import for spring cloud should be:

For brixton:

        <dependencyManagement>
                <dependencies>
                        <dependency>
                                <groupId>org.springframework.cloud</groupId>
                                <artifactId>spring-cloud-dependencies</artifactId>
                                <version>Brixton.BUILD-SNAPSHOT</version>
                                <type>pom</type>
                                <scope>import</scope>
                        </dependency>
                </dependencies>
        </dependencyManagement>

For angel:

        <dependencyManagement>
                <dependencies>
                        <dependency>
                                <groupId>org.springframework.cloud</groupId>
                                <artifactId>spring-cloud-dependencies</artifactId>
                                <version>Angel.SR6</version>
                                <type>pom</type>
                                <scope>import</scope>
                        </dependency>
                </dependencies>
        </dependencyManagement>
