### ISSUE TITLE
Implement ServiceInstance.getMetadata

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-consul#162]
New from spring-cloud/spring-cloud-commons#56.

See https://github.com/spring-cloud/spring-cloud-zookeeper/commit/ed8001b866e1731e786ba130741c045d64d3e69a.

My first thought is to use tags with `name=value` pairs (there is precedence for that 6e4a6c686d59dcb1475a77e75044a5b2eeb48b53).

When proper k/v metadata comes in consul https://github.com/hashicorp/consul/issues/1107, we can move this over.

**Comment by ahawtho** [comment]
@spencergibb Are you suggesting that we add a metadata entry _only_ for tags of the form <code>name=value<code/>? I had already posted on #161 with some ideas for exposing tags that conform to the hashicorp recommendations (DNS name segment compatible). We could probably make use of this approach, but it would be better IMO if there were a way to support all consul tags, especially those that follow the "official" recommendations.

**Comment by smcvb** [comment]
Sorry to reiterate on this, but this ticket lets me assume that the `Metadata` on the `ServiceInstance` is leveraged by Spring Cloud Consul.
The docs (on ['Metadata and Consul tags'](https://github.com/spring-cloud/spring-cloud-consul/blob/master/docs/src/main/asciidoc/spring-cloud-consul.adoc)) actually suggest that it is yet to be implemented.

What is the truth in this case?

**Comment by spencergibb** [comment]
Consul itself doesn't support metadata on services yet. We "fake" it by using name value pair tags.

**Comment by smcvb** [comment]
Ah alright, that's good to know.
Is there any indication when/if it will support the `ServiceInstance.metadata`?

**Comment by spencergibb** [comment]
I don't know

**Comment by lucwillems** [comment]
hi ,
consul-api has now support in version 1.4.0 for CatalogService.nodeMeta() which seems to be the metadata for the service.

**Comment by marbon87** [comment]
Hi @spencergibb , any plans to support Servicemeta from consul?
