### ISSUE TITLE
Can spring consul bus be used with spring cloud 1.0.0 M6?

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-cloud/spring-cloud-consul#163]
I'm wondering if spring cloud bus can be used at some milestone level(M6) at the moment.

p.s. Is there a spring cloud gitter?

**Comment by spencergibb** [comment]
Is your question about the spring cloud consul bus or spring cloud bus?
If it's about consul bus, then no it can not. The consul bus isn't ready for release and will come as a service release of brixton (after GA). https://gitter.im/spring-cloud/spring-cloud
