### ISSUE TITLE
Populate consul with default values

### ISSUE THREAD

**Issue by samuel-pt** [spring-cloud/spring-cloud-consul#170]
We are using spring-cloud-consul-config to load properties from consul. We are loading properties using @Value. 

If we run our application for the first time, we would like to run with default values.
That is, if consul does not contain the properties, we would like start the application with default values and populate the consul with default values as well. 

Currently the application itself didn't start if a property is not present in consul.

Could you please enhance spring-cloud-consul support, 
1. Start the application with default values if property not present in consul
2. Upload default values to consul, if the property not exist in consul.

**Comment by spencergibb** [comment]
A few things, I'd recommend using `@ConfigurationProperties` rather than `@Value`. You can put defaults they. If you use `@Value`, do something like `${my.key:defaultValue}` for a default.

I'm inclined to not change the consul key value store by uploading defaults.
