### ISSUE TITLE
Issue with injecting Ribbon/Consul-enabled RestTemplate between Briston M5 and BUILD-SNAPSHOT 

### ISSUE THREAD

**Issue by russmiles** [spring-cloud/spring-cloud-consul#171]
I've upgraded the following project to BUILD-SNAPSHOT (in the hope to get hystrixcommand and fallback methods working, but that's another story): https://github.com/antifragilesoftware/simple-boot-microservice-consumer.

With the dependencies set to Brixton.M5 the test runs and everything works at runtime with Consul being used for service discovery and ribbon being use to round-robin against the discovered service instances; all through using the injected RestTemplate.

However if I upgrade the Brixton.BUILD-SNAPSHOT the test fails as it can't get hold of a RestTemplate? Problem or PEBKAC?

**Comment by spencergibb** [comment]
No, we made a breaking change. A `RestTemplate` is no longer created automatically ([docs](https://github.com/spring-cloud/spring-cloud-commons/blob/master/docs/src/main/asciidoc/spring-cloud-commons.adoc#spring-resttemplate-as-a-load-balancer-client)).

You need to
```
    @LoadBalanced
    @Bean
    RestTemplate restTemplate() {
        return new RestTemplate();
    }
```
And it will be configured for ribbon.
