### ISSUE TITLE
Application packaged as war fails to register with consul

### ISSUE THREAD

**Issue by bagerman** [spring-cloud/spring-cloud-consul#173]
I am packaging my application as war to be deployed on Tomcat. It successfully pulls configuration off but fails to register with consul. It appears that to register AbstractDiscoveryLifecycle->ConsulLifecycle needs a port number which in turn is only set for EmbeddedServletContainer's (AbstractDiscoveryLifecycle.onApplicationEvent). Moreover, this event never fired for non-embedded container apps. 

I am trying to switch from Eureka (where both war/jar packages worked) based registry to Consul and was wondering what would be a work around? Thanks
Alex

**Comment by n3integration** [comment]
:+1:

**Comment by spencergibb** [comment]
I'm not positive if you can get the port from a deployed war. Is that possible @dsyer? The intermediate answer is to set `server.port`.

**Comment by dsyer** [comment]
There's no way for an app in an external container to know its port in general. So yes, I'd say you have to configure it in.

**Comment by bagerman** [comment]
I tried to set server.port but it did not help. I think the problem is that AbstractDiscoveryLifecycle.onApplicationEvent is not invoked when application runs in container as it expects EmbeddedServletContainerInitializedEvent event.

**Comment by spencergibb** [comment]
@bagerman or @n3integration I'd love for you to try snapshots and verify.

**Comment by spencergibb** [comment]
I had to roll this back, as it broke other things.

**Comment by mpaltanea** [comment]
Hi,
I'm facing the same issue while trying to deploy as WAR in an external Tomcat. Are there any plans to treat this in a future release?
Thank you, 
Marius

**Comment by dsyer** [comment]
It's not clear to me what doesn't work. If you set `server.port` it should be fine, I think.

**Comment by mpaltanea** [comment]
I believe it's because at the moment AbstractDiscoveryLifecycle.onApplicationEvent() can only be invoked with an EmbeddedServletContainerInitializedEvent, which in turn requires the embedded server

**Comment by dsyer** [comment]
Yes, but that doesn't do anything with `server.port`. That part is orthogonal.

**Comment by tommyJimmy87** [comment]
Hello everyone,
i have the same problem when deploy my web application in Jboss EAP 6,7 and Tomcat 7, Spring Cloud Consul doesn't register the service.  Instead if i start my application throught Tomcat Embedded Servlet Container or Undertow Embedded Servlet Container it work very well. 
Have you solved the problem? 

Thanks

**Comment by spencergibb** [comment]
@tommyJimmy87 Not solved. You would see updates here if it were.

**Comment by tommyJimmy87** [comment]
Hi @spencergibb ,
 i'm trying last your commit and now it work well (1.1.0.M1). 
Currently when i deploy war the service can register itself very well.
Otherwise when i shutting down the server (Jboss EAP for example) my service can't deregistered.

Have you idea if can be a bug or my mistake ? 
Thanks
