### ISSUE TITLE
Discovery support for failFast=false

### ISSUE THREAD

**Issue by eugeneugrevatov** [spring-cloud/spring-cloud-consul#175]
Similar to #137 and #145 use `failFast=false` during application registration in consul (`ConsulLifecycle#register`) and so just log warning instead of application startup failing.

**Comment by eugeneugrevatov** [comment]
@spencergibb can you leave any comment about this, please?

**Comment by spencergibb** [comment]
Seems like a reasonable request. spring-cloud-netflix behaves this way because eureka registration happens on a background thread.

**Comment by demaniak** [comment]
+1 this would be very handy for development and I'm certain in some production scenarios
