### ISSUE TITLE
Are there any more effective way can discover a group of services by tag?

### ISSUE THREAD

**Issue by Robin7Ma** [spring-cloud/spring-cloud-consul#177]
I have a project need to discover a group of services that play the same role from Consul. 
And I found spring-cloud-consul support Consul tags, so I want to tag them and then use `DiscoveryClient` or `ConsulDiscoveryClient` to get them.
But I can't find any method can do it easily. 

So I write the flow code that used `ConsulDiscoveryClient` to implement it:

```Java
private Set<String> getServicesByTag(String tag) {
	Set<String> serviceIds = new HashSet<>();
	List<ServiceInstance> allInstances = discoveryClient.getAllInstances();
	for (ServiceInstance inst : allInstances) {
		if (inst.getMetadata().containsKey(tag)) {
			serviceIds.add(inst.getServiceId());
		}
	}
	return serviceIds;
}

// Main method
public void sendMsg2EveryStation(String message){
	 Set<String> serviceIds = getServicesByTag("stationAgent");
	 for (String sid : serviceIds) {
		 ServiceInstance si = loadBalancer.choose(sid);
		 // Use ServiceInstance do something...
	}
}
```

Are there any more effective way can do it?

**Comment by spencergibb** [comment]
Not currently.

**Comment by Robin7Ma** [comment]
I got it, thank you all the same.
