### ISSUE TITLE
Sending SIGTERM does not deregister service in consul

### ISSUE THREAD

**Issue by bpgray** [spring-cloud/spring-cloud-consul#178]
When sending the shutdown command to the spring-boot-actuator shutdown endpoint, spring-cloud-consul properly deregisters the service in consul . However, when sending a SIGTERM to the process directly, the application exits **without** deregistering the service in consul.

The issue could very well be upstream in spring-cloud or spring-boot.

Example console output of a spring-cloud-consul app, when receiving a SIGTERM.

```
Received killTask
Shutting down
Sending SIGTERM to process tree at pid 18872
Sent SIGTERM to the following process trees:
[ 
--- 18872 /app/java/bin/java -Djava.security.egd=file:/dev/./urandom -Dserver.port=31114 -Dmanagement.port=31115 -jar app.jar 
]
2016-04-27 05:11:02.876  INFO 18872 --- [      Thread-11] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@25d87cc1: startup date [Tue Apr 26 23:56:15 GMT 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@481b5d3c
2016-04-27 05:11:02.877  INFO 18872 --- [      Thread-11] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5aa70111: startup date [Tue Apr 26 23:56:25 GMT 2016]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@25d87cc1
```

spring-boot provides an example launch.script, so it seems like the spring-cloud-consul application should deregister its service in consul when receiving a signal from the OS (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script)

It seems like spring-cloud-consul should be registering a shutdown hook with spring-boot, or shutdown itself when receiving a signal from the OS. Maybe this is already in place and I've missed a required config option in the documentation.

**Comment by spencergibb** [comment]
Spring Cloud deregisters on shutdown of the spring context, so you aren't missing anything. From the two lines in your log, it looks like the context is shutting down. If I `Ctrl-C` a s-c-consul app, it deregisters properly.

**Comment by bpgray** [comment]
Thank you @spencergibb 
I verified that spring-cloud-consul is sending the deregister call to consul, and the issue is elsewhere in our ecosystem.

It would be helpful to log the deregister call, so it's consistent with logging the register call.
I'll close this issue and send a pull request for logging the deregister call.

Thank you!

**Comment by ajishashah** [comment]
What was the resolution for this issue? We have same issue.
