### ISSUE TITLE
Filter services by tag in ConsulDiscoveryClient

### ISSUE THREAD

**Issue by avthart** [spring-cloud/spring-cloud-consul#18]
It would be nice to filter services by tag using the ConsulDiscoveryClient. Sometimes you only want some specific services in your application.

**Comment by cah-oster** [comment]
We are doing this by editing this class today: ConsulServerList.java

**Comment by cah-oster** [comment]
We are doing this by editing ConsulServerList.java.  The getServers() method calls client.getCatalogService( this.serviceId, QueryParams.DEFAULT);
when it needs to support calling:
client.getCatalogService(this.serviceId, tags, QueryParams.DEFAULT);

This behavior change should be able to be wired in via the conditional ribbonServerList in ConsulRibbonClientConfiguration:
	@Bean
	@ConditionalOnMissingBean
	public ServerList<?> ribbonServerList(IClientConfig config) {
		ConsulServerList serverList = new ConsulServerList(client, properties);
		serverList.initWithNiwsConfig(config);
		return serverList;
	}

We ran into trouble trying to inject that replacement, in that we couldn't seem to load it at a time when IClientConfig is available, but before the conditional check in ConsulRibbonClientConfiguration.

Any pointers?

**Comment by spencergibb** [comment]
Usually that means the `@Configuration` for  your server list is getting picked up by component scanning.

**Comment by cah-oster** [comment]
Is this the pattern we should follow then?
https://github.com/spring-cloud-samples/tests/tree/master/ribbon-default-config/src/main/java/demo

Basically create a @Configuration class (that defines the ribbonServerList method) that is not loaded via componentscan or other mechanisms, then reference it in the @RibbonClients annotation?  For example:
@RibbonClients(defaultConfiguration=MyDefaultRibbonConfig.class)

**Comment by spencergibb** [comment]
Yes, that is according to the documentation http://projects.spring.io/spring-cloud/spring-cloud.html#_customizing_the_ribbon_client

**Comment by cah-oster** [comment]
Ok, I will give it a shot.  The documentation more seemed to imply it shouldn't be componentscanned unless you wanted it to be globally used (which I am fine with):

*The FooConfiguration has to be @Configuration but take care that it is not in a @ComponentScan for the main application context, otherwise it will be shared by all the @RibbonClients.*

**Comment by spencergibb** [comment]
yes, but you would also have to define you're own `IClientConfig` since there is no global one.
