### ISSUE TITLE
High log volume when consul agent down

### ISSUE THREAD

**Issue by bpgray** [spring-cloud/spring-cloud-consul#181]
Sometimes consul agents fail, or need to be restarted for various reasons.

When the agent goes down, ConfigWatch.watchConfigKeyValues() will start logging errors that include the full stack trace. If it's down for a couple of minutes, this can result in a several megabyte log file.

To prevent massive log files, there are some options:
1) Implement a longer fixedDelayString, which helps but also has side effects.
2) Don't log the full stack trace in the catch block
3) Use a back off pattern on error. One simple implementation would be for the class to track errors and introduce a sleep if the last few calls resulted in an error.

If there is a preferred option, I can work on a pull request.

**Comment by spencergibb** [comment]
1) is a user option, so nothing to do there.
2) is the simplest. I'd log the full error on debug, msg on error. I'd start here.
3) We already use spring retry
