### ISSUE TITLE
spring-cloud-consul-config doesn't read application.properties on startup

### ISSUE THREAD

**Issue by ydemartino** [spring-cloud/spring-cloud-consul#185]
I have an application.properties with the following configuration:
```
spring.cloud.consul.config.format=YAML
spring.cloud.consul.config.data-key=properties.yml

```

When I start spring-boot using debug I can see the ConsulConfigProperties only have the default values (format = KEY_VALUE, data-key = data).

Thus, most of my configuration is ignored.

On the other hand, if I pass the values using JVM parameters: 
`-Dspring.cloud.consul.config.format=YAML -Dspring.cloud.consul.config.dataKey=properties.yml`
It works as expected.

**Comment by spencergibb** [comment]
They need to go in bootstrap.properties.

**Comment by ydemartino** [comment]
Thank you, indeed, this fixes the issue.
Sorry I did not know this file existed
