### ISSUE TITLE
Agent Service Register

### ISSUE THREAD

**Issue by HagarJNode** [spring-cloud/spring-cloud-consul#186]
Testing with two spring boot applications, but I end up having to make a manual registration of my service... Shouldn't the sample example connect at boot up, using the spring.application.name and server.port? Running consul agent in dev mode tells me that my applications start listening, but they don't join. Creating the manual registration in application A do end up showing in application B when I list the services using the DiscoveryClient. 

Just sure, I did also try to set the spring.cloud.consul.discovery.register=true in my bootstrap file, but looking a bit at the code I noticed that the default should be true...
Calling discoveryClient.getLocalServiceInstance() give a warn output: "o.s.c.c.discovery.ConsulDiscoveryClient  : Unable to locate service in consul agent: ....."

A comment in the code tells that the method might have been called before registration of the service... 

Querying on consul 

curl http://localhost:8500/v1/catalog/services

gives

{"consul":[]}

Any ideas?

**Comment by HagarJNode** [comment]
Looks like the AbstractDiscoveryLifecycle at start should call the register method, that is if the configuredPort is > 0, but in the ConsulLifecycle configuredPort it taken from the server - which is setup in the register method... This must be a bug...

**Comment by HagarJNode** [comment]
Looks like there is a problem setting the port in the AbstractDiscoveryLifecycle, which should be used in the start method...

**Comment by HagarJNode** [comment]
Got around it.... it looks like the onApplicationEvent method isn't called, at least not if the spring boot application is wrapped in a war, so I made my own ConsulLifecycle that set the configuration port to the server.port, just after the super call in the constructor.

**Comment by spencergibb** [comment]
Duplicates #173
