### ISSUE TITLE
can not find consul all ref in spring cloud Brixton.M3 parent

### ISSUE THREAD

**Issue by lucifer-zz** [spring-cloud/spring-cloud-consul#187]
Hi,
     I want to use consul with spring-cloud-Brixton M3. But I could not find spring-cloud-consul-all 1.1.0.M4 ref in Brixton parent pom and found nothing in central repos. Need I download M4 code and compile it by myself ?

**Comment by spencergibb** [comment]
Brixton.RELEASE is the latest. Try and use that first.

**Comment by dsyer** [comment]
I think you mean `spring-cloud-starter-consul-all`? It's there in the Brixton.RELEASE.
