### ISSUE TITLE
IPADDRESS and IP_ADDRESS discrepancy

### ISSUE THREAD

**Issue by jihor** [spring-cloud/spring-cloud-consul#188]
When setting up Spring Cloud Consul JVM environment variables in Docker the following variables
-e SPRING_CLOUD_CONSUL_DISCOVERY_PREFERIPADDRESS={value}
-e SPRING_CLOUD_CONSUL_DISCOVERY_IP_ADDRESS={value}
are propagated to 
spring.cloud.consul.discovery.preferIpAddress and 
spring.cloud.consul.discovery.ipAddress 
respectively.

In the former case there is no underscore between IP and ADDRESS. In the latter, there is an underscore.

**Comment by spencergibb** [comment]
I'm afraid this is a spring boot issue. Not much we can do about it.

**Comment by jihor** [comment]
Ok, I thought maybe it was related to the Spring Cloud bootstrap context initialization.

If it's not, I will then check if the normal relaxed binding works (which should be ...DISCOVERY_PREFER_IP_ADDRESS) and post correct environment variable names here.

**Comment by jihor** [comment]
Yes, for some reason only preferIpAddress is bound from both and PREFERIPADDRESS and PREFER_IP_ADDRESS. IP address will not be bound bound to property if typed without underscore.

The following keys work with relaxed binding rules for Spring Boot:
-e SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS={value}
-e SPRING_CLOUD_CONSUL_DISCOVERY_IP_ADDRESS={value}
-e SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME={value}
