### ISSUE TITLE
Support watching keys and services directory 

### ISSUE THREAD

**Issue by avthart** [spring-cloud/spring-cloud-consul#19]
With Consul and other solutions like etcd, it is possible to watch for changes within services and keys directories. The current Spring Cloud API does not support this kind of functionality. Are there any plans to support this?

"Watches are a way of specifying a view of data (e.g. list of nodes, KV pairs, health checks) which is monitored for updates. "

See also: http://www.consul.io/docs/agent/watches.html

**Comment by spencergibb** [comment]
This may be howto support #1

**Comment by aatarasoff** [comment]
Yep, it will be great functionality, cause in real life, when I use docker with consul, I use consul template for real time change system configs.  For example nginx conf.

**Comment by spencergibb** [comment]
So I implemented a watch here 8ffa7e04eadb7ccdd44749a10c62f07b4cdc17f2.  I didn't implement `watches` in any kind of generic sense.  Wondering what that would look like.  Here, it's specific to the `ConsulClient` api.

**Comment by avthart** [comment]
Great! Will have a look at it.

**Comment by spencergibb** [comment]
#64 is a watch for configuration
