### ISSUE TITLE
why nodeId as hostname?

### ISSUE THREAD

**Issue by warmuuh** [spring-cloud/spring-cloud-consul#20]
i tried to setup a cluster with several docker-container and the nodeId inside these docker-containers is the containerId which is not resolvable as hostname (at least outside of a container).

i am just wondering if somewhere is stated, that the nodeId must be a (resolvable) hostname. as far as i  [see it](https://www.consul.io/docs/agent/options.html#_node) (--node parameter doc), it is hostname by default but does not have to be, so it could be an arbitrary id...

wouldnt it be better to use the address in super-call in `org.springframework.cloud.consul.discovery.ConsulServer.ConsulServer(final CatalogService service)`? or am i missing something?

**Comment by spencergibb** [comment]
@warmuuh you can now use `spring.cloud.consul.discovery.preferIpAddress=true`
