### ISSUE TITLE
Support ACL for Service Discovery

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-consul#201]
Since 0.6.0

See http://stackoverflow.com/questions/38064011/spring-cloud-consul-discovery-acl-for-catalog-services

**Comment by spencergibb** [comment]
Waiting on https://github.com/Ecwid/consul-api/pull/61

**Comment by sirlatrom** [comment]
@spencergibb go do! 😄

**Comment by spencergibb** [comment]
http://search.maven.org/#artifactdetails%7Ccom.ecwid.consul%7Cconsul-api%7C1.1.11%7Cjar

**Comment by spencergibb** [comment]
https://github.com/Ecwid/consul-api/commit/d520482ebffd1f25e598b91cc7b548b924afb5d8
