### ISSUE TITLE
RefreshEventData class inside ConfigWatch class needs to be public

### ISSUE THREAD

**Issue by bin01** [spring-cloud/spring-cloud-consul#204]
I am trying to integrate spring-boot with consul and the use case is to get notified when a property is changed on consul and if it does, take some action based on it. A typical use case might be to increase the thread pool size or disable caching.

Given that org.springframework.cloud.consul.config.ConfigWatch already publishes RefreshEvent, I could technically implement the above use case by implementing an ApplicationListener. However, RefreshEventData is currently package private and is not visible. Can we make it public instead?

**Comment by bin01** [comment]
Ping?

**Comment by spencergibb** [comment]
What data are you looking for from that class? It's just a command event that tells the `RefreshEventListener` to perform a refresh. When a refresh is done an `EnvironmentChangeEvent` is published that lists the changed keys.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
