### ISSUE TITLE
Best practice question

### ISSUE THREAD

**Issue by kabennett** [spring-cloud/spring-cloud-consul#205]
I need to have environment specific properties for each of my services, and I'm not clear after reading the documentation how to do this with Spring Cloud Consul.  Can anyone point me to an example of how environment-specific *.yml properties should be set up for a service (e.g., dev, test, prod)?

**Comment by kabennett** [comment]
Never mind.  I figured it out.  The reason I was confused is because in my application, the profile separator is '::', and the documentation was using config/testApp,dev/ as an example.  Just a suggestion, but you may want to update the documentation example to clarify that it's not necessarily a comma to be used for profile-specific properties but whatever separator you have configured.  Thanks!

**Comment by spencergibb** [comment]
hmm, the default profile separator I see in the code is `,`.
