### ISSUE TITLE
Customize SpringAggregatorFactory implementation of getClusterName() using consul discovery client

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-consul#206]
@spencergibb 

I want to customize the implementation of SpringAggregatorFactory as I want to set cluster information from consul agent. Right now this is being provided by spring cloud where it is reading this from clusterConfig given in properties file.as 

```
	      private List<String> getClusterNames()  {
		   List<String> clusters = new ArrayList<String>();
		   String clusterNames = aggClusters.get();
		  if (clusterNames == null || clusterNames.trim().length() == 0) {
			clusters.add("default");
		  }
		  else {
			String[] parts = aggClusters.get().split(",");
			for (String s : parts) {
				clusters.add(s);
			}
		  }
		  return clusters;
	      }
```

I have provided option to also read this from consul as per my project requirement as 

          private List<String> getClusterNames() {

        List<String> clusters = new ArrayList<String>();
        List<String> appNames = discoveryClient.getServices();
        if (appNames == null || appNames.size() == 0) {
            logger.info("No apps configured, returning an empty instance list");
            String clusterNames = aggClusters.get();
            if (clusterNames == null || clusterNames.trim().length() == 0) {
                clusters.add("default");
            } else {
                String[] parts = aggClusters.get().split(",");
                for (String s : parts) {
                    clusters.add(s);
                }
            }
        } else {
            for (String appName : appNames) {
                try {
                    clusters.add(appName);
                } catch (Exception ex) {

                }
            }
        }

        return clusters;
    }

I have created a local AggregatoryFactory class and configured this in local TurbineLifeCycle class as 

              public class HystrixTurbineLifecycle extends TurbineLifecycle {

                       @Resource
                         InstanceDiscovery instanceDiscovery;

                        public HystrixTurbineLifecycle(InstanceDiscovery instanceDiscovery) {
                        super(instanceDiscovery);
                          }

                          private boolean running;

    @Override
    public void start() {
        PluginsFactory.setClusterMonitorFactory(new TurbineAggregatorFactory());
        PluginsFactory.setInstanceDiscovery(instanceDiscovery);
        TurbineInit.init();
        running = true;
    }

    @Override
    public void stop() {
        this.running = false;
    }

    @Override
    public boolean isRunning() {
        return this.running;
    }
}

Now this lifecycle class in also configured as 

                    @EnableConfigurationProperties
                  @Configuration
                        public class TurbineInstanceDiscoveryConfig {

    @Resource
    private DiscoveryClient discoveryClient;

    @Bean
    public HasFeatures Feature() {
        return HasFeatures.namedFeature("Turbine (HTTP)", TurbineInstanceDiscoveryConfig.class);
    }

    @Bean
    public ServletRegistrationBean turbineStreamServlet() {
        return new ServletRegistrationBean(new TurbineStreamServlet(), "/turbine.stream");
    }

    @Bean
    public TurbineProperties turbineProperties() {
        return new TurbineProperties();
    }

    @Bean(name = "turbineLifecycle")
    public TurbineLifecycle turbineLifecycle(InstanceDiscovery instanceDiscovery) {
        return new HystrixTurbineLifecycle(instanceDiscovery);
    }

    @Bean
    public InstanceDiscovery instanceDiscovery(TurbineProperties turbineProperties) {
        return new TurbineInstanceDiscoverImpl(turbineProperties, discoveryClient);
    }
}

Now It is able to use my own implementation for Turbine instance discovery as configured above but it is not reading HystixTurbineLifeCycle which I have created to inject AggregatoryFactory . 
And it is reading this from spring cloud TurbineLifecycle.

Please help how can I configure this to use own AggregatorFactory instead of using spring cloud SpringAggregatorFactory.

**Comment by JagmohanSharma** [comment]
I am not able to find a way to do this. Can somebody help in this regard as it is bit urgent for me to implement this??

**Comment by spencergibb** [comment]
It's not something we've looked at before. Why do you need to read the cluster config from discovery?

**Comment by JagmohanSharma** [comment]
actually we need to make it dynamic in nature as we should not configure this from applicaiton.yml cluster config. So as in SpringAggregatorFactory getClusterNames() we are reading cluster config to have List of cluster, same thing we need to achieve with reading these from consul. Now this I have achieved via configuring 
@Bean
    HystrixTurbineLifecycle turbineContextListener(InstanceDiscovery instanceDiscovery) {
        return new HystrixTurbineLifecycle(instanceDiscovery, discoveryClient);
    }

and I have removed @EnableTurbine from my Application class.  and in life cycle class I have configured this. 
@Override
    public void start() {
        logger.info("Initializing Turbine");
        PluginsFactory.setClusterMonitorFactory(new TurbineAggregatorFactory(discoveryClient));
        PluginsFactory.setInstanceDiscovery(instanceDiscovery);
        TurbineInit.init();
        running.set(true);
    }
So I am now able to getClusterNames() from consul services. 

******But Now I am facing issue with InstanceObservable pollDelayMillis property as it keeps trying in this interval time even /hystrix.stream is not working due to  “MaxConcurrentConnections reached: 5” issue with 503 error.   so we are facing service slowdown issue due to this. can we override this behaviour for pollDelayMillis as if /hystrix.stream is not working and it is not getting event stream then we not keep this trying continuously. but try after some time if its start working with proper event stream from services.**

**Comment by spencergibb** [comment]
You need to update `MaxConcurrentConnections`.

**Comment by JagmohanSharma** [comment]
I am planning to update this to 10 so will this cause any performance issue?
 is hystrix.stream poller  a heavy weight process? (worried about performance after activating 10 stream connections)

**Comment by spencergibb** [comment]
`MaxConcurrentConnections` is case sensitive.

**Comment by JagmohanSharma** [comment]
Here MaxConcurrentConnections is getting updated properly to 10 as we are reading hystrix.stream.maxConcurrentConnections property in HystrixMetricsStreamServlet. 


private static DynamicIntProperty maxConcurrentConnections = DynamicPropertyFactory.getInstance().getIntProperty("hystrix.stream.maxConcurrentConnections", 5);

But still only 5 requests are being served and on 6th request it showing below error - 

"message": "MaxConcurrentConnections reached: 10".

**Comment by JagmohanSharma** [comment]
This issue can be reproduce by using this sample application - https://github.com/JagmohanSharma/HystrixThreadIssue

As here I tried with setting property hystrix.stream.maxConcurrentConnections to 10. Now 6 /hystrix.stream request works fine. But on 7th request , it get hanged untill we close other existing running stream connection(etc By closing browser tab). It does not even come to HystrixMetricsStreamServlet to check the below condition.

if (numberConnections > maxConcurrentConnections.get()) {
response.sendError(503, "MaxConcurrentConnections reached: " + maxConcurrentConnections.get());
} else {

All other my service endpoints are also not working until I close one of the running stream.

**Comment by spencergibb** [comment]
Closing as this is a function of max parallel connections in a browser. http://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser
