### ISSUE TITLE
Allow decoration of NewService registration 

### ISSUE THREAD

**Issue by dwelch2344** [spring-cloud/spring-cloud-consul#207]
We've found a few scenarios where we've wanted to easily add tags and programmatically set some of the values (extremely useful in a Kubernetes environment) and found ourselves having to override `ConsulLifecycle` to get it done. 

It'd be nice if we could decorate / instrument the service definition before it's registered with Consul. Would that be something welcome in the actual library? Perhaps something like the following: 

```
public class DecoratingConsulLifecycle extends ConsulLifecycle {

    private final Collection<Decorator> decorators;

    public DecoratingConsulLifecycle(ConsulClient client, ConsulDiscoveryProperties properties,
                                     HeartbeatProperties ttlConfig, Collection<Decorator> decorators) {
        super(client, properties, ttlConfig);
        this.decorators = decorators;
    }

    @Override
    protected void register(NewService newService) {
        for(Decorator d : decorators ){
            d.decorate(newService);
        }
        super.register(newService);
    }

    @FunctionalInterface
    public interface Decorator {
        void decorate(NewService service);
    }
}
```

If so, happy to submit a PR.

**Comment by spencergibb** [comment]
Won't be able to use `@FunctionalInterface` since we're still java 7. We'll discuss it.

**Comment by dwelch2344** [comment]
Old school... ;) I can live with that. Thanks

**Comment by spencergibb** [comment]
@dwelch2344 next year when we have a release based on spring 5 & boot 2 the baseline moves to java 8. It will be our `E` release after Camden and Dalston.

**Comment by ezraroi** [comment]
@spencergibb , this `ConsulRegistration` class will allow us to add tags to the service that are not coming from the yml?

**Comment by spencergibb** [comment]
@ezraroi you can create your own `ConsulRegistration` instance with whatever tags you wish.

**Comment by ezraroi** [comment]
thanks

**Comment by dwelch2344** [comment]
Agreed @spencergibb. Like the new changes to the API. Great work!
