### ISSUE TITLE
Document consul key/value watch support.

### ISSUE THREAD

**Issue by kabennett** [spring-cloud/spring-cloud-consul#209]
http://cloud.spring.io/spring-cloud-consul/spring-cloud-consul.html states that "watching the key value store (which Consul supports) is not currently possible, but will be a future addition to this project."

Just curious about when this feature will be integrated into Spring Cloud Consul.

**Comment by spencergibb** [comment]
Actually, the [ConfigWatch](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-config/src/main/java/org/springframework/cloud/consul/config/ConfigWatch.java) has been available since 1.0.1. Looks like we need to update the documentation.
