### ISSUE TITLE
Erroneous health checks

### ISSUE THREAD

**Issue by piotr-piastucki** [spring-cloud/spring-cloud-consul#21]
When there are more than 1 services deployed on a single node and one of them is failing it will affect the discovery of any other service deployed on the same node.

The problem is caused by the following piece of code in the ServiceCheckServerListFilter class:
```java
List<Check> nodeChecks = client.getHealthChecksForNode(consulServer.getNode(), QueryParams.DEFAULT).getValue();
boolean passingNodeChecks = true;
	for (Check check : nodeChecks) {
		if (check.getStatus() != Check.CheckStatus.PASSING) {
			passingNodeChecks = false;
			break;
		}
	}
```
getHealthChecksForNode returns health checks for all the registered services, in my case the list looks as follows:
[Node{node='ubuntu-abc', checkId='serfHealth', name='Serf Health Status', status=PASSING, notes='', output='Agent alive and reachable', serviceId='', serviceName=''}, Node{node='ubuntu-abc', checkId='service:my-gateway:8765', name='Service 'my-gateway' check', status=CRITICAL, notes='', output='', serviceId='my-gateway:8765', serviceName='my-gateway'}, Node{node='ubuntu-abc', checkId='service:my-ui:8888', name='Service 'my-ui' check', status=PASSING, notes='', output='', serviceId='my-ui:8888', serviceName='my-ui'}]

Please note that the service I am trying to look up (my-ui) is fine while another service (my-gateway) is failing. Unfortunately, the service ID is not taken into account in ServiceCheckServerListFilter and my-ui is not found. 

A quick fix is to change:
```java
if (check.getStatus() != Check.CheckStatus.PASSING) {
```
to:
```java
if (passingServiceIds.contains(check.getServiceId()) 
&& check.getStatus() != Check.CheckStatus.PASSING) {
```

BTW, It looks like another method in the same class called getPassingServiceIds does not do anything in my case as the list returned here:
```java
List<Check> serviceChecks = client.getHealthChecksForService(serviceId,
					QueryParams.DEFAULT).getValue();
 ```
seems to be always empty (bug?).

**Comment by spencergibb** [comment]
Fixed in 81c2592996e544aca94951495e425b07bb1ca2d2
