### ISSUE TITLE
ConsulLifecycle fails to deregister service when spring.cloud.config.discovery.enabled=true

### ISSUE THREAD

**Issue by vcariven** [spring-cloud/spring-cloud-consul#213]
When `spring.cloud.config.discovery.enabled=true`, `ConsulDiscoveryClientConfigServiceBootstrapConfiguration` is activated and consulLifecycle bean is instanciated during bootstrap phase so that config server can be discovered.

As a side effect, at application shutdown, the consulLifecycle bean does not seem to receive the lifecycle event that triggers the consul service deregistration. 

Similar issue seems to be described in this stackoverflow: http://stackoverflow.com/questions/38783943/spring-cloud-consul-deregister-failed-when-app-exit-because-of-use-spring-cloud

Not beeing so familiar with spring boot/cloud arcanes, did I miss something or is this a bug or is there an oscure config to work around this issue ?

Regards,

Vincent

**Comment by spencergibb** [comment]
@vcariven I am unable to reproduce this. Running from the ide and as a jar, the service is deregistered normally. Can you provide a sample that recreates the problem?

**Comment by vcariven** [comment]
Here is a sample : https://github.com/vcariven/spring-cloud-consul-demo
I run it from Eclipse STS on windows 64bit. Further explanation at : https://github.com/vcariven/spring-cloud-consul-demo/blob/master/README.md

**Comment by spencergibb** [comment]
@vcariven thanks for the project that reproduces, super helpful!
