### ISSUE TITLE
spring.cloud.consul.sample with loadbalance ，can't autowired

### ISSUE THREAD

**Issue by Keets2016** [spring-cloud/spring-cloud-consul#214]
I start consul.sample ,but when i use feignClient for other services , It throws exception.
```
@Autowired
private LoadBalancerClient loadBalancer;
```

testConsulApp-2 has been started successfully.
```
@FeignClient("testConsulApp-2")
public interface SampleClient {

	@RequestMapping(value = "/choose", method = RequestMethod.GET)
	String choose();
	
}
```

**Comment by spencergibb** [comment]
That's not enough information. What is the exception? What is your configuration? What are your dependencies?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
