### ISSUE TITLE
Turn Off Hystrix functinality

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-consul#217]
I am integrating Hystrix in an application. That application is already in production and we will be testing out hystrix integration work in sandbox before we will push it to production. My question is that is there any way to turn on/off hystrix functionality using some configuration setting?

**Comment by marcingrzejszczak** [comment]
Where would you like to turn Hystrix off? You have switches to turn off Hystrix for feign for example `feign.hystrix.enabled=false`

**Comment by JagmohanSharma** [comment]
I mean we have used HystrixCommand and wrapped our api method with this. So we want to turn off this functionality in case any issue occur in production due to this as recently it got some issues due to ThreadPoolSize or maxConcurrentConnections related failure . Which we could find out after major debugging of issue on production. so we want to have feature to disable this in case of such issues so that we do not have any prod down time.

**Comment by marcingrzejszczak** [comment]
ok so what does it have to do with Consul?

**Comment by JagmohanSharma** [comment]
sorry to raise this at wrong place , I did not noticed this as I had lot of other git hub pages at browser. I will raise this at other place. Thanks.
