### ISSUE TITLE
How to make Spring Cloud Consul register with external IP?

### ISSUE THREAD

**Issue by nlacombe42** [spring-cloud/spring-cloud-consul#219]
How to make Spring Cloud Consul register with external IP?

I run spring boot applications with spring cloud consul in docker. The application is running inside a docker network on a docker swarm.

This means that if spring consul registers with the hostname or the IP address it will get an hostname or ip address that is internal to the docker swarm. My consul server is outside the docker swarm.

This might be related to issue #192.

I would like to be able to keep my consul server outside the docker swarm network so that I can have the same consul server for my docker swarm key-value store.
I also want to be able to setup a proxy that uses consul to perform load balancing. This is why I do not want to register the spring application with the docker container ID (hostname) because this will use the docker dns load balancing when I would prefer this to be done by my proxy and potentially also with ribbon.

**Comment by spencergibb** [comment]
No need to cross post. Closing in favor of http://stackoverflow.com/questions/39461420/how-to-make-spring-cloud-consul-register-with-external-ip
