### ISSUE TITLE
Override default consul host & port 

### ISSUE THREAD

**Issue by kulkarni-bhaskar** [spring-cloud/spring-cloud-consul#22]
Is there a way to override the default consul host & port values

**Comment by spencergibb** [comment]
From [ConsulProperties](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-core/src/main/java/org/springframework/cloud/consul/ConsulProperties.java):

 - `consul.host`
 - `consul.port`
