### ISSUE TITLE
Wrong host returned in LocalServiceInstance

### ISSUE THREAD

**Issue by s4s0l** [spring-cloud/spring-cloud-consul#221]
ConsulDiscoveryClient in getLocalServiceInstance() returns host name of consul agent not the service hostname. 
Maybe i don't understand something, because it looks like someone did a lot of work to do it:
```
                Response<Self> agentSelf = client.getAgentSelf();
		Member member = agentSelf.getValue().getMember();
		if (member != null) {
			if (properties.isPreferIpAddress()) {
				host = member.getAddress();
			}
			else if (StringUtils.hasText(member.getName())) {
				host = member.getName();
			}
		}
```
Why is that? spring-cloud-zipkin is using this information and it makes zipkin data pushed with wrong hostname.

**Comment by spencergibb** [comment]
@s4s0l likely an early artifact. Consul's recommended architecture is to run the agent on the same host as the service. `getLocalServiceInstance()` was there for completeness and s-c-sleuth is probably the first project to use it and in combination with s-c-consul. It was also before you could set the hostname specifically for consul discovery.

**Comment by spencergibb** [comment]
Also if the `Service` is returned, the `Address` should be used.

**Comment by spencergibb** [comment]
There is also a `isPreferAgentAddress` property that should be used here.
