### ISSUE TITLE
applying defaultQueryTag in ConsulDiscoveryClient

### ISSUE THREAD

**Issue by pwielgolaski** [spring-cloud/spring-cloud-consul#225]
Following issue https://github.com/spring-cloud/spring-cloud-consul/pull/166
could we consider passing `defaultQueryTag` into ConsulDiscoveryClient

```
    private void addInstancesToList(List<ServiceInstance> instances, String serviceId,
            QueryParams queryParams) {
        Response<List<HealthService>> services = client.getHealthServices(serviceId,
                this.properties.getDefaultQueryTag(),
                this.properties.isQueryPassing(), queryParams);
        for (HealthService service : services.getValue()) {
            String host = findHost(service);
            instances.add(new DefaultServiceInstance(serviceId, host, service
                    .getService().getPort(), false, getMetadata(service)));
        }
    }
```

Thanks to this we can use consul to keep more than one environment on the same instance.

In my case I want to share consul instance for more than one environment, let's say DEV1 & DEV2.
So all services has tag either DEV1 or DEV2, but I dont want them to see each other in discovery.

**Comment by pwielgolaski** [comment]
would you accept pull request for this feature?

**Comment by spencergibb** [comment]
@pwielgolaski yes, that makes sense if you are using discovery client directly and not ribbon. Is that the case you're looking for?

**Comment by pwielgolaski** [comment]
Yes, it is what I want

**Comment by pwielgolaski** [comment]
I finally did this change, one thing that I noticed is that with feature enabled you can not query for consul service as it does not have default tag that match it.

**Comment by spencergibb** [comment]
What do you mean "you can not query for consul service as it does not have default tag that match it."?

**Comment by pwielgolaski** [comment]
I could be more precise.
So code like this
`List<ServiceInstance> instances = discoveryClient.getInstances("consul");`
will return empty list of instances, if you have defaultQueryTag defined.

Sample when where you used it in test 
https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/test/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClientTests.java#L60
```

**Comment by spencergibb** [comment]
I see. So it could be a problem for services registered outside of spring cloud. They would need to add the tag.

**Comment by pwielgolaski** [comment]
I think that it is whole idea of default tag

**Comment by jeffnelson** [comment]
👍 for this issue. We need the ability to discover based on a given tag
