### ISSUE TITLE
Upgrade ewcid consul-api to 1.2.1

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-consul#232]
https://github.com/Ecwid/consul-api/commit/a7021f5b314bbff78a39549508d57371d99b0897

**Comment by samuelbr** [comment]
It would be great to upgrade consul-api to 1.2.0 and add ability to configure NewCheck.deregisterCriticalServiceAfter.

**Comment by spencergibb** [comment]
- 1.2.0 https://github.com/Ecwid/consul-api/milestone/4?closed=1
- 1.2.1 https://github.com/Ecwid/consul-api/milestone/5?closed=1
