### ISSUE TITLE
No way to disable ConsulHealthIndicator

### ISSUE THREAD

**Issue by tehjakey** [spring-cloud/spring-cloud-consul#234]
I need to disable the ConsulHealthIndicator within a springboot application that uses spring-cloud-consul. My springboot application has its /health endpoint invoked by an ELB very frequently which results in the ConsulHealthIndicator being invoked. This in turn places unwanted load on the Consul server. I would rather disable the health check than slow down the /health calls from the ELB.
So far, I can only disable the ConsulHealthIndicator by disabling consul via. spring.cloud.consul.enabled=false Obviously i don't want this as it disables all of the Consul integration.

**Comment by tehjakey** [comment]
Perfect. Thank you @spencergibb

**Comment by theAmneziac** [comment]
For some reason, this isn't working for me.  I have `management.health.consul.enabled = false` set in my configuration, but the consul health indicator is still present in my health check.

My `org.springframework.cloud:spring-cloud-starter-consul-all` version is `1.2.1.RELEASE`.

As a sanity check, I tried `management.health.diskspace.enabled = false` and saw that the diskSpace health indicator went away.  I was able to get rid of the health check by creating a bean called `consulHealthIndicator` that overrides the one from Spring Cloud Consul, but I hope there's a better way.

Please let me know if you can tell what's going wrong, thanks!

**Comment by spencergibb** [comment]
@theAmneziac if you can produce a sharable project that recreates the problem, please open a new issue.

**Comment by theAmneziac** [comment]
@spencergibb I realize now that this problem only happens when I include spring-cloud-starter-consul-all in a **Grails application**.  It doesn't happen in a plain Spring application.  Do you have any intuition about this?  If not, it's fine, this is probably an issue with Grails, not Spring Cloud Consul.
