### ISSUE TITLE
Consul not marking service as down

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-consul#243]
I've added a custom health indicator to my app which correctly shows up as DOWN in `/management/health` when invalid. My [Spring Boot Admin](https://github.com/codecentric/spring-boot-admin) app shows it as down but Consul is still showing it as up.

(service is called flex-indexelastic-service)

![image](https://cloud.githubusercontent.com/assets/5837418/19924398/a13fb980-a0e3-11e6-8e2c-2cb87337e554.png)

![image](https://cloud.githubusercontent.com/assets/5837418/19924410/b200c368-a0e3-11e6-863f-87425fb0fe7b.png)

![image](https://cloud.githubusercontent.com/assets/5837418/19924438/d04bd3d0-a0e3-11e6-9dbd-9124974cd40c.png)

![image](https://cloud.githubusercontent.com/assets/5837418/19925809/7276e3c0-a0e9-11e6-8338-8347dcb2a06d.png)

Any ideas why this might be? I'm using  Spring Boot 1.3.6.RELEASE and Spring Cloud Brixton.SR5.

Thanks

Nick

**Comment by spencergibb** [comment]
Which check did you configure your service with http (default) or ttl?

**Comment by nickcodefresh** [comment]
Well we're not setting anything explicitly, so whatever is the default. What's the difference between the two? I can't find anything in the reference documentation regarding this

**Comment by spencergibb** [comment]
> with http (default) or ttl

**Comment by nickcodefresh** [comment]
Http then I guess

**Comment by spencergibb** [comment]
I'm unable to duplicate with a simple project:
With a custom health indicator that is down I get the following from `/health`
```
{
    "status": "DOWN",
    "healthIndicator": {
        "status": "DOWN"
    },
}
```

And this from `http://localhost:8500/v1/health/checks/democonsulcustomhealthindicator`
```
[
    {
        "Node": "sgibb-mbp.local",
        "CheckID": "service:democonsulcustomhealthindicator",
        "Name": "Service 'democonsulcustomhealthindicator' check",
        "Status": "critical",
        "Notes": "",
        "Output": "",
        "ServiceID": "democonsulcustomhealthindicator",
        "ServiceName": "democonsulcustomhealthindicator",
        "CreateIndex": 183,
        "ModifyIndex": 183
    }
]
```

Please share a minimal project duplicating the problem.

**Comment by nickcodefresh** [comment]
I'll check tomorrow on a non-local environment, in case that was it.  Thanks for your help so far.

**Comment by nickcodefresh** [comment]
I finally figured out what this was. It was indeed because I had spring.cloud.consul.discovery.hearthbeat.enabled set to true. Sorry for being an idiot
