### ISSUE TITLE
Make Consul Health Indicator configurable / aware of disabled discovery

### ISSUE THREAD

**Issue by salgmachine** [spring-cloud/spring-cloud-consul#244]
Hi, 

first of all I want to thank the whole spring cloud team for the amazing components you provided to the community!

My Issue:

Currently it is not possible to disable the health indicator for consul using the management namespace. 
E.g. what I would have expected is to have an option 

`management.health.consul.enabled`

so I can disable the health indicator.

The root cause for this issue is the fact that for tests I have service discovery via consul disabled. As I would like to test my own application-specific health indicators I check the content of the /health endpoint and expect the status to be "UP" when everything is working fine (basically I'm integration-testing the /health endpoint using MockMvc) 

Currently however the overall status is "DOWN" as the health indicator for consul fails: 

`"consul":{"status":"DOWN","error":"com.ecwid.consul.transport.TransportException: java.net.ConnectException: Connection refused: connect"}`

I have checked the ConsulAutoConfiguration class where I saw that the ConsulHealthConfig already does conditional loading (`@ConditionalOnClass(Endpoint.class)`) Maybe this could be extended to also take into consideration the `spring.cloud.consul.discovery.enabled` configuration property? I think this would be the way to go as from my perspective there is no point in having an (active) health indicator for a disabled functionality (like in this instance for service discovery..)

**Comment by spencergibb** [comment]
Duplicates #234

**Comment by salgmachine** [comment]
Oh sorry, didn't see that. 

Thanks @spencergibb 

keep up the good work =)
