### ISSUE TITLE
ConsulCatalogWatch should publish HeartbeatEvent only when consulIndex is really changged

### ISSUE THREAD

**Issue by lowzj** [spring-cloud/spring-cloud-consul#245]
The source code: [ConsulCatalogWatch](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulCatalogWatch.java#L68)
It will set `catalogServicesIndex` and publish `HeartbeatEvent` every time. IMO, it's unneccessary.
The `consulIndex` from the query response may be equal to the previous one cached because of query timeout after `catalogServicesWatchTimeout`.
I think it's better to update `catalogServicesIndex` and publish `HeartbeatEvent` only when `consulIndex` is greater than the previous one, like this:

```
        if (consulIndex != null && consulIndex > index) {
            catalogServicesIndex.set(BigInteger.valueOf(consulIndex));

            log.trace("Received services update from consul: {}, index: {}",
                    response.getValue(), consulIndex);
            publisher.publishEvent(new HeartbeatEvent(this, consulIndex));
        }
```

 In addition, why is `catalogServicesIndex`'s type `AtomicReference<BigInteger>`, neither `AtomicReference<Long>` nor `AtomicLong`?

**Comment by spencergibb** [comment]
It's a `HeartbeatEvent`. It's simply to notify that there was communication from the discovery service. It originally stems from the eureka client which actually sends a heartbeat. Only sending if incremented would defeat the purpose.
