### ISSUE TITLE
Refactor ConsulServerList for extensibility

### ISSUE THREAD

**Issue by jjathman** [spring-cloud/spring-cloud-consul#246]
The ConsulServerList class is not implemented in a way that allows for clients to extend the class and change it's behavior. My company has some rather unusual requirements about how we interact with Consul so having hooks within this class to change it's default behavior would be great for us. We don't want to make massive changes to how it works, so I would rather not copy/paste/update the existing class.

**Comment by spencergibb** [comment]
What are the "rather unusual requirements"?

**Comment by jjathman** [comment]
1. We have multiple data centers and a handful of services run in more of an active/passive pattern so there are certain times where we will want to get a list of services from not the default data center that consul will return
1. We use the health checks that sometimes use a warning but we want to use healthy services first, and then services with a warning when necessary
1. We want to have our clients prefer a local instance of a service when available to minimize network latency when it isn't necessary so I would like to be able to sort the returned services in a more precise manner than what Consul would return

Is this helpful? I tried extending the class but ran in to a couple road blocks. If you'd rather not make extending this class the preferred pattern that is OK, I can implement our version from scratch, it's not that much code.

**Comment by spencergibb** [comment]
At this point I'd prefer you have a custom `ServerList` until we see if more people would want this.

**Comment by jjathman** [comment]
Sure, that works too. Just wanted to put this out there in case it was useful for others.
