### ISSUE TITLE
rewrite ConsulServer.MetaInfo#getServerGroup() to support serverGroup

### ISSUE THREAD

**Issue by lowzj** [spring-cloud/spring-cloud-consul#248]
source: [spring-cloud-consul](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulServer.java#L45)

The method `getServerGroup` currently always return a null value. And I think it would be better to get the `serverGroup` from the service tags, because that services registered in consul can only provide extra infos by using tags. So `getServerGroup` could be like this: 

```
    @Override
    public String getServerGroup() {
        return getMetadata().get("group");
    }
```

And then declaring a private attribute `Map<String, String> metadata` to cache the result in order to avoid building `metadata` every time.

**Comment by spencergibb** [comment]
AFAICT, this is not used anywhere. What are you wanting to use it for?

**Comment by lowzj** [comment]
I'm trying to implement blue-green deployment(or a/b testing, or multi-version deployment). I use consul for service discovery, feign for inter-services communication, ribbon for load balancing on client. I classify instances of same service into multi-group, and implement a `IRule`to route requests to  instances of different group depends on different loadBalanceKey. 

For a simple example, there are 2 users(named Z and J) to query `service A`, and `service A` has to query some datas from `service B` by using feign and ribbon. And `service B` has 2 versions in production: version-1, version-2. I start 2 instances of `service B`, classify them into `group-1, group-2`, register them in consul and store their group info in service tags. Then I can map the request of `user Z` to `group-1`, and `user J` to `group-2` by using customized `IRule`.

And I have to extract group information from the server. Because of I'm using consul, I currently write the code in my `IRule` like this:

```
        if (server instanceof ConsulServer) {
            return ((ConsulServer) server).getMetadata().get("group");
        } else {
            return server.getMetaInfo().getServerGroup();
        }
```

So I think it may be better to rewrite `ConsulServer.MetaInfo#getServerGroup()` to support `serverGroup`. Or there is a better solution I haven't known.

And my `IRule` implementation is belonging to my `ribbon module`, so it would introduce `consul dependency` into `ribbon module`.
