### ISSUE TITLE
Server zone support for Ribbon

### ISSUE THREAD

**Issue by starlight36** [spring-cloud/spring-cloud-consul#249]
Hi~

Currently `spring-cloud-netflix` is using the `ZoneAwareLoadBalancer` as the default Ribbon load-balancer. It could be work with the zone property of `Server` implementation.  But in `ConsulServerList` there is no override method found to update server's zone, so the zone property is always `UNKNOWN` as default. 

Is there any approach to make full use `ZoneAwareLoadBalancer` with consul? Or should we change for a better load-balancer?

**Comment by spencergibb** [comment]
`DiscoveryEnabledNIWSServerList` gets the zone from the Eureka `InstanceInfo`. There is no better load balancer.

Now that consul discovery has metadata support, we could use that to set the zone.
