### ISSUE TITLE
Add support for https check with selfsigned certificate

### ISSUE THREAD

**Issue by pwielgolaski** [spring-cloud/spring-cloud-consul#261]
It seems new feature from consul that was implemented by PR https://github.com/hashicorp/consul/pull/1984 and is available in 0.7.1.

I created PR for consul-api https://github.com/Ecwid/consul-api/pull/83 to support it

**Comment by vivekasingh** [comment]
+1. In my project we are planning to use consul as discovery service and do register services with https health checks and self signed certificate and this merge is the key for us to move forward.

**Comment by spencergibb** [comment]
@vivekasingh this is depending on the consul-api PR, nothing I can do here yet.
