### ISSUE TITLE
DiscoveryClientHealthIndicator doesn't get properly initialized when using consul for service discovery and spring cloud config

### ISSUE THREAD

**Issue by pion** [spring-cloud/spring-cloud-consul#268]
I am trying to use consul for service discovery and spring-cloud-config for external configuration. 
I start the services with spring.cloud.config.enabled=true and spring.cloud.config.discovery.enabled=true - however the health indicator for discovery client reports a status of UNKNOWN.
From what I can tell the DiscoveryClientHealthIndicator is instantiated but never receives a InstanceRegisteredEvent after the consul registration (the event is published however by the ConsulLifecycle.

I am using spring-cloud-starter-consul-discovery 1.0.2.RELEASE, spring-cloud-starter-config 1.1.3.RELEASE.

**Comment by spencergibb** [comment]
Looks like you are using the `Brixton` release train. Can you try with `Camden.SR5`?

**Comment by pion** [comment]
Tried with Camden, works fine, I'll close this.
