### ISSUE TITLE
Getting only consul as a service although multiple services are registered in consul when ACL is enabled

### ISSUE THREAD

**Issue by Oddadmix** [spring-cloud/spring-cloud-consul#269]
When enabling ACL in consul only consul is returned as the registered services.

I think the issue is that the token is not passed to consul api.

`ConsulDiscoveryClient.getServices` always calls the `getCatalogServices` using the consul api and pass the Default query params ignoring the token.

**Comment by spencergibb** [comment]
Duplicates #201, see PR #233
