### ISSUE TITLE
Add conditional property to disable spring-consul-binder

### ISSUE THREAD

**Issue by aantono** [spring-cloud/spring-cloud-consul#273]
Add `@ConditionalOnProperty` guard to only instantiate the config if `spring.cloud.consul.binder.enabled` is either missing or true. https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-binder/src/main/java/org/springframework/cloud/consul/binder/config/ConsulBinderConfiguration.java#L41

Without the guard, if Consul is disabled, there is no ConsulClient and the auto-wiring fails.

**Comment by spencergibb** [comment]
Should also be `@ConditionalOnConsulEnabled`.

**Comment by GuiForget** [comment]
Any change this could be back-ported to the 1.1.x branch?

**Comment by spencergibb** [comment]
@GuiForget see 269a43eca0bfd692219b6b5a48b8c8a8a28111b9
