### ISSUE TITLE
EnvironmentChangeEvent fires before config property values are updated on first event

### ISSUE THREAD

**Issue by joshfix** [spring-cloud/spring-cloud-consul#278]
I would like to execute code when a particular config value is modified in Consul. However, the very first time a config value is modified in Consul and the EventListener catches the EnvironmentChangeEvent, Spring seems to not have populated that config property value yet. Every time thereafter, the value is properly populated when the EnvironmentChangeEvent listener is invoked.

I have provided a sample application that replicates the behavior here:

https://github.com/joshfix/demo

**Comment by spencergibb** [comment]
See [ConfigurationPropertiesRebinderAutoConfiguration.java#L75-L81](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.java#L75-L81)

> // After all beans are initialized send a pre-emptive EnvironmentChangeEvent
		// so that anything that needs to rebind gets a chance now (especially for
		// beans in the parent context)

Seems @dsyer is doing it on purpose.

**Comment by joshfix** [comment]
I'm not sure that describes the issue I'm seeing.  My EventListener doesn't even seem to catch that initial empty event that you linked.  The issue I'm having happens after the first property value change in consul.  The very first time you change a value, the change event fires, but the property isn't updated yet.  I have to manually call RefreshEndpoint.refresh() for the updated value to be set.  Every change in consul thereafter works as expected -- the change event fires and the updated property value is set.

**Comment by beeva-pablovaliente** [comment]
I am experiencing the same issue as mentioned #288 

My scenario is as follows:

* My application starts when consul is still empty
* After application is started, a key is written in consul (manually for example)
* The application cannot detect this first change until a new change is made again in consul (or refresh is called). When the second change happens, the event that arise, contains both updated keys.

Hope this helps.

Regards.

**Comment by joshfix** [comment]
FWIW, @beeva-pablovaliente, I believe it is the same issue.  The only difference between your scenario and mine is I had an initial key/value set for the property I was fetching in my event listener.

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-consul/pull/297

**Comment by spencergibb** [comment]
BTW, the updated test [failed](https://jenkins.spring.io/view/Spring%20Cloud/view/CI/job/spring-cloud-consul-master-ci/2300/) with version 0.7.2 of consul in CI. Updating to 0.7.5 let the test pass.
