### ISSUE TITLE
Register new HealthIndicator fails

### ISSUE THREAD

**Issue by jpuzzler** [spring-cloud/spring-cloud-consul#286]
I'm trying to register a Database health indicator to make it appear into the ```/health``` payload.
when only adding the ```actuator```dependency including the ```spring-cloud-starter-consul-discovery```only the following payload is returned 
```json
{
"description": "Spring Cloud Consul Discovery Client",
"status": "UP"
}
```
after adding one or many healthIndicator implementation only the following appears.
```json
{
"status": "UP"
}
````

[here's a minimal sample](https://github.com/jpuzzler/mvp-spring-cloud-consul)

It looks that the ```HealthAggregator```isn`t used or something I could not figure out.
Thanks

**Comment by spencergibb** [comment]
why do you think it fails? By default, spring boot doesn't display details.

**Comment by jpuzzler** [comment]
I removed the spring-cloud-consul dependency and have the same behaviour. looks I missed something. thanks
