### ISSUE TITLE
How to register service with consul?

### ISSUE THREAD

**Issue by kanekoh** [spring-cloud/spring-cloud-consul#289]
If the attribute 'autoRegister = false' is set, how to register service with consul later?
I'd like to register service with consul after service is ready so I want to register in onApplicationReady method.

```
@EnableDiscoveryClient(autoRegister = false)
@SpringBootApplication
@ImportResource("classpath:applicationContext.xml")
public class SpringApplication {

	@EventListener
	public void onApplicationReady(ApplicationReadyEvent event) {
		// Register service with consul
	}
```

**Comment by lowzj** [comment]
I think you could do it like this:

```java
@Autowire
ConsulLifecycle consulLifecycle;

@EventListener
public void onApplicationReady(ApplicationReadyEvent event) {
    consulLifecycle.start();
}
```

**Comment by kanekoh** [comment]
Yes, aware of that option but it's deprecated so I tried ConsulAutoServiceRegistration class however  couldn't autowire it.

**Comment by spencergibb** [comment]
The solution is to use the new `ServiceRegistry` api. See https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/test/java/org/springframework/cloud/consul/serviceregistry/ConsulServiceRegistryTests.java

**Comment by kanekoh** [comment]
The below source code is my changes to use ServiceRegistry.

```
@SpringBootApplication
@EnableDiscoveryClient(autoRegister = false)
public class SpringApplication {

	@Autowired
	private ConsulRegistration consulRegistration;

	@Autowired
	private ConsulServiceRegistry serviceRegistry;

	@EventListener
	public void onApplicationReady(ApplicationReadyEvent event) {
		serviceRegistry.register(consulRegistration);
	}

	public static void main(String[] args) {
		SpringApplication.run(SchedulerApplication.class, args);
	}
```

The above source code works for me however, I'd like to use the class `ConsulAutoServiceRegistration.class` for my solution.
As @lowzj mentioned, I tried to use that class and then found the way to autowire `ConsulAutoServiceRegistration`.
If I put `@ImportAutoConfiguration` and set `AutoServiceRegistrationConfiguration.class` in it. `ConsulAutoServiceRegistration` could be autowired.

```
@SpringBootApplication
@EnableDiscoveryClient(autoRegister = false)
@ImportAutoConfiguration({ AutoServiceRegistrationConfiguration.class })
public class SchedulerApplication {

	@Autowired
	private ConsulAutoServiceRegistration autoServiceRegistration;

	@EventListener
	public void onApplicationReady(ApplicationReadyEvent event) {
		autoServiceRegistration.start();
	}

	public static void main(String[] args) {
		SpringApplication.run(SchedulerApplication.class, args);
	}
``` 

Do you have a plan to add `AutoServiceRegistrationConfiguration` into a spring.factories file?

**Comment by spencergibb** [comment]
We already have `ConsulAutoServiceRegistrationAutoConfiguration`. Auto registration is used for just that, auto registration. No plans on trying to integrate it if `autoRegister=false`.

**Comment by kanekoh** [comment]
ok, thanks.
