### ISSUE TITLE
Distributed Configuration : support for serving plain text

### ISSUE THREAD

**Issue by orphaner** [spring-cloud/spring-cloud-consul#292]
Hy there,

I'm using spring cloud consul for distributed configuration. It works very well for the spring environment. 

But I would like to serve plain text files such as logback.xml for example (many other needs in my company). 
It exists in the spring cloud config, here is the link to doc: http://projects.spring.io/spring-cloud/spring-cloud.html#_serving_plain_text

After carefully reading your spring cloud consul documentation I've not found such a feature. I've made a bunch of tests. All unsucessfull.

Do you have any plan to add such a functionnality ?

See you,
Nicolas

**Comment by spencergibb** [comment]
So the spring cloud config functionality serves up text files using an http api. Consul already has a KV interface where you can put anything you want. I'm not sure this project needs to do anything. You can autowire a `ConsulClient` and use that.

**Comment by orphaner** [comment]
Hy Spencer, thanks for your reply.

Is there any way that those plain text files added to the consul KV might be found in the classpath during the bootstrap phase of spring boot ? (I still have my logback.xml file in mind as an example)

Thanks,
Nicolas

**Comment by spencergibb** [comment]
Not automatically. It's not a feature of spring-cloud-config client either.

**Comment by orphaner** [comment]
Too bad. It would be an awesome feature !
How hard the implementation could be ?

**Comment by spencergibb** [comment]
Difficult enough that we haven't done anything in 3 years.
