### ISSUE TITLE
upgrade consul-api version

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-consul#295]
Hi,
the new versions of the ecwid consul api has some important fixes.. one of them is they fixed the operation exception to include some information. Can the version be upgraded? 

https://github.com/Ecwid/consul-api/milestone/5?closed=1
https://github.com/Ecwid/consul-api/milestone/4?closed=1

**Comment by ezraroi** [comment]
@lchayoun

**Comment by spencergibb** [comment]
closed already via 9d393d15b4f57d1a44cb04673e5b1ed21e626b3b
