### ISSUE TITLE
Replace joda-time dependency with Java8 java.time classes

### ISSUE THREAD

**Issue by jonfreedman** [spring-cloud/spring-cloud-consul#301]
Java 7 has been end-of-life for 2 years, hopefully there is no issue with removing the Joda dependency.

**Comment by spencergibb** [comment]
The current baseline is java7 and will change with spring 5 and boot 2. Boot 2 is due Q4 2017. This change would go in a release shortly after that.

**Comment by ryanjbaxter** [comment]
There is just one place where joda-time is used 
https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/HeartbeatProperties.java#L59

It is the return type of a `protected` API.  We cannot change this until the next major release.  All other references to joda-time have been removed.

**Comment by Sineaggi** [comment]
Are there any updates to this?
