### ISSUE TITLE
How can i config with consul cluster

### ISSUE THREAD

**Issue by gaojia0814** [spring-cloud/spring-cloud-consul#307]
I have a comsul cluster, how can i config?
use spring.cloud.consul.host?

**Comment by spencergibb** [comment]
The local consul agent should be the thing joining the cluster.

**Comment by Alzerzyl** [comment]
But if local consul(the client agent) down(broken),how does it work?How to guarantee HA?

**Comment by spencergibb** [comment]
HA for what? the local consul agent process could be restarted by an watchdog process.

**Comment by spencergibb** [comment]
then the node is not part of the cluster anymore and the platform should restart it. This is not a spring cloud question, but a consul one.

**Comment by SpinSi** [comment]
> HA for what? the local consul agent process could be restarted by an watchdog process.

No no no, the local java application is not a consul agent process .  even the java application start a consul agent  ,how to confirm   it can connect **spring.cloud.consul.host** ( it  is down ).
