### ISSUE TITLE
How to configure spring-cloud-consul?

### ISSUE THREAD

**Issue by andChow** [spring-cloud/spring-cloud-consul#310]
My Consul configuration as follows
# Consul servers cluster
```
/usr/local/consul/0.8.3/consul agent -server -config-dir=/data/consul/0.8.3/server/conf -data-dir=/data/consul/0.8.3/server/data -pid-file=/data/consul/0.8.3/server/pid -datacenter lq -node=lq-server1 -bootstrap-expect=3 -client=192.168.1.2
/usr/local/consul/0.8.3/consul agent -server -config-dir=/data/consul/0.8.3/server/conf -data-dir=/data/consul/0.8.3/server/data -pid-file=/data/consul/0.8.3/server/pid -datacenter lq -node=lq-server2 -bootstrap-expect=3
/usr/local/consul/0.8.3/consul agent -server -config-dir=/data/consul/0.8.3/server/conf -data-dir=/data/consul/0.8.3/server/data -pid-file=/data/consul/0.8.3/server/pid -datacenter lq -node=lq-server3 -bootstrap-expect=3
```

# Consul client
```
/usr/local/consul/0.8.3/consul agent -config-dir=/data/consul/0.8.3/client/conf -data-dir=/data/consul/0.8.3/client/data -pid-file=/data/consul/0.8.3/client/pid -bind=192.168.2.2 -client=192.168.2.2
```

# My questions
1.  Should spring-cloud-consul-host use consul client Ip(192.168.2.2)? If yes. Does spring-cloud-consul register application must be deployed with consul client?
2.  Does register application relation with consul client should one to one?

**Comment by lowzj** [comment]
In my own experience,
* Do not set `-client` option of consul client, use its default value: `127.0.0.1`. 
* Register every application to the local consul client by using the same property `spring.cloud.conul.host=127.0.0.1`. 
* It's best to register applications to consul client although you can register them to consul servers. It's best to run consul servers on individual machines and there is no application registered to consul servers.
* The relation between register application and consul client could be `many to one`.

Hope helpful for you and correct me if anything wrong.

**Comment by andChow** [comment]
@lowzj So every registers application server must deploy consul client.

**Comment by lowzj** [comment]
Consul client should be deployed on every machine node.

**Comment by spencergibb** [comment]
@lowzj according to the consul best practices, that is correct. Consul clients should only ever connect to consul agents and the agents are configured to connect to the server cluster.

**Comment by andChow** [comment]
tks
