### ISSUE TITLE
Override service host/port registered in Consul for PaaS

### ISSUE THREAD

**Issue by raffian** [spring-cloud/spring-cloud-consul#317]
We're testing Consul with Cloud Foundry. Services register successfully, but Consul uses PCF's internal VM IP for registration, and that IP is not visible or addressable to anything outside PCF.  All services get a public route/port in PCF, and that never changes, so we want Consul to use that instead. We can configure the public route in bootstrap.yml, just looking for some pointers on what classes would be impacted.

**Comment by spencergibb** [comment]
It would be similar to what we do [here](https://github.com/spring-cloud-samples/config-repo/blob/master/application.yml#L30-L34) for eureka except for `spring.cloud.consul.discovery.{hostname|port}`.

**Comment by raffian** [comment]
Is that functionality available now in spring-cloud-consul?

**Comment by spencergibb** [comment]
It doesn't have anything to do with spring-cloud-consul. It's spring-boot and configuration placeholder replacement.

**Comment by raffian** [comment]
You're right, was expecting it would require enhancements to get working, that's certainly not the case; I got it working, no problem. Thank you!
