### ISSUE TITLE
Default configuration “spring.cloud.consul.discovery.instanceId”

### ISSUE THREAD

**Issue by hi-sb** [spring-cloud/spring-cloud-consul#318]
“spring.cloud.consul.discovery.instanceId”
This default configuration, I think, is more appropriate to change to ip+port

**Comment by spencergibb** [comment]
Can you please explain more? You haven't provided much information at all.

**Comment by hi-sb** [comment]
The same instanceId will be overwritten when the service is registered. And now the default is spring.application.name + port， by default is too easy to be covered

**Comment by hi-sb** [comment]
OMG,You not sleep？

**Comment by yangBin666** [comment]
int the docker,if i use the default config of instanceId,when i start multi instance,their's instanceId is same;
so,i config the `instance-id: ${spring.application.name}-${random.int[10000,30000]}` ,but if i restart a service
 many times,multiple instances exist for a single service,and their's state are passing,because  their's ip is same

**Comment by spencergibb** [comment]
@yangBin666 there's nothing keeping you from using ip+port as the id.

**Comment by yangBin666** [comment]
@spencergibb we are not use the fixed ip and port  in docker , so i can't set instanceId  to ip+port.i  suggest provide a property for user to chose the instanceId type

**Comment by spencergibb** [comment]
I'm not sure how that would work.

**Comment by icanfly** [comment]
@spencergibb, we met the same problems. providing a property for user to chose the instanceId type I think is a good idea.

**Comment by spencergibb** [comment]
Just set the instance id

**Comment by zhangzhixiu** [comment]
default instance id now is "application_profile_port". if one service is started in two machines, instance started earlier will be overridden by instance started later in consul. so ${random.value} has to be set to avoid this situation. but sometimes we kill -9 a service so the service will not exit properly and leave a failing service in consul. if a service start and stop serval times, there are serval duplicate service in consul point to a single instance. i think ${application_name}-${hostname|ip}-${port} is a good naming strategy to solve the situation. also you can make an interface for developers themselves to implement the naming strategy.

**Comment by spencergibb** [comment]
Have you set the property mentioned above?

**Comment by zhangzhixiu** [comment]
i think it is not a good idea to set instance id manually every instance. generating it by rule is better.

**Comment by icanfly** [comment]
@zhangzhixiu the same problems . But we have to manually modify the instance id to avoid your problems, because the official did not provide such a default setting. This problem is really annoying

**Comment by zhangzhixiu** [comment]
i misunderstood consul architecture serval months ago and the design of instanceId is reasonable.
consul is different from others like zookeeper.
every node should run a consul agent in client mode and join consul cluster.
spring cloud instance registers itself to consul which is running on localhost.

**Comment by spencergibb** [comment]
We'll stick with the current default.

**Comment by xiaoxing598** [comment]
@zhangzhixiu What you mean is that the Consul server needs to deploy a cluster separately, such as at least 3 nodes. Each server running the application installs the Consul agent, and the application on this server should connect to the local Consul agent.
Have you tried this plan? Will the coverage not occur with the same instance ID registered by different agents?
