### ISSUE TITLE
how to change the schema from http to https ?

### ISSUE THREAD

**Issue by chiku11** [spring-cloud/spring-cloud-consul#319]
I have tried changing the service scheme from http to https but no luck. I am using this below property to overwrite the value of scheme default value.

spring.cloud.consul.discovery.scheme=https

Code:https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryProperties.java#L124

When using DiscoveyClient in other microservice it still returns http instead of https

**Comment by spencergibb** [comment]
What does the consul dashboard show?

**Comment by glockhart** [comment]
Possible solution:
In the same way that the username/password/configPath are published to the consul metadata for the service instance, could the scheme also be published via the meta data?

@spencergibb If you're happy with this as a solution I can create a PR over the next few days.  If you have a different solution in mind and/or have more feedback then let me know and I can incorporate this into a PR

**Comment by spencergibb** [comment]
Closed via #409
