### ISSUE TITLE
Allow deregister on shutdown to be disabled

### ISSUE THREAD

**Issue by jonfreedman** [spring-cloud/spring-cloud-consul#321]
We are using [Prometheus](https://prometheus.io/) to automatically monitor spring-boot services as they are started using Consul.  However if a service performs an orderly shutdown it is de-registered from Consul so alerting about it being unavailable is disabled.

I think this can be implemented by introducing a `deregister` property in [ConsulDiscoveryProperties](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryProperties.java#L145) and updating [ConsulAutoServiceRegistration#deregister](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/serviceregistry/ConsulAutoServiceRegistration.java#L102) to check `!this.properties.isRegister() && !this.properties.isDeregister()`

SO Question [here](https://stackoverflow.com/questions/44647397/how-do-i-configure-spring-cloud-consul-to-not-de-register-on-shutdown)

**Comment by spencergibb** [comment]
I'm confused about this. Why would you not want it to be deregistered if it is shutdown?

**Comment by jonfreedman** [comment]
We use Prometheus to monitor our micro-service environment and have set it up so that any service registered with Consul can be monitored automatically and alerts sent to our operations team if one of the services goes down (basically described [here](https://www.robustperception.io/finding-consul-services-to-monitor-with-prometheus/)).  What happens currently if a service terminates is an alert is sent but immediately cleared as the service is de-registered & I think that behavior is subject to a race condition.

I like the fact that when I deploy a new service instance I don't need to manually register it in Consul.  I can get the behavior I want by disabling registration in spring-cloud-consul, but then I need to remember which Consul cluster I need to register with, which host/port I've started or add Consul registration into our deployment scripts.  Both of those options seem like a waste of time given adding this behaviour is a 3-line change.

I screwed up my PR - I've fixed the test I added to actually contain the code I wrote not the test I copied it from...  It's now fixed.

**Comment by jonfreedman** [comment]
Hi @spencergibb - do you need any more detail?  I think if you re-run the unit tests they will pass, they were green until I corrected some comments in my PR.  I would like to know if you will accept the change.

**Comment by spencergibb** [comment]
I still think its very strange to leave a service registered in consul if it is shut down.

**Comment by jonfreedman** [comment]
I'm not advocating that this should be the default behaviour, but consul supports service health checking and we want to take advantage of that.  I agree it makes no sense if you're using dynamic scaling, but that's not what we're doing, we want the alerts to be resolved, either by restarting the service in-place or moving it elsewhere and then manually re-registering the previous instance.

**Comment by jonfreedman** [comment]
I have been thinking a bit more about this and wanted to give some more examples.  The standard [example](https://prometheus.io/docs/alerting/rules/) for a Prometheus alert is as follows:
```
ALERT InstanceDown
  IF up == 0
  FOR 5m
```
Hopefully self explanatory, any instance which reports up == 0 for 5min is considered down.  If the instance is de-registered from Consul and removed from the Prometheus catalog and this takes less than 5min then this alert will not fire.

We could be "smarter" and define something like the following provided we are attaching enough labels to the up metric to identify a service:
```
ALERT ServiceDown
  IF max(up) without (instance) == 0
  FOR 5m
```
This would send an alert when there are no instances of a service running, irrespective of how many happen to be down.  Again this suffers from the same race condition described above.

**Comment by jonfreedman** [comment]
Can we please make a decision about merging this?  If it's not deemed suitable then I need to disable registration completely and switch to manual registration.

**Comment by jonfreedman** [comment]
I came across a feature of Consul today which is also relevant to this issue.  DeregisterCriticalServiceAfter](https://www.consul.io/api/agent/check.html#deregistercriticalserviceafter) allows you to specify a period of time after which failing a health check will de-register a service.  This is really the behavior I want.

I am considering using [registrator](https://github.com/gliderlabs/registrator/blob/master/consul/consul.go#L126) to achieve this but I would much prefer to do this via spring-cloud as that will allow us to keep all the configuration in once place.

**Comment by gabrielfsousa** [comment]
how can we tell spring when building the check to add deregister_critical_service_after option ?

**Comment by gabrielfsousa** [comment]
healthCheckTimeout:  ?
