### ISSUE TITLE
Not able to override ConsulClient

### ISSUE THREAD

**Issue by tanmaybinaykiya** [spring-cloud/spring-cloud-consul#332]
I wish to discover the Consul servers based on AWS EC2 tags that I provide. To achieve this I wish to override the ConsulClient Bean. I have the following Configuration class, but for some reason spring is picking the one defined in [ConsulAutoConfiguration][1]. What am I missing here? 

```
@Configuration
public class CustomConsulAutoConfiguration {
	
	private Logger logger = LogManager.getLogger(CustomConsulAutoConfiguration.class);

        @Inject 
        private AmazonEC2 ec2Client;

	private String environment="dev";
	
	@Bean
	@Primary
	public ConsulClient consulClient() {
		logger.info("ConsulClient *************************************** ");
		DescribeInstancesResult response = ec2Client.describeInstances(new DescribeInstancesRequest()
				.withFilters(new Filter().withName("CONSUL").withValues(this.environment)));
		logger.info("DescribeInstances response: {} ", response);
		List<String> consulServers = response.getReservations().stream()
				.map(Reservation::getInstances)
				.flatMap(Collection::stream)
				.map(Instance::getPrivateIpAddress)
				.collect(Collectors.toList());
		logger.info("consulServers: {} ", consulServers);
		return new ConsulClient(consulServers.get(0), 8500);
	}
}
```

  [1]: https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-core/src/main/java/org/springframework/cloud/consul/ConsulAutoConfiguration.java

**Comment by spencergibb** [comment]
Are you using consul configuration?

**Comment by tanmaybinaykiya** [comment]
Yes.
Sorry I forgot to update here. I added the above as candidate for org.springframework.cloud.bootstrap.BootstrapConfiguration and it picked it up.
