### ISSUE TITLE
Cannot find any details about consul config properties

### ISSUE THREAD

**Issue by Sunrry** [spring-cloud/spring-cloud-consul#333]
I find that spring cloud consul has a great many of config properties, e.g. the properties in org.springframework.cloud.consul.discovery.ConsulDiscoveryProperties.
But I cannot find any detail specification about the usage of these properties.
How can I use these configuration correctly ?
Is there any documentation that I can refer to ? 
I find some configurations seem similar to the configurations from consul, how can I make sure the relation between these two ?

Thanks in advance
Sunrry

**Comment by spencergibb** [comment]
You can find them here in the documentation http://cloud.spring.io/spring-cloud-static/Dalston.SR1/#_appendix_compendium_of_configuration_properties

**Comment by Sunrry** [comment]
This is exactly what I want.
Thanks a lot !
