### ISSUE TITLE
Custom health check in Spring Boot

### ISSUE THREAD

**Issue by udoless** [spring-cloud/spring-cloud-consul#335]
I am using consul in my spring boot project. And project's health check endpoint requires a `basic auth`. So how to config Spring to implement this? Or Can I use `script` health check in Spring?

Thanks for your reply!

**Comment by spencergibb** [comment]
Can you elaborate on what your problem is? I'm still unsure what the problem is?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
