### ISSUE TITLE
Dont force to use Servlet in class path

### ISSUE THREAD

**Issue by pwielgolaski** [spring-cloud/spring-cloud-consul#337]
I would like to use discovery in consul, but dont use servlet server 
It does not start when servlet are missing
https://github.com/spring-cloud/spring-cloud-consul/blob/87528424a962f1ed32a43c5bfb746ebaafb3bf9b/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/serviceregistry/ConsulAutoRegistration.java#L181

**Comment by spencergibb** [comment]
duplicates #314
