### ISSUE TITLE
Issue with @ConfigurationProperties annotation

### ISSUE THREAD

**Issue by mbazos** [spring-cloud/spring-cloud-consul#339]
I am not sure if this is an issue but I have exhausted my search in trying to get this to work.  In my application I have configured spring-cloud-starter-consul-config using spring boot version 1.5.6.RELEASE.

Basically what I am experiencing is that using the `@Value` annotation works and injects the consul property correctly, but when I try to use `@ConfigurationProperties` annotation it's unable to map to my properties object. Any help would be much appreciated and if there is an issue here I don't mind working on a pull request, I might just need some guidance.

Any other class Class:
```
    @Value("${app.key}")
    private String prop;
```

Properties class:
```
@ConfigurationProperties("app") <---This doesn't seem to work...and I am not sure why
public class HelloProperties {

    private String key;

    public String getKey() {
        return key;
    }
}
```

**Comment by spencergibb** [comment]
Do you reference `HelloProperties` from `@EnableConfigurationProperties` or create a bean of `HelloProperties`?

**Comment by mbazos** [comment]
I was hoping it would be that easy but here is what I have, propValueInject has the correct property from the server but my HelloProperties bean is null.

```
@SpringBootApplication
@EnableDiscoveryClient
@EnableConfigurationProperties(HelloProperties.class)
public class ServiceRegistryConsulApplication {

    @Value("${key}")
    private String propValueInject;

    public static void main(String[] args) throws UnknownHostException {
        SpringApplication.run(ServiceRegistryConsulApplication.class, args);
    }

    @Bean
    public HelloProperties helloProperties() {
        return new HelloProperties();
    }

    @ConfigurationProperties
    public static class HelloProperties {
        private String key;

        public String getKey() {
            return key;
        }
    }
}
```

**Comment by spencergibb** [comment]
I can not. I'll need a project that replicates the issue

**Comment by mbazos** [comment]
@spencergibb I created a repo here to show the problem:
https://github.com/mbazos/spring-cloud-samples

You will need a local consul server to run with the following key loaded `config/service-registry-consul/data` `key: "this came from a remote server"`

Once the server is running you can hit this endpoint:
http://localhost:8080/get-prop

This returns the value from the `@ConfigurationProperties` and the `@Value`

**Comment by bijukunjummen** [comment]
Happened to notice it just now @mbazos, you are missing a setter for `key` in `HelloProperties`

```
 public void setKey(String key) {
            this.key = key;
 }
```

Adding that in should fix it

**Comment by mbazos** [comment]
Okay I will try that out tomirrow I guess I thought the annotation would
use reflection to set on properties directly instead of setter injection.

**Comment by spencergibb** [comment]
Nope, `@ConfigurationProperties` doesn't use reflection and requires normal getters and setters.

**Comment by spencergibb** [comment]
Feel free to reopen if you think there is an issue with spring-cloud-consul.

**Comment by mbazos** [comment]
@spencergibb & @bijukunjummen Thanks for the help and sorry for opening the issue in your project, I tried it out today and it resolved my problem.
