### ISSUE TITLE
Documentation Questions

### ISSUE THREAD

**Issue by mbazos** [spring-cloud/spring-cloud-consul#343]
@spencergibb in the documents for 1.2.1.RELEASE:
http://cloud.spring.io/spring-cloud-static/spring-cloud-consul/1.2.1.RELEASE/
 under "Distributed Configuration with Consul" section 

"Configuration is currently read on startup of the application. Sending a HTTP POST to /refresh will cause the configuration to be reloaded. Watching the key value store (which Consul supports) is not currently possible, but will be a future addition to this project."

I was testing this out locally and it seems like 1.2.1.RELEASE, does in fact support watching consul keys..specifically looking at the class `org.springframework.cloud.consul.config.ConfigWatch`

Is this just a documentation issue? I don't mind helping with some documentation on the latest release if you need help, it will also help me understand the library a lot better.  Also not sure if creating a issue is the best way for this type communication.

**Comment by spencergibb** [comment]
It is a documentation issue
