### ISSUE TITLE
Deregistering Services from Consul in a dockerised environement

### ISSUE THREAD

**Issue by KhwajaMuhammad** [spring-cloud/spring-cloud-consul#344]
Is there any way to de-register a service as soon as its health check fails in consul? I found DeregisterCriticalServiceAfter (string: "")  in this link https://www.consul.io/api/agent/check.html.
 But the minimum time that can be set using the above property is 1 minute. But I need it to be less than 30 seconds or as soon as health check fails at that time it should deregister itself from consul.

**Comment by spencergibb** [comment]
You'll have to take that up with consul itself. We support `DeregisterCriticalServiceAfter` but if the minimum is 1 min, there's nothing we can do.
