### ISSUE TITLE
Spring Consul not deregistering from Consul in  Docker Datacenter deploy

### ISSUE THREAD

**Issue by andrewlarsen514** [spring-cloud/spring-cloud-consul#346]
Hi,

I have seen a few similar issues but my scenario did not seem quite the same.

Currently we have Consul deployed as a container to a Docker Datacenter cluster.  We have built Java microservices using Spring Cloud Consul framework.  The applications register with Consul just fine:

`Registering service with consul: NewService{id='cit-user-profile-gateway-e5899ed3191f9cdd8c94fe9a5427e49e', name='cit-user-profile-gateway', tags=[], address='10.0.0.3', port=8080, enableTagOverride=null, check=Check{script='null', interval=10s, ttl=null, http=http://10.0.0.3:8080/health, tcp=null, timeout=null, deregisterCriticalServiceAfter=null, tlsSkipVerify=null}, checks=null}`

However, when we run a deployment via Docker Datacenter's UCP, the command: `docker stack deploy`, Spring Consul does not deregister the service from Consul.  This is leading to issues when other services are attempting to lookup various other services via Service Discovery.   I can provide more detail on this if needed.

We have done some testing around the **/shutdown** endpoint with Spring Boot.  This will shutdown the service gracefully but I have concerns around operationalizing this approach.

Is there a recommended approach with how to deregister Spring Cloud services running in a Docker container deployed to Docker Datacenter?  

Please let me know if there is any further information I can provide.  If this is the incorrect place to post this I apoligize in advance!

**Comment by KhwajaMuhammad** [comment]
Exactly like this issue I think [https://github.com/gliderlabs/docker-consul/issues/108]

**Comment by spencergibb** [comment]
Consul has a deregister timeout you might use. Otherwise, I don't see what we can do.

**Comment by andrewlarsen514** [comment]
First off thank you for the quick response!

Is there a linux signal that spring cloud (or maybr spring boot) looks for to perform a graceful shutdown that spring consul has hooks into?  If there is documentatipn you could point me to that wpuld be great.

Thanks for these great frameworks!

**Comment by spencergibb** [comment]
If the spring boot app is shutdown gracefully, spring cloud will deregister.

**Comment by andrewlarsen514** [comment]
We were able to figure out our issue, it was not Spring-Cloud-Consul related, as @spencergibb was pointing out.  The issue we had was that we were running our spring boot jar from within an inline shell script like so:

`ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]`

The problem with this is the shell script was receiving the SIGTERM signal and not propagating it to the Java process that was spawned via the shell script, therefore Spring Boot could not exit gracefully.  

After a bit of research we stumbled onto this blog, http://veithen.github.io/2014/11/16/sigterm-propagation.html, which pointed us to running the command via exec, which will replace the shell process, and the SIGTERM will get propagated to Spring Boot.   Our ENTRYPOINT now looks like so:

`ENTRYPOINT [ "sh", "-c", "exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]`

Thanks again for the great support!

**Comment by gabrielfsousa** [comment]
can i use deregisterCriticalServiceAfter option on yml ?

**Comment by spencergibb** [comment]
@gabrielfsousa please stop spamming all of these issues with your same question. Join us on gitter to ask.

**Comment by misko566** [comment]
> We were able to figure out our issue, it was not Spring-Cloud-Consul related, as @spencergibb was pointing out. The issue we had was that we were running our spring boot jar from within an inline shell script like so:
> 
> `ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]`
> 
> The problem with this is the shell script was receiving the SIGTERM signal and not propagating it to the Java process that was spawned via the shell script, therefore Spring Boot could not exit gracefully.
> 
> After a bit of research we stumbled onto this blog, http://veithen.github.io/2014/11/16/sigterm-propagation.html, which pointed us to running the command via exec, which will replace the shell process, and the SIGTERM will get propagated to Spring Boot. Our ENTRYPOINT now looks like so:
> 
> `ENTRYPOINT [ "sh", "-c", "exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]`
> 
> Thanks again for the great support!

This was more helpful than all other think's Thanks a lot :)
