### ISSUE TITLE
ConfigWatch Constructor Just Ignore the context parameters break the legacy code silently

### ISSUE THREAD

**Issue by aemonfly** [spring-cloud/spring-cloud-consul#347]
The [ConfigWatch Constructor](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-config/src/main/java/org/springframework/cloud/consul/config/ConfigWatch.java#L57) just ignore the second parameter ``List<String> contexts`` , which will cause configWatch not work properly. (Can't receive refreshEvent), therefor breaking the legacy code silently.

I'm aware of it is deprecated but it should work properly.

**Comment by spencergibb** [comment]
The old constructor is not used. The new one sets the appropriate values. Why do you say it is not working? What version are you using?

https://github.com/spring-cloud/spring-cloud-consul/blob/ce3ca8ee99a2692c7c3dfcc09b3de64a139a7ef0/spring-cloud-consul-config/src/main/java/org/springframework/cloud/consul/config/ConsulConfigAutoConfiguration.java#L43

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
