### ISSUE TITLE
Consul registration problem

### ISSUE THREAD

**Issue by Sunrry** [spring-cloud/spring-cloud-consul#348]
Hi, I have encounter the registration problem in using consul, here is the details : 

In my environment, I want to use an another tool to help me to register my service to consul and do health check (here is [nomad](https://www.nomadproject.io/)),  rather than let the service register itself to consul. ( And I know the config : ' spring.cloud.consul.enabled ' can do this, but this config will disable everything of consul, this is not the result I want)

BUT when the service want to send a request to other services which will be registered to consul by nomad too, I want this service can get the addresses of other services from consul also.

So can I just disable the register when my service starts and unregister when my service stop and the health check ?

Thanks a lot

**Comment by spencergibb** [comment]
Have you tried `@EnableDiscoveryClient(autoRegister=false)`?

**Comment by Sunrry** [comment]
Yes, I have tried and forget to close this issue, thank you.
Thanks a lot @spencergibb
