### ISSUE TITLE
ServiceInstances always return an HTTP URI even if scheme=HTTPS is used

### ISSUE THREAD

**Issue by robachmann** [spring-cloud/spring-cloud-consul#349]
```
List<ServiceInstance> list = discoveryClient.getInstances("exampleService");
list.get(0).getUri()
```
will always return a URI starting with "http" even if the service registered itself with `consul.discovery.scheme=https`

I believe this is because the constructor parameter `secure` is hard-coded to `false`:
https://github.com/spring-cloud/spring-cloud-consul/blob/e6cbd11a03b22469aadaa90c1ade5d6cb3ca3770/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClient.java#L184

Maybe there's a way to figure out the `scheme` right before that line and pass the correct argument in order to support https-connections?

**Comment by spencergibb** [comment]
Duplicates #319
