### ISSUE TITLE
ConsulPropertySourceLocatorTests.propertyLoadedAndUpdated fails locally

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-consul#354]
When running the build locally on OSX `ConsulPropertySourceLocatorTests.propertyLoadedAndUpdated` fails.  Here is what I do

1.  Run `docker-compose up`
2.  Run `./mvnw clean package`

**Comment by spencergibb** [comment]
My guess is it's an old consul version. https://hub.docker.com/r/progrium/consul/~/dockerfile/ Running locally (`brew install consul`) and it works ok.

**Comment by ryanjbaxter** [comment]
I'm reopening this because the README instructs the user to use docker-compose.  We either need to update the docker-compose file or change the instructions in the README

**Comment by spencergibb** [comment]
I fixed the docker compse file so that docker-compose works again, why reopen?

**Comment by ryanjbaxter** [comment]
@spencergibb sorry, it wasnt clear to me that you fixed it by your comment.

**Comment by spencergibb** [comment]
My comment was just why it was broken, then my commit fixed it.

**Comment by ryanjbaxter** [comment]
I didnt see the commit ;)
