### ISSUE TITLE
ConsulAutoConfiguration#consulClient - add support for com.ecwid.consul.transport.TLSConfig

### ISSUE THREAD

**Issue by domelz** [spring-cloud/spring-cloud-consul#360]
org.springframework.cloud.consul.ConsulAutoConfiguration#consulClient(ConsulProperties) instantiates a ConsulClient as shown below.

	@Bean
	@ConditionalOnMissingBean
	public ConsulClient consulClient(ConsulProperties consulProperties) {
		return new ConsulClient(consulProperties.getHost(), consulProperties.getPort());
	}

The ConsulClient(host, port. com.ecwid.consul.transport.TLSConfig) constructor provides support for a TLS configuration.

Add support to instantiate a ConsulClient with a TLSConfig.

**Comment by cnodin** [comment]
Is this issue in planing? Does anybody know?thanks.

**Comment by spencergibb** [comment]
It is not, PRs welcome

**Comment by wdroste** [comment]
Any comments on the commit?

**Comment by spencergibb** [comment]
It is not trivial according to our definition

**Comment by spencergibb** [comment]
https://cla.pivotal.io/about#obvious-fixes

**Comment by wdroste** [comment]
np. I just need to go through some paperwork at my work in order to sign the contributor agreement.

**Comment by spencergibb** [comment]
ping @wdroste we're getting close and want to know if this will be signed.

**Comment by EvilJinious1** [comment]
Very interested in this when it appears

**Comment by wdroste** [comment]
@spencergibb still waiting on corp paperwork.

**Comment by newmodelcoder** [comment]
In case it helps others coming across this issue, I wanted to note that it __IS__ possible to enable TLS communication with Consul without any change to spring-cloud-consul __IF__ you don't mind using system properties.

I'm currently using spring-cloud-consul 1.2.1.RELEASE and successfully enabled TLS communications by:

- Use an absolute URI for `spring.cloud.consul.host`, e.g. "https://127.0.0.1".  If no scheme is specified, it sill default to "http".  (Looks like the 2.0.0 release will have a spring.cloud.consul.scheme property that can be set to "https" instead, though using an absolute URI appears to be compatible still)
- Set the system property `javax.net.ssl.trustStore` to the path of your truststore.
- Set the system property `javax.net.ssl.trustStorePassword` to the password of the truststore.

Internally, consul-api uses HttpClient, so the ConsulClient instance created by Spring will honor those properties automatically (using a constructor taking a TLSConfig is not required).   

I did not require client certs in my case, but presumably setting the other standard system properties for a keystore would work.

**Comment by elysrivero99** [comment]
Any news about this? I have the same problem trying to connect consul-config to consul over ssl

**Comment by spencergibb** [comment]
This was applied to 1.3.x and then merged forward to master.
