### ISSUE TITLE
Make it possible to proxy consul as a configuration provider through sidecar

### ISSUE THREAD

**Issue by Anonymous-Coward** [spring-cloud/spring-cloud-consul#366]
Configuring a simple spring-based sidecar is described [here](http://projects.spring.io/spring-cloud/spring-cloud.html#_polyglot_support_with_sidecar).

Configuring a spring boot application to use consul as a source of configuration is described [here](http://cloud.spring.io/spring-cloud-consul/multi/multi_spring-cloud-consul-config.html).

The problem, when creating a spring boot application to run behind a spring boot based sidecar, is that when a spring boot application using consul as the source for configuration properties runs behind a sidecar, requests to the k/v store in consul for configuration properties cannot be proxied easily by the sidecar.

In order for the proxying to happen, the spring boot application behind the sidecar would need to issue consul requests using an URL starting with "http(s)://localhost:\<sidecar port\>/consul/", but there's no way to insert the "/consul/" part in the URL. You can only configure the host and the port for consul, but not a path prefix.

(The motivation for such a setup is simple: a sidecar needs to be developed and maintained only once, and can include any kind of infrastructure-specific customizations, without the need to have those implemented and dragged along in each microservice that's part of a larger system. Without putting a sidecar in front of spring boot based microservices, you'd need to recompile and restest every single microservice when the changes you are doing are infrastructure-related, not specific to the business logic of the microservices themselves.)

The root cause is (IMO) in how the `ConsulAutoConfiguration` class constructs the `ConsulClient`. This eventually reaches the constructor `ConsulRawClient(HttpTransport httpTransport, String agentHost, int agentPort)`, where there's no way available to inject a path.

Changing this is IMO simple, but I know too little about the entire codebase to submit a full patch or create a pull request. The change would need to happen to a large extent in the non-spring dependency consul-api, though. I'm adding this here, however, because the changes may not be important to that other project, but are required to be able to run a spring boot based application using consul to provide configuration behind a spring boot based sidecar.

**Comment by spencergibb** [comment]
the sidecar was built specifically for spring cloud netflix. Consul is meant to communicate through a local agent, a sidecar in itself, according to the hashicorp guidelines. Can you tell me why you want to talk to consul thru a sidecar?

**Comment by Anonymous-Coward** [comment]
Picture two environments: local and production. 

No consul whatsoever on local. The service is able to talk freely to other services, whose URLs are configured in an application-local.properties. The developer runs all services needed on local in a single instance, with no consul and no clustered configuration whatsoever.

A clustered consul is available in production. The service/app you develop sits behind a sidecar in production and is completely cut off from the network (started so that it can only access localhost). It can only access the sidecar running on the same host/inside the same container via the sidecar port. In production, however, it _should_ take its configuration from consul, however.

**Comment by spencergibb** [comment]
That sounds like a very non-standard way of doing things. The recommended way to run consul is as a local agent.

Nothing is keeping you from defining your own `ConsulClient` bean. `ConsulClient` is a third party library. If you want to make changes to it, you'll need to open an issue with them.
