### ISSUE TITLE
Can we have timer metrics while watchConfigKeyValues in ConfigWatch?

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-consul#367]
We need to keep track of consul calls being made for each consulIndexes so I think it would be a good idea to keep timer metrics around watchConfigKeyValues() to trace calls time taken.

I have made changes regarding this. Please let me know if this really adds value here.

**Comment by spencergibb** [comment]
I think it probably would make sense, though the implementation will be different in 2.0.x with micrometer.

**Comment by JagmohanSharma** [comment]
Yes, actually we are making use of com.ryantenney.metrics's metrics-spring provided annotation support for  Dropwizard Metrics library. which is not being used spring cloud consul. I will see if we can do this by existing libraries.
