### ISSUE TITLE
Support glob matching

### ISSUE THREAD

**Issue by douglassparker** [spring-cloud/spring-cloud-consul#374]
Fabio supports either prefix or glob matching. The spring.cloud.consul.discovery.tags property does not seem to work with glob matching. Example. In this case, assume that a combination of parent id and child id are required to uniquely identify the child resource,

**Parent service**
/parents - browse all parents
/parents/{parentId} - specific parent
spring.cloud.consul.discovery.tags=urlprefix-myserver.com/parents

**Child service**
/children - browse all children
/parents /{parentId}/children - all children for a parent
/parents/{parentId}/children/{childId} - specific child

spring.cloud.consul.discovery.tags=
urlprefix-myserver.com/children,urlprefix-myserver.com/parents/*/children

In fabio.properties, I set **proxy.matcher = glob**.  It did not work. If there is a way to do this that I am overlooking, please advise. Of course, I am aware that I could use different URLs, so advise in that form is not necessary.

**Comment by spencergibb** [comment]
I have no idea what fabio is and it's unclear what you are asking for, can you clarify?

**Comment by douglassparker** [comment]
With further investigation, I am now convinced this is a Consul issue, not a Spring Cloud issue. I will close. FYI, Fabio is a load balancer that is often used with Consul. Thanks.
