### ISSUE TITLE
Document how to stop catalogServiceWatch 

### ISSUE THREAD

**Issue by TimoDoernenburg** [spring-cloud/spring-cloud-consul#375]
Hello,
currently, we are facing an issue with the spring-cloud-starter-consul-discovery dependency.
The issue appears when the consul cluster responds with "no cluster leader eligible".
This responding is reproducible when only one consul slave node is available.

If the cluster has this "unhealthy" state, the ConsulCatalogWatch catalogServicesWatch scheduler runs into timeouts and the application is not responding during this time window (Healthaggreagtor is also not responding). It seems like the executing of this scheduler freezes the complete web server itself when the cluster is not working as expected.

Is it possible to deactivate this scheduler without disabling the complete discovery functionality?

We also would like to deactivate the complete consul health check itself. 
Currently, we removed the health check manually from the Healthcheck aggregator, but this looks a bit "sloppy".

**Application consul using details**
- Consul Service discovery is used to connect to a Hazelcast cluster
- Consul KV store is used during startup and runtime

**Comment by spencergibb** [comment]
You can set `spring.cloud.consul.discovery.catalogServicesWatch.enabled=false` to disable the watch and `management.health.consul.enabled=false`.
