### ISSUE TITLE
@EnableConsulUi doesn't work 

### ISSUE THREAD

**Issue by jmirc** [spring-cloud/spring-cloud-consul#38]
If I start consul without the ui parameter ```-ui-dir```, I got a 404 error

Without ```-ui-dir```

```
./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul
```

See the screenshot

![screen shot 2015-06-01 at 22 04 35](https://cloud.githubusercontent.com/assets/50304/7927150/4788e696-08aa-11e5-87dc-2e9fcc2ceffd.png)

With ```-ui-dir``` it works.
```
./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul -ui-dir `dirname $0`/ui
```

**Comment by spencergibb** [comment]
Apparently enabling the ui enables an internal ui api that isn't public :-(  This feature might just have to go away.

**Comment by spencergibb** [comment]
@jmirc So instead of ditching the feature all together, we decided to proxy the UI as well as the API through zuul, so you are now _required_ to run the ui in the agent to use `@EnableConsulUi`.

**Comment by jmirc** [comment]
good decision.
