### ISSUE TITLE
Spring boot 2 actuator (BUILD-SNAPSHOT) class EndpointHandlerMapping has been removed

### ISSUE THREAD

**Issue by thaingo** [spring-cloud/spring-cloud-consul#381]
The class **EndpointHandlerMapping** has been removed from the Spring boot actuator 2.0.0.BUILD-SNAPSHOT. What the alternative is?

Thanks.

**Comment by spencergibb** [comment]
Can you explain what that has to do with Spring Cloud Consul?

**Comment by thaingo** [comment]
@spencergibb so sorry, my bad. I was supposed to open the issue in the Spring Boot. Shall I close it or can you help move it to the Spring Boot?

**Comment by spencergibb** [comment]
Please open it in Spring Boot
