### ISSUE TITLE
Make LifecycleRegistrationResolver public

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-consul#385]
In previous release trains, we were able to override the `ConsulDiscoveryClient` by marking our `ConsulDiscoveryClient` as `@Primary`.

We need this as we use the `ConsulDiscoveryClient` in our `MultiZonesConsulDiscoveryClient` that returns the instances of a services from multiple DCs and also adds letancy information based on network coordinates that comes from Consul.

Now, we are no longer able to override it and we don't have any way to define only our own `ConsulDiscoveryClient` as the composite will call the `ConsulDiscoveryClient` that comes from `org.springframework.cloud.consul.discovery.ConsulDiscoveryClient`.

We tried to define our own one by inheriting from `ConsulDiscoveryClient` but this is not possible without copying the `LifecycleRegistrationResolver` implementation as it is an inner class.

So we ended up copying the `LifecycleRegistrationResolver` and inheriting from `ConsulDiscoveryClient` so this way we have only our own implemetnation of `ConsulDiscoveryClient` and `SimpleDiscoveryClient`.

Please either enable a way to disable the composite discovery or atleast reuse the `LifecycleRegistrationResolver`

**Comment by spencergibb** [comment]
A few things composite service discovery is in spring-cloud-commons, so it can't happen in this repo. What should happen there is to allow ordering using the spring `Ordered` mechanism. I don't see why `LifecycleRegistrationResolver` couldn't be public, it is gone in master. Also, any reason to not contribute your `MultiZonesConsulDiscoveryClient`?

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-commons/issues/304

**Comment by spencergibb** [comment]
Closed via 44e8048c8ff8b354273bcc5bc53df9d79adf6437

**Comment by ezraroi** [comment]
@spencergibb How can we contribute our `MultiZonesConsulDiscoveryClient'? Should i open another issue?

Thanks for exposing the `LifecycleRegistrationResolver` class, we also fixed it to use `ConsulRegistration` instead of the deprecated `ConsulLifecycle` bean. Do you want me also to contribute it?

**Comment by spencergibb** [comment]
Just a PR.

The use of `ConsulRegistration` is in master already.
