### ISSUE TITLE
Deregistration with GET method not allowed

### ISSUE THREAD

**Issue by mimi06500** [spring-cloud/spring-cloud-consul#387]
Bug report

The deregistration of Consul services is calling a Get method on the Consul Agent API (AgentConsulClient:249 - consul-api 1.2.2) :

`@Override
	public Response<Void> agentServiceDeregister(String serviceId) {
		RawResponse rawResponse = rawClient.makeGetRequest("/v1/agent/service/deregister/" + serviceId);
`
The Consul agent returns a HTTP 405 because a PUT method is expected by Consul see [here](https://www.consul.io/api/agent/service.html).

Is there any fix available for this issue ?
Should we upgrade to Spring Cloud Consul 1.3.1 even if it is not tagged as "current" ?

Thank you for your advice !

**The setup to reproduce this issue :**

Tomcat 8.5
JDK 1.8.0_161
Spring Cloud Consul version : org.springframework.cloud:spring-cloud-starter-consul-all:jar:1.2.1.RELEASE
Dependency on consul-api 1.2.2
Consul v1.0.0

**Comment by spencergibb** [comment]
1.3.1 is the latest.

**Comment by rachitkul** [comment]
I am also facing this issue. Consul version 1.0.2

**Comment by spencergibb** [comment]
Are you using the latest version of spring cloud consul?

**Comment by rachitkul** [comment]
I was using spring cloud consul version 1.2.1. After updating it to verison 1.3.1 I am no longer encountering this error.

**Comment by hars1130** [comment]
I am also facing the issue i stop the discovery client springboot application.
spring cloud version: Dalston.SR1
consul: 1.3.0

**Comment by spencergibb** [comment]
That version is very old. Please try the latest Edgware.SR5
