### ISSUE TITLE
multiple agent

### ISSUE THREAD

**Issue by levin950825** [spring-cloud/spring-cloud-consul#389]
Does spring-cloud-consul consider supporting multiple agent configurations
``` java
spring:
  cloud:
    consul:
      host: ip1,ip2
      port: 8500
```

**Comment by spencergibb** [comment]
No, it does not. The recommended way is to connect to the local agent only

**Comment by xiaoxing598** [comment]
I think it should support multiple addresses in order to achieve failover. With a local agent, the same project uses a different profile, which does not conform to the configuration central management policy.

**Comment by xiaoxing598** [comment]
This means that a Consul proxy service must be installed on each machine, and all applications running on this machine are connected to this proxy service.

In order to avoid the trouble of centrally managing configuration files, I expect to be able to automatically get the local Consul service.
```
spring.cloud.consul.host = 10.x.x.x

# When the HOST parameter is not configured
spring.cloud.consul.host = 127.0.0.1
```
