### ISSUE TITLE
Add Header support for service Checks.

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-cloud/spring-cloud-consul#391]
Add Header map support. This enables header based authentication from the consul server to the target service among many other customizations.

[Consul service check feature support reference.](https://github.com/hashicorp/consul/blob/48f3dd5642374d079f5a64359023fb8318eb81cc/api/agent.go#L82)

**Comment by spencergibb** [comment]
We tend to like separate issues rather than combined. I think 2) is already done.

**Comment by PedroAlvarado** [comment]
Sounds good, allow me to update the ticket.

**Comment by johnBgood** [comment]
Hi,

I quickly looked at this issue and it looks like the [consul client (ECWID)](https://github.com/Ecwid/consul-api/blob/master/src/main/java/com/ecwid/consul/v1/agent/model/NewService.java) does not support 'headers' attribute yet.

**Comment by e1337** [comment]
It does now.

https://github.com/Ecwid/consul-api/issues/162

**Comment by HarryHarcourt** [comment]
Ladies / Gents
We could really do with this added to the capability of Spring-Cloud (just to be sure we would like to enable basic authentication for Service Health Checks which we think will be addressed by passing the login / password through the HTTP Headers during registration).
When do you think this capability might be enabled?
Best

**Comment by spencergibb** [comment]
It's not scheduled. PRs welcome

**Comment by HarryHarcourt** [comment]
Thanks Spencer - I will see what we can do within our Team

**Comment by HarryHarcourt** [comment]
Hi Spencer
To provide us with more guidance (for my ask of them) what do you think the success criteria should be, thus what should we "test"?
Our goal is to enable Basic Auth for the Health Checks, thus setting the user and password, whether locally within the application.yml file or from Vault (our goal), 
These would then be submitted through the header as base64 encoded values to consul: 
example:  "Authorization: <type> <credentials>".  Where type is basic and credentials are the base64 encoded values.
If no login and password is configured or login or password then the Header submission is ignored.
Does this sound sufficient?
Best

**Comment by spencergibb** [comment]
I think a basic string,string map healthCheckHeaders in `ConsulDiscoveryProperties` would be sufficient.
