### ISSUE TITLE
com.ecwid.consul.v1.OperationException: OperationException(statusCode=500, statusMessage='Internal Server Error', statusContent='rpc error: EOF' 

### ISSUE THREAD

**Issue by kissdragon-z** [spring-cloud/spring-cloud-consul#394]
Lately， I found one exception , detail as:
Error watching Consul CatalogServices com.ecwid.consul.v1.OperationException: OperationException(statusCode=500, statusMessage='Internal Server Error', statusContent='rpc error: EOF') at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogServices(CatalogConsulClient.java:122) at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogServices(CatalogConsulClient.java:108) at com.ecwid.consul.v1.ConsulClient.getCatalogServices(ConsulClient.java:320) at org.springframework.cloud.consul.discovery.ConsulCatalogWatch.catalogServicesWatch(ConsulCatalogWatch.java:65) at org.springframework.cloud.consul.discovery.ConsulCatalogWatch$$FastClassBySpringCGLIB$$512778c2.invoke() at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) at 

where i saw the resource , detail as:
@Scheduled(
        fixedDelayString = "${spring.cloud.consul.discovery.catalogServicesWatchDelay:30000}"
    )
    public void catalogServicesWatch() {
        try {
            long index = -1L;
            if(this.catalogServicesIndex.get() != null) {
                index = ((BigInteger)this.catalogServicesIndex.get()).longValue();
            }

            Response<Map<String, List<String>>> response = this.consul.getCatalogServices(new QueryParams((long)this.properties.getCatalogServicesWatchTimeout(), index));
            Long consulIndex = response.getConsulIndex();
            if(consulIndex != null) {
                this.catalogServicesIndex.set(BigInteger.valueOf(consulIndex.longValue()));
            }

            log.trace("Received services update from consul: {}, index: {}", response.getValue(), consulIndex);
            this.publisher.publishEvent(new HeartbeatEvent(this, consulIndex));
        } catch (Exception var5) {
            log.error("Error watching Consul CatalogServices", var5);
        }

    }

the Schedule does query something from consul
from the exception, i thew the consul something wrong ocuured . but i want to know 
1. the purpose of the Schedule
2. if there is any possiblye to stop the Schedule

thanks

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

The purpose is to publish a heartbeat that other spring cloud projects can listen to and react when there are new services (such as zuul).

To disable set `spring.cloud.consul.discovery.catalogServicesWatch.enabled=false`.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
