### ISSUE TITLE
Add support for filtering services discovered by "ConsulDiscoveryClient#getAllInstances" and "ConsulDiscoveryClient#getServices"

### ISSUE THREAD

**Issue by lchayoun** [spring-cloud/spring-cloud-consul#396]
My use case for it is filtering services by an API Gateway.
The gateway is auto discovering all services registered in consul, filtering from the list only services with "Edge" tag in order to allow the services to decide on exposing routes through the API Gateway

**Comment by spencergibb** [comment]
Why can't this be handled by a `ServerListFilter` from ribbon?

**Comment by lchayoun** [comment]
@spencergibb `ServerListFilter` is filtering servers from the list for already created route, this filter will allow filtering services and not creating the routes at all.

**Comment by spencergibb** [comment]
consul doesn't know anything about routes. Why couldn't you create a ServerListFilter that is only used in Zuul? I don't see the need for another filter.

**Comment by spencergibb** [comment]
Sorry, I misunderstood. I still don't think it's a consul specific problem. If anything it's a [DiscoveryClientRouteLocator](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/discovery/DiscoveryClientRouteLocator.java) problem, or enhancement.

**Comment by lchayoun** [comment]
I agree, enhancing the `DiscoveryClientRouteLocator` would be better, the only issue with it is that the `DiscoveryClient` doesn't have an interface for returning the services with the metadata since it is not consul specific.
As I see it the only way to do it using the DiscoveryClientRouteLocator is by adding some logic that will add all the "excluded" services to the ignore list before running the `DiscoveryClientRouteLocator#locateRoutes`

**Comment by spencergibb** [comment]
It does. `ServiceInstance.getMetadata()`. I opened https://github.com/spring-cloud/spring-cloud-netflix/issues/2747
