### ISSUE TITLE
agentServiceDeregister not pass token

### ISSUE THREAD

**Issue by gongmingbin** [spring-cloud/spring-cloud-consul#402]
I use consul with ACL. I pass discovery.acl-token and register success. but when server shutdown,I found spring-cloud-consul deregister  use 		
`
		client.agentServiceDeregister(reg.getInstanceId());
`
install of 
`
  agentServiceDeregister(String serviceId, String token) ;
`

**Comment by spencergibb** [comment]
Fixed in #401
