### ISSUE TITLE
Intellij IDEA do not deregister the consul service

### ISSUE THREAD

**Issue by Xiaobaxi** [spring-cloud/spring-cloud-consul#407]
1、I choose the spring boot verison 1.5.10 and add the web、autuator and consul discovery dependencies on start.spring.io  from the pom.xml we will see the spring cloud version is Edgware.SR3
2、i start the consul for the version 1.0.6
3、set the application.properties:
`
spring.application.name=consul-test
server.context-path=/consul-test
server.port=8888
spring.cloud.consul.host=my-local-ip
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.preferIpAddress=true
spring.cloud.consul.discovery.ip-address=my-local-ip
spring.cloud.consul.discovery.health-check-path=${server.context-path}/health
spring.cloud.consul.discovery.health-check-interval=10s
`
4、start the application in IEDA(version 2017.1.5)  the spring cloud consul register the service to the consul
5、stop the application in IEDA(version 2017.1.5)  the consul service does not deregister

BUT：
after I execute maven install use jar -jar to start the application in the command line,and use ctrl-c to stop the application. the consul service register and deregister is correct

**Comment by spencergibb** [comment]
I don't think this has anything to do with spring cloud consul specifically. I've done what you describe many times and the functionality is independent of IDE. It must be something specific to your environment

**Comment by Xiaobaxi** [comment]
thank u for ur reply. I also doubt whether it is a problem with my idea environment.

**Comment by lcb1208** [comment]
I also meet this problem ...
