### ISSUE TITLE
Cannot override ServerListFilter for ConsulRibbonClientConfiguration 

### ISSUE THREAD

**Issue by mrkeuz** [spring-cloud/spring-cloud-consul#411]
I use consul for service discovery with 'feign' client

I've tried to override default HealthServiceServerListFilter that came from ConsulRibbonClientConfiguration but cannot.

i've tried to add annotaions like:
```
@RibbonClients(defaultConfiguration = MySrervieRibbonConfig.class)
or
@RibbonClient(name = "my-service", configuration = MySrervieRibbonConfig.class)
```
with class like:
```
public class MySrervieRibbonConfig {
    @Bean
    public ServerListFilter<Server> ribbonServerListFilter() {
        return new MyCustomServerListFilter();
    }
}
```

But no success in both case. 
I will try to figure out that this is bug or maybe i doing something wrong with configuration.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
