### ISSUE TITLE
Is there any way to configure delay of service registration?  [Enhancement]

### ISSUE THREAD

**Issue by rvit34** [spring-cloud/spring-cloud-consul#414]
I've just faced with a problem when I need to set some delay before service is registered at Consul or tell consul to make retries if first health check is failed. Unfortunately I've not found any similar option at `ConsulDiscoveryProperties`.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
