### ISSUE TITLE
Config auto refresh not working with springboot 2.0.1.RELEASE and spring-cloud-consul 2.0.0.RC1

### ISSUE THREAD

**Issue by ymmihw** [spring-cloud/spring-cloud-consul#417]
I build a [consul client with spring-cloud-consul 2.0.0.RC1](https://github.com/ymmihw/spring-cloud-consul). when I update key/value (config/myApp/my/prop) in the consul, Application configuration context is not refreshing. but it works with boot 1.5.10.RELEASE & spring-cloud-consul 1.3.3.RELEASE .

is there anything wrong with my client?  thank you

**Comment by spencergibb** [comment]
No, seems like an issue. Duplicates #399
