### ISSUE TITLE
Binding to target ConsulProperties(host=localhost, port=8500, enabled=true) failed:

### ISSUE THREAD

**Issue by LincolnLu8** [spring-cloud/spring-cloud-consul#423]
# my dependencies configration:
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-consul-discovery</artifactId>
	<version>1.3.3.RELEASE</version>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-consul-core</artifactId>
	<version>1.3.2.RELEASE</version>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-actuator</artifactId>
</dependency>

# and my issue：

Binding to target ConsulProperties(host=localhost, port=8500, enabled=true) failed:
    Property: spring.cloud.consul.host
    Value: null
    Reason: cannot be null

is there something wrong with my config?
and how can I do to solve this problem

thanks

**Comment by spencergibb** [comment]
You need to not mix versions. Please try with 1.3.5.RELEASE.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
