### ISSUE TITLE
Will ribbon automatically update its server list when we using consul?

### ISSUE THREAD

**Issue by laohubuchiyu** [spring-cloud/spring-cloud-consul#426]
Hi,
   when one node of server list is down, how fast could BaseLoadBalancer refresh the UpServerList. I just find that PollingServerListUpdater will do this job every 30 seconds, is there any other strategy？

**Comment by spencergibb** [comment]
yes see https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulCatalogWatch.java
