### ISSUE TITLE
Only one consul node restart ,services not auto register

### ISSUE THREAD

**Issue by lcb1208** [spring-cloud/spring-cloud-consul#429]
Only one consul node ,If it down ,register services not down ,how ensure services auto register when consul node restart

**Comment by kevin-tan** [comment]
This issue is most likely related to this: https://github.com/spring-cloud/spring-cloud-consul/issues/419

**Comment by rotilho** [comment]
@lcb1208 did you manage to accomplish that?

I have similar issue

**Comment by spencergibb** [comment]
Duplicate of #197
