### ISSUE TITLE
Hope to support empty string values

### ISSUE THREAD

**Issue by takeseem** [spring-cloud/spring-cloud-consul#430]
1. create a key in config/application/mykey, value is empty string.
2. when i use in spring ${mykey}, it is NULL.

- consul GET /v1/kv/config/application/?recurse
```
{
"LockIndex": 0,
"Key": "config/application/mykey",
"Flags": 0,
"Value": null,
"CreateIndex": 1265,
"ModifyIndex": 17278
}
```
- I think that  the consul configured a key then the value can not be null, because it is exist in the consul
- If i need a NULL, I will remove the key in consul.
- I hope we can convert the NULL to "", if the key in consul.

- temp fix: 
```
mykey=${mykey.default:}
```

**Comment by spencergibb** [comment]
I'm not sure about this. How would we differentiate.

**Comment by takeseem** [comment]
I think if i config a key in consul, the value of the key is must not be null.
because of the key is exist.

if the key is not exist in consul, then the value is null.
