### ISSUE TITLE
Customising wait time for consul property source index as 0

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-consul#432]
In ConfigWatch, For consul property sources which are not present in kv store, it waits for some amount of time(55 sec default) on that file as seconds to wait (or block) for watch query which is not required and add some latency. We might want to add a check if do not have property source present on consul we should not wait for such sources.

```
Response<List<GetValue>> response = this.consul.getKVValues(context, aclToken,
							new QueryParams(this.properties.getWatch().getWaitTime(),
									currentIndex));
```

Thoughts? we have customised this behaviour. if you find this valuable then I can provide changes for review.

**Comment by JagmohanSharma** [comment]
Actually sometime contextIndex might contain some of the values for which we do not have any property source present in consul. So in ConfigWatch , for such context we get 0 value for currentIndex.
```
Long currentIndex = this.consulIndexes.get(context);
```
and then we are trying to get kvValues for such index files which even does not exist.
```
Response<List<GetValue>> response = this.consul.getKVValues(context, aclToken,
							new QueryParams(this.properties.getWatch().getWaitTime(),
									currentIndex));
```
This adds some latency in terms of wait time configured for this consul call. We might want to customise this wait time for such property source which does not present in consul kv store but they are being configured in consulIndexes.

**Comment by spencergibb** [comment]
So you want a wait time per context?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
