### ISSUE TITLE
Ability to disable Consul discovery per Ribbon client

### ISSUE THREAD

**Issue by Delorien84** [spring-cloud/spring-cloud-consul#434]
Hi,
 It would be great, if there will be some simple configuration way, how to disable Consul for specific Ribbon client.

Let have situation, where I have two services `foo` and `bar`. For service `bar`  I need to set [`listOfServers` manually](https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.0.RC2/single/spring-cloud-netflix.html#spring-cloud-ribbon-without-eureka) (eg. testing, service `bar` is not in consul yet ...).

Currently there is option to disable consul for ribbon completely by setting `spring.cloud.consul.ribbon.enabled=false` property. But then I have to setup both services manually.

My workaround for this is to create following configuration:
```
bar.ribbon.listOfServers: localhost:8080


@Configuration
@RibbonClients({
        @RibbonClient(name = "bar", configuration = LocalRibbonClientConfiguration.class)
})
public class RibbonConfiguration {
}

public class LocalRibbonClientConfiguration {

    @Autowired
    private IClientConfig config;

    public IClientConfig getConfig() {
        return config;
    }

    @Bean
    @ConditionalOnExpression("'${${ribbon.client.name}.ribbon.listOfServers:null}' != 'null'")
    public ServerList<Server> ribbonServerList() {
        ConfigurationBasedServerList res = new ConfigurationBasedServerList();
        res.initWithNiwsConfig(config);
        return res;
    }
}
```

It would be nice, if there is configuration option like `spring.cloud.consul.ribbon.<service_name>.enabled` or similar to simple turn off Consul for specific Ribbon client.

**Comment by spencergibb** [comment]
```
bar:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: example.com,google.com
```
