### ISSUE TITLE
ConsulCatalogWatch does not pass acl token parameter

### ISSUE THREAD

**Issue by wubins** [spring-cloud/spring-cloud-consul#440]
I don't know why  the method catalogServicesWatch of ConsulCatalogWatch access consul server without acl token : 
```
 Response<Map<String, List<String>>> response = consul
					.getCatalogServices(new QueryParams(properties
							.getCatalogServicesWatchTimeout(), index));
```
then it call the CatalogConsulClient getCatelogServices method , and the acl token parameter is null,
if consul server need acl token  , the will have no permission

**Comment by spencergibb** [comment]
PRs welcome
