### ISSUE TITLE
Wrong IP address registered within Kubernetes?

### ISSUE THREAD

**Issue by somejavadev** [spring-cloud/spring-cloud-consul#441]
Question

I would like to use spring cloud within a kubernetes environment. Currently my Consul cluster is also running in kubernetes. When I view the discovered services of my spring boot app in the Consul UI some of the health checks fails for services. After further investigation the IP address registered for the service does not match that of the pod they are deployed in. I had a look at the spring cloud configs: prefer-agent-address and prefer-ip-address and tried playing with them with no luck. It doesn't seem like the correct address is being updated when the pod gets deleted and re-registered. What would be the correct configuration for running spring cloud consul within a kubernetes environment to allow the health checks to pass, how would I get the addresses in sync? Is it possible to have the pods generated name used as DNS instead of making use of IP addresses?

Consul UI:

![consul](https://user-images.githubusercontent.com/6507120/43038104-24fd1006-8d14-11e8-926a-00df36ef82b5.png)

Kubernetes POD:

![selection_009](https://user-images.githubusercontent.com/6507120/43038114-5a04b06a-8d14-11e8-87d5-806e6b0f8bd0.jpg)

Bug report

Consul version: 1.2.0
Spring boot / cloud consul version: 2.0.3.RELEASE
Kubernetes version: 1.11.0

**Comment by somejavadev** [comment]
Just additionally what I have noticed is that it might be older instances of that service which was not properly de-registered from consul when the pod was killed and started again. I currently only have one instance of this audit service running in a pod but multiple versions seem to be still registered
![selection_010](https://user-images.githubusercontent.com/6507120/43473228-de68c3c2-94ef-11e8-876b-90d675b62df8.jpg)
The extra ones listed are the ones receiving the failed health checks.

**Comment by spencergibb** [comment]
Spring Cloud tries to guess what to register as. Outside of that, you need to provide a routable hostname or IP address. You can also give our guessing algorithm some clues, see http://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#ignore-network-interfaces

**Comment by somejavadev** [comment]
Excellent thanks, additionally I have set the `health-check-critical-timeout` property in my spring config to allow the ghost services to unregister them self from consul should the IP address of the container change and a service still be registered to an old IP address.

**Comment by oliversalmon** [comment]
> Excellent thanks, additionally I have set the `health-check-critical-timeout` property in my spring config to allow the ghost services to unregister them self from consul should the IP address of the container change and a service still be registered to an old IP address.

Hi,

I have the same problem, please could you let me know what you did, did you use spring.cloud.inetutils.ignoredInterfaces and if so what values did you use?

Thanks in advance for your help

**Comment by somejavadev** [comment]
@oliversalmon, see my spring application-prod.yml bellow, the settings defined resolved any issues we had with these ghost services. 

```yaml
spring:
    cloud:
        consul:
            discovery:
               prefer-ip-address: true
               health-check-critical-timeout: "1m"
            host: localhost
            port: 8500
```    
One thing to note is that you will have to remove the registered services manually if they where registered before adding these settings. You can do that with a tool such as https://github.com/jippi/hashi-ui or the REST calls if you know them.
