### ISSUE TITLE
Ability to define several prefix to fetch key/values from different consul nodes

### ISSUE THREAD

**Issue by symphonydarlys** [spring-cloud/spring-cloud-consul#450]
Hi Team,

I have a question about your library allowing fetch consul key/values in a spring boot application. 

Normally We can define a prefix and an application name to define what is the consul node containing the values that we want to inject in the content config of spring. 

I have an interesting case where we want to set some key/values in different consul nodes [different paths], Is it possible to do that with your library?

Thanks in advance
Darlys

**Comment by spencergibb** [comment]
Not currently.

**Comment by colin-mullikin** [comment]
I also have a current requirement of reading configuration data from separate path prefixes (/config and /appData). Is there any chance this will be supported in the near future?
