### ISSUE TITLE
ConfigWatch is running only once instead of periodically

### ISSUE THREAD

**Issue by cambierr** [spring-cloud/spring-cloud-consul#457]
From what I can see in 
```java
    @Scheduled(fixedDelayString = "${spring.cloud.consul.config.watch.delay:1000}")
    public void watchConfigKeyValues() {
        ...
    }
```
The config watch runs only once (and it's what I observe when checking logs). Is this a choice ? What if I want it to run periodically so that I can change any config at any time ?

**Comment by Frances-zy** [comment]
hi  i meet the same question, please tell me why is not work !

**Comment by cambierr** [comment]
Hi @Frances-zy,

My understanding of `fixedDelayString` was wrong: It doesn't mean "run once after this delay" but "run, then way for this delay, then re-run, the re-wait, ...". Which is the expected behavior.
