### ISSUE TITLE
ConsulSendingHandler assumes payload for message is always a String, but that isn't normally the case

### ISSUE THREAD

**Issue by drobert-bfm** [spring-cloud/spring-cloud-consul#458]
In ConsulSendingHandler.handleMessageInternal, an assumption is made that the payload is of type Message<String> but this is not normally the case. When using spring-cloud-consul-bus, in fact, the default org.springframework.cloud.stream.binding.MessageConverterConfigurer$OutboundContentTypeConvertingInterceptor creates a Message<byte[]>, not a Message<String>, even when the actual content is textual (such as application/json), and this causes a ClassCastException when the ConsulSendingHandler blindly casts the payload to String.

This makes spring-cloud-consul-binder unusable at this time.

**Comment by ryanjbaxter** [comment]
Can you provide a sample or even a unit test that shows the issue?  Maybe you would be interested in submitting a PR?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by spencergibb** [comment]
@drobert-bfm the consul api expects a string. If it is a byte array, we'd need to encode/decode it.

**Comment by dirkmurphy** [comment]
Hello, we are trying to use spring cloud with consul as registration center and config center.
But we are stopped by this exception when integrate spring cloud consul bus. It seems like this issue.
I have check into the consul bus source code, a converter cast my customEvent object to byte[] and ConsulSendingHandler.handleMessageInternal() cast the payload(byte[]) to String. so it throw a Exception.

Wait for your kindly help. Thank you.

The exception info as below: 
java.lang.ClassCastException: [B cannot be cast to java.lang.String
	at org.springframework.cloud.consul.binder.ConsulSendingHandler.handleMessageInternal(ConsulSendingHandler.java:52) ~[spring-cloud-consul-binder-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:165) ~[spring-integration-core-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132) ~[spring-integration-core-5.0.4.RELEASE.jar:5.0.4.RELEASE]

**Comment by vova-uvarov** [comment]
> @drobert-bfm the consul api expects a string. If it is a byte array, we'd need to encode/decode it.

ok. in #468 I provided a simple example. it is not work with defautl config 
https://github.com/vova-uvarov/consul-bus-error

for send event i use this code
`eventPublisher.publishEvent(new CustomRemoteEvent("customValue", this, "test-event-sender:**", "oauth-server:**"));`

**Comment by dirkmurphy** [comment]
@vova-uvarov  Thank your for reply. Have you solved this problem? Can you show me a detailed example?

**Comment by Sam-Kruglov** [comment]
Also blocked by this 2.1.2.RELEASE

**Comment by dirkmurphy** [comment]
Hi team.
Is there any update? Does [spring cloud consul bus](https://github.com/spring-cloud/spring-cloud-consul/tree/master/spring-cloud-starter-consul-bus) available now?

**Comment by plmaheu** [comment]
Got this issue in two different ways on the same message. First one was what my RemoteApplicationEventScan wasn't set properly.

Second is when send the AckRemoteApplicationEvent, it ends up as a byte[] payload.

**Comment by spencergibb** [comment]
as I stated before, the consul event api expects a string. What needs to happen is that if the payload is a `byte[]` encode it base64, set a header that notes it was base64 encoded, then, decode where needed.

PRs welcome.

**Comment by plmaheu** [comment]
@spencergibb I was about to ask a rather long question but I guess a PR would be simpler, we'll see if I got it right. What needs to be changed is ConsulSendingHandler, right?
