### ISSUE TITLE
spring boot service not deregister from consul 

### ISSUE THREAD

**Issue by ericxchang** [spring-cloud/spring-cloud-consul#459]
When spring boot application not shutdown gracefully, such as kill -9 or out of memory etc. the service does not deregister from consul. Is there way to resolve this? I have spring boot v1.5.9.
Here is my spring consul configuration:
spring:
  cloud:
    consul:
      host: localhost
      port: 80
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        healthCheckPath: /${app.name}/health
        healthCheckInterval: 15s

consul has parameter DeregisterCriticalServiceAfter, is there anything equivalent in Spring Boot?

Thanks for helping!

**Comment by spencergibb** [comment]
set `spring.cloud.consul.discovery.healthCheckCriticalTimeout`
