### ISSUE TITLE
Service fail health check in consul when upgrade to spring boot 2.0

### ISSUE THREAD

**Issue by quangnvn** [spring-cloud/spring-cloud-consul#461]
I upgrade my project to spring-boot 2.0 along with consul, and already set for application.yml config file but my service still fail health-check in consul:

management.endpoints.web.exposure.include=*
spring.cloud.consul.discovery.health-check-path=/application/health

Could you guys show ways to resolve it? Thanks so much!

**Comment by spencergibb** [comment]
have you tried to use the default path of `/actuator/health`?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
