### ISSUE TITLE
After upgrade to Spring Boot v2.1.0 Consul auto registration not working

### ISSUE THREAD

**Issue by devpreview** [spring-cloud/spring-cloud-consul#464]
After upgrade to Spring Boot v2.1.0 Consul auto registration not working.

Minimal step repo for Spring Boot v2.0.6
https://github.com/devpreview/test-consul/tree/spring-v2.0.6

It works correctly.

> 2018-11-07 20:55:40.179  INFO 17032 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
> 2018-11-07 20:55:40.195  INFO 17032 --- [           main] o.s.c.c.s.ConsulServiceRegistry          : Registering service with consul: NewService{id='test-6f583ab5b29c271d1d1cd52a34e86c58', name='test', tags=[secure=false], address='sabo-probook.lan', port=8080, enableTagOverride=null, check=Check{script='null', interval='10s', ttl='null', http='http://sabo-probook.lan:8080/actuator/health', tcp='null', timeout='null', deregisterCriticalServiceAfter='null', tlsSkipVerify=null, status='null'}, checks=null}
> 2018-11-07 20:55:40.232  INFO 17032 --- [           main] com.test.consul.Application              : Started Application in 4.385 seconds (JVM running for 5.636)

Minimal step repo for Spring Boot v2.1.0
https://github.com/devpreview/test-consul/tree/spring-v2.1.0

Consul auto registration not working.

> 2018-11-07 20:58:06.135  INFO 17631 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
> 2018-11-07 20:58:06.136  INFO 17631 --- [           main] com.test.consul.Application              : Started Application in 2.301 seconds (JVM running for 2.91)

- Spring Boot version: 2.1.0
- Spring Cloud version: Finchley.SR2
- Java version: OpenJDK 9.0.4
- OS: Linux

**Comment by devpreview** [comment]
As hotfix you may starting registration manually:

```
@Configuration
public class ConsulConfiguration {
    @Bean
    public ApplicationListener<ApplicationReadyEvent> consulServiceRegistryRegister(ConsulAutoServiceRegistration consulAutoServiceRegistration) {
        return event -> {
            consulAutoServiceRegistration.setPort(8080);
            consulAutoServiceRegistration.start();
        };
    }
}
```

**Comment by spencergibb** [comment]
Finchley is not compatible with boot 2.1.x

**Comment by jdkhome** [comment]
> As hotfix you may starting registration manually:
> 
> ```
> @Configuration
> public class ConsulConfiguration {
>     @Bean
>     public ApplicationListener<ApplicationReadyEvent> consulServiceRegistryRegister(ConsulAutoServiceRegistration consulAutoServiceRegistration) {
>         return event -> {
>             consulAutoServiceRegistration.setPort(8080);
>             consulAutoServiceRegistration.start();
>         };
>     }
> }
> ```

thanks！

**Comment by jdkhome** [comment]
> As hotfix you may starting registration manually:
> 
> ```
> @Configuration
> public class ConsulConfiguration {
>     @Bean
>     public ApplicationListener<ApplicationReadyEvent> consulServiceRegistryRegister(ConsulAutoServiceRegistration consulAutoServiceRegistration) {
>         return event -> {
>             consulAutoServiceRegistration.setPort(8080);
>             consulAutoServiceRegistration.start();
>         };
>     }
> }
> ```

thanks! you can comment out ```consulAutoServiceRegistration.setPort(8080);```

**Comment by devpreview** [comment]
@jdkhome If you not set port on ConsulAutoServiceRegistration you will get an exception:

```
java.lang.IllegalArgumentException: service.port has not been set
	at org.springframework.util.Assert.notNull(Assert.java:198)
	at org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistration.getRegistration(ConsulAutoServiceRegistration.java:56)
```

See: https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/serviceregistry/ConsulAutoServiceRegistration.java#L51

ConsulAutoServiceRegistration.setPort should be equal your server.port property (or your service port).

Your may get port from ServerProperties:

```
@Bean
    public ApplicationListener<ApplicationReadyEvent> consulServiceRegistryRegister(
            ConsulAutoServiceRegistration consulAutoServiceRegistration,
            ServerProperties serverProperties
    ) {
        return event -> {
            consulAutoServiceRegistration.setPort(serverProperties.getPort());
            consulAutoServiceRegistration.start();
        };
    }
```

**Comment by spencergibb** [comment]
is this still a problem with Boot 2.1.1.RELEASE and Greenwich.RC1?

**Comment by devpreview** [comment]
Yes. With Boot 2.1.1.RELEASE and Greenwich.RC1 Consul auto registration does not work.

**Comment by spencergibb** [comment]
@devpreview I just created a minimal application from start.spring.io that auto registers just fine.

![image](https://user-images.githubusercontent.com/594085/49966640-96c58a00-feee-11e8-9760-a4ca137c7be9.png)

Also, your app, updated to boot 2.1.1.RELEASE and java 8 (since I don't have 9) auto registered just fine.

![image](https://user-images.githubusercontent.com/594085/49966855-41d64380-feef-11e8-856e-9c37ba77395b.png)

**Comment by devpreview** [comment]
@spencergibb Sorry. I did not test correctly.

With Boot 2.1.1.RELEASE and Greenwich.RC1 Consul auto registration is working.

**Comment by spencergibb** [comment]
Thanks for following up

**Comment by jdkhome** [comment]
> @spencergibb Sorry. I did not test correctly.
> 
> With Boot 2.1.1.RELEASE and Greenwich.RC1 Consul auto registration is working.

I upgraded to 2.1.1.RELEASE ,But if you don't use your code, auto registration is working.
I use jdk11
