### ISSUE TITLE
is there a full documentation of possible properties in spring.cloud.consul

### ISSUE THREAD

**Issue by Code2Life** [spring-cloud/spring-cloud-consul#469]
Official documents only contains some common configurations, but when going to production, we may need to configure some useful properties such as "healthCheckCriticalTimeout", "preferIpAddress", It would be very helpful to get a explicit documentation. btw, possible options for "instanceId" will help a lot, too.

**Comment by ryanjbaxter** [comment]
They should be there in the documentation.  Try looking up the canonical names, for example `health-check-critical-timeout`.

**Comment by ryanjbaxter** [comment]
Just to clarify you need to look in Appendix http://cloud.spring.io/spring-cloud-static/Finchley.SR2/multi/multi__appendix_compendium_of_configuration_properties.html
