### ISSUE TITLE
service not deregistering when leader node of consul cluster changes

### ISSUE THREAD

**Issue by Code2Life** [spring-cloud/spring-cloud-consul#473]
Hi, 
  I tested a special case with 3 nodes consul cluster and found something abnormal. To reproduce this:

1. normally start springboot application, service will register to the leader agent of consul nodes
2. after registering, kill leader agent, and consul cluster will elect a new leader
3. then shutdown application, service can not be deregistered
note that without step 2, application can deregister itself from leader agent

Is that a bug ? or maybe I misunderstand the mechanism ?

**Comment by Code2Life** [comment]
The problem is, after a while, I manually restart the previous consul leader agent, and previous service will remain in it (even if I've shut down the app) , it will lead to inconsistent data

**Comment by spencergibb** [comment]
Not sure this is a problem with spring cloud consul as it all has to do with consul directly. Seems you would have this problem regardless of the mechanism of registering.

**Comment by Code2Life** [comment]
thx a lot
