### ISSUE TITLE
spring-cloud-consul-discovery is not compatible with Spring Boot 2.1.1.RELEASE

### ISSUE THREAD

**Issue by fbutter** [spring-cloud/spring-cloud-consul#481]
# Expected Behavior:
After the startup of the Servlet or Reactive Webcontainer, the service is registered in consul.

# Actual Behavior:
After the startup of the Servlet or Reactive Webcontainer, the service is not registered in consul.

# Root Cause Analyses:
1.  The registration of the service in consul is performed by:
```org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration#bind```
2. The highlighted method should listen to the application event ```WebServerInitializedEvent```, emitted after the Netty, Tomcat or Jetty are started.
3. The listener is not executed since the registration of the listener fails. The registration fails, since spring-context from version 5.1 on started to check if the listener bean is annotated with ```@Component```, which is not the case for the listener. Rather, the bean is provided to the context using the Bean method ```org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration#consulRegistration```.

The changes leading to this issue has been made in [this ](https://github.com/spring-projects/spring-framework/commit/d72d376f035a22cd7128a337cfdcf22cf91badd6) commit. The task in which these changes have been implemented is [Avoid unnecessary synthesizable annotation processing (SPR-16933)](https://jira.spring.io/browse/SPR-16933).

**Comment by spencergibb** [comment]
What version of spring cloud are you using? Boot 2.1.x is only compatible with Greenwich.RELEASE, boot 2.0.x with Finchley.SR2

**Comment by fbutter** [comment]
The problem existed in master and Finchley.SR2, which was the latest version at the time of writing.
Its working greatly with the just released Greenwich.RELEASE, thank you.
