### ISSUE TITLE
the configuration of spring.cloud.consul.host does not work well

### ISSUE THREAD

**Issue by godpit** [spring-cloud/spring-cloud-consul#483]
spring.cloud.consul.host=192.168.97.132

error: com.ecwid.consul.transport.TransportException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500.

detail:

ConsulAutoConfiguration -> consulProperties
        @Bean
	@ConditionalOnMissingBean
	public ConsulProperties consulProperties() {
		return new ConsulProperties();
	}

go into the consulProperties method and return default host: localhost

environment：springboot 2.1.1, springcloud Finchley.SR2, java8

**Comment by spencergibb** [comment]
Finchley is not compatible with boot 2.1.x. please downgrade to boot 2.0.x or upgrade to Greenwich.RC1.

Those settings should go in bootstrap.properties.

**Comment by godpit** [comment]
it didn't work well , host is still localhost

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by godpit** [comment]
[testconsul.zip](https://github.com/spring-cloud/spring-cloud-consul/files/2735070/testconsul.zip)

This is a simple example.

**Comment by xyy277** [comment]
I had the same problem

**Comment by spencergibb** [comment]
`spring.cloud.consul.host=192.168.97.132` must be in bootstrap.yml
