### ISSUE TITLE
Collection properties are overwritten by elements

### ISSUE THREAD

**Issue by sophiaso** [spring-cloud/spring-cloud-consul#485]
**Question**

When using `spring-cloud-starter-consul-config` to load properties, the Collection properties are not loaded properly. It might be caused by some defects of `PropertySourceBootstrapConfiguration` and `PropertySourceLocator`,  as it only allows a single CompositePropertySource being created when loading from Locator, or I just had some misunderstanding.

**Bug report**

Spring Cloud version: 2.1.0.M2

Consul properties:
```
config/application/config.names[0] -> "application name 0"
config/application/config.names[1] -> "application name 1"
config/foo/config.names[0] -> "foo name 0"
```
bootstrap.properties:
```
spring.application.name=foo
```

Simplified domain class:
```
@ConfigurationProperties(prefix = "config")
public class TestProperties {
    private List<String> names;  // Getter/Setter omitted
}
```

After started, the TestProperties#getNames() returned `[foo name 0, application name 1]`, shouldn't `[foo name 0]` be expected?

**Enhancement**
Collection properties field should overwrite the whole list instead of by elements.

**Comment by spencergibb** [comment]
I believe this is how spring boot works with property collections across property sources. I don't think there is anything we can do.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
