### ISSUE TITLE
support for enable_tag_override?

### ISSUE THREAD

**Issue by geercode** [spring-cloud/spring-cloud-consul#486]
I am operating a cluster of 3 consul server with a signle soft loadbalance address in which my springcloud apps registered.And when I changed the tags of my app, the app registered in another consul server.But the old tags is still in the original consul server.I expect springcloud consul could raise some supports for consul cluster with multi server nodes.What I suppose is the arch design between consul and eureka is quite different,but it's quite similar between consul and zookeeper.Pleased to get some guides.
Consul docs raise we could register a service with enable_tag_override giving a true value, so we can override the tags on the catalog, is that possible or a good way to make things right?

**Comment by spencergibb** [comment]
I'm afraid I don't understand what you are saying. We expect apps to register via agents, not directly to a cluster.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
