### ISSUE TITLE
Why DefaultInstanceId does not include hostname?

### ISSUE THREAD

**Issue by tianzhipeng-git** [spring-cloud/spring-cloud-consul#487]
https://github.com/spring-cloud/spring-cloud-consul/blob/38928ae253e7d6760fdccd14df856ed3dd6fd5b4/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/serviceregistry/ConsulAutoRegistration.java#L139

If user doesn't config the `instanceId`, it will fall back to this line to `getDefaultInstanceId()`; 
I wonder why includeHostname param is fixed to `false`? 
I have several instances running in different host and same port, same appName, they will share a same  `instanceId`.

Maybe there should be annother config option `instanceIdIncludeHostname`?

**Comment by spencergibb** [comment]
PRs welcome

**Comment by tianzhipeng-git** [comment]
Looks this PR. 
I add a property to control 'whether hostname is included into the default instance id when registering service'.
And I think instanceId won't be used in 'consul dns query', so it is no necessary to be dns compliant ?

**Comment by tianzhipeng-git** [comment]
Has been fixed in #570
