### ISSUE TITLE
how spring boot service register to consul cluster ,the confit host is only one ip

### ISSUE THREAD

**Issue by zjypp** [spring-cloud/spring-cloud-consul#488]
image
<img width="509" alt="image" src="https://user-images.githubusercontent.com/4704158/51599253-1e64d680-1f3a-11e9-95dc-d7e2ddbce20b.png">

this is my consul cluster

this is my spring boot configuration
server:
port: 8082
spring:
application:
name: consul-consumer
cloud:
consul:
host: 172.17.51.130 #this is one node of consul cluster
port: 8500
discovery:
tags: tag1
prefer-ip-address: true
ip-address: 60.205.176.124

when the spring boot register to the node1 of consul cluster,
but other nodes of consul cluster can not get the spring boot service info.

**Comment by spencergibb** [comment]
your not supposed to register directly do a server, but to an agent.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
