### ISSUE TITLE
After enable TTL, DeregisterCriticalServiceAfter not working .

### ISSUE THREAD

**Issue by NikoTung** [spring-cloud/spring-cloud-consul#490]
I used the following config to enable the TTL and DeregisterCriticalServiceAfter.

    spring:
       cloud:
         consul:
            host: localhost
            port: 8500
            discovery:
              instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
             health-check-critical-timeout: 3m
             heartbeat:
                enabled: true
                ttl-value: 30

When the application crash(exit without executing  the deregister ),the application will be in the critical status on consul ui and never be removed by consul.

I read the code and found that the other parameters are ignored when the ttl are enable.

    public static NewService.Check createCheck(Integer port, HeartbeatProperties ttlConfig,
										 ConsulDiscoveryProperties properties) {
		NewService.Check check = new NewService.Check();
		if (ttlConfig.isEnabled()) {
			check.setTtl(ttlConfig.getTtl());
			return check;
		}
		...
		return check;
	}
So my question is: Why the DeregisterCriticalServiceAfter is ignored. 

Since it is not conflict with the ttl. And I check the [consul.io ](https://www.consul.io/api/agent/service.html)document.

I alse test with the following curl script.The application:test-critical will be removed by consul automatically after 1 minute

    curl -X "PUT" "http://localhost:8500/v1/agent/service/register" \
     -H 'Content-Type: application/json' \
     -d $'{
        "ID": "test-critical-9e7433ac909aaf67ce256818b8e14e28",
        "Address": "10.0.11.179",
        "Name": "test-critical",
        "Check": {
          "TTL": "20s",
          "DeregisterCriticalServiceAfter": "1m"
        },
        "Port": 8080
      }'

**Comment by spencergibb** [comment]
I think that the `consul-api` library used to only support one `Check`, that is not the case anymore.

**Comment by NikoTung** [comment]
I know the `consul-api` library used to only support one `Check`. I think that the `DeregisterCriticalServiceAfter ` is kind of consul agent behavior, and no matter what kind  of `check`  we specified ,the `DeregisterCriticalServiceAfter` should not be ignored when it is config.

**Comment by scrat98** [comment]
Same issue. Could you please add DeregisterCriticalServiceAfter feature on TTL checks. Thanks!

**Comment by spencergibb** [comment]
@scrat98 PRs welcome
