### ISSUE TITLE
when i register 1 service to consul ,Why does consul display two instances

### ISSUE THREAD

**Issue by zrd1314** [spring-cloud/spring-cloud-consul#494]
when i register 1 service to consul ,Why does consul display two instances

**Comment by spencergibb** [comment]
I don't know, it generally doesn't do that and you provided no information to help. What exactly are you seeing in consul? What versions are you using? What is your configuration? If you'd like us to spend time helping, please spend some time describing in detail what is happing and how you got there.

**Comment by zrd1314** [comment]
sorry， my consul version is 1.4.1 ,springboot 2.1.2.RELEASE ,
I want to know why spring-cloud-consul-producer service  is on Consul  have two instances ,Is it normal ?，I'm testing spring bootadmin monitoring consul for service startup， but springboot admin does not monitor service startup ，so I raised this question
![appilcation](https://user-images.githubusercontent.com/31639666/52899656-79cb7100-3227-11e9-8550-068a386ab95d.png)

![consul](https://user-images.githubusercontent.com/31639666/52899698-e7779d00-3227-11e9-80e8-a1bc6ebc630f.png)

**Comment by spencergibb** [comment]
I wanted spring cloud version as well.

Screenshots aren't real helpful. But I can't see two instances of one service.

**Comment by zrd1314** [comment]
spring cloud:Finchley.SR2

**Comment by spencergibb** [comment]
Your screenshot doesn't show a problem to me

**Comment by zrd1314** [comment]
![consul1](https://user-images.githubusercontent.com/31639666/52901296-b9508800-323c-11e9-87ef-885735a97682.png)

**Comment by spencergibb** [comment]
Re-adding the same screenshot that I said doesn't show me a problem isn't helpful. Please describe why you think it is wrong.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
