### ISSUE TITLE
When some consul server crash in consul cluster,  the spring service couldn't switch the other consul automatically

### ISSUE THREAD

**Issue by Wadeqin** [spring-cloud/spring-cloud-consul#498]

**Comment by spencergibb** [comment]
They should be connected to a local agent not a server. This is recommended by hashicorp.

**Comment by Wadeqin** [comment]
I know what you mean, but if the local agent crash, our app  wouldn't connect to it, then the app wouldn't provide service. I don't know whether you understand me or not. When we use zk client, we can specify all zk server node ip. Any node crash, our apps still work well. Ok, currently we use a VIP and nginx to  reach our goal.

**Comment by spencergibb** [comment]
But zookeeper doesn't have the notion of agents.

**Comment by spencergibb** [comment]
We already have an open issue to reregister to an agent when it respawns

**Comment by Wadeqin** [comment]
I understand, i just using  the zk client round robin as a example. I think if the consul client could specify  multiple agent ip and it could switch to the right consul , it would be nice to our developer. Thank you for your reply.

**Comment by spencergibb** [comment]
How many consul agents do you run along side a service?

**Comment by Wadeqin** [comment]
Sorry, my expression could be ambiguous. I build an app, and using consul as registration center. Then i build consul cluster and app mutil-instance as load balance and fail-over. In the config file, i could noly specify one consul host ip as registration center address. When the consul service i write in the config file crash, my app would try to  connect to it again and again, then my app wouldn't provide service. I hope my app could connect to other normal consul automatically.

**Comment by spencergibb** [comment]
Your spring cloud apps should not communicate directly with the cluster. They should communicate with a consul agent running on local host. The agent should communicate with the cluster.

**Comment by Wadeqin** [comment]
I agree with you. But if the local consul agent crash, my app on the same machine should crash?

**Comment by spencergibb** [comment]
> We already have an open issue to reregister to an agent when it respawns

**Comment by 46557783** [comment]
@Wadeqin  i have the same problem as you ... if the given agent was unavilible ...

**Comment by Wadeqin** [comment]
@46557783 I am sorry for late response,it's busy to develop our bz, My solution is to create a VIP to connect u consul, then your local config configure the vip.
