### ISSUE TITLE
host can only set one consul host?

### ISSUE THREAD

**Issue by 46557783** [spring-cloud/spring-cloud-consul#513]
Question

please guidance me why the property spring.cloud.consul.host can only set one consul host? 
how spring-cloud-consul keep availability when the given host was unavailable in such way ?

**Comment by OlgaMaciaszek** [comment]
If you want to make it highly available, maybe you could make the `host` property point to a load-balancer? Would that solve your issue?

**Comment by spencergibb** [comment]
It should point to an agent not an actual consul cluster node

**Comment by SpinSi** [comment]
> It should point to an agent not an actual consul cluster node

How to point to an agent withs spring-cloud-consul ? Is this way really highly available?

**Comment by spencergibb** [comment]
Please stop commenting on multiple issues
