### ISSUE TITLE
ConsulServerList returns unhealthy nodes.

### ISSUE THREAD

**Issue by gitpg** [spring-cloud/spring-cloud-consul#52]
Its using the consul catalog service: client.getCatalogService(this.serviceId, QueryParams.DEFAULT);
.. but shouldnt it be using the consul health endpoint with the ?passing param to only get healthy nodes?

Thanks
/Andreas

**Comment by spencergibb** [comment]
I don't think so.  I think that should be the function of a filter.  The health of the nodes can change over time.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
