### ISSUE TITLE
ConsulProperties is not populated correctly

### ISSUE THREAD

**Issue by geoand** [spring-cloud/spring-cloud-consul#54]
Using the latest code from master (revision **dc3a367a4897d689a92250d4a5a3d039a6c27a66**), I tried to run the sample application following the instructions and with various settings for where Consul was installed

The problem I noticed is that Spring Cloud Consul only worked when Consul was accessible via `http://localhost:8500`.

What I noticed while debugging, was that *ConsulProperties* was being instantiated too early and there for totally ignored the properties set in *application.yml* (resulting in the use of default values).

You can verify this behaviour by running the sample application with the following modifications:

Add the following to *application.yml* 

```
spring:
  cloud:
    consul:
      host: someTest
      port: 9999
```

Change the main method in *SampleApplication.java* to:

```
public static void main(String[] args) {
        SpringApplication app = new SpringApplication(SampleApplication.class);
        app.addListeners(new ApplicationListener<ContextRefreshedEvent>() {
            @Override
            public void onApplicationEvent(ContextRefreshedEvent event) {
                final ConsulProperties consulProperties = event.getApplicationContext().getBean(ConsulProperties.class);
                log.info("ConsulProperties is {}", consulProperties);
                Assert.isTrue(consulProperties.getHost().equals("localhost"));
                Assert.isTrue(consulProperties.getPort() == 8500);
            }
        });
        app.run(args);
}
```

**Comment by spencergibb** [comment]
If you are using `spring-cloud-consul-config`, those values need to be in `bootstrap.yml`.  See [the caution in the docs](https://github.com/spring-cloud/spring-cloud-consul/blob/master/docs/src/main/asciidoc/spring-cloud-consul.adoc#registering-with-consul).  Also see #49 for another reason it didn't work.

**Comment by geoand** [comment]
Thank you very much for pointing me in the right direction!
