### ISSUE TITLE
How often does the Consul client go to the registry to get a list of available services?

### ISSUE THREAD

**Issue by xiaoxing598** [spring-cloud/spring-cloud-consul#552]
I want to know how long the Consul client in the application gets the service list. Can this interval be adjusted?

I see the `spring.cloud.consul.discovery.healthCheckInterval` parameter, is it?

**Comment by spencergibb** [comment]
The interval is determined by ribbon. Ask again later if you haven't found the right property

**Comment by xiaoxing598** [comment]
I want to know the interval between the consular client requesting the consular agent service.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
