### ISSUE TITLE
How can I do the consul cluster failover when using SpringCloud

### ISSUE THREAD

**Issue by Packy1014** [spring-cloud/spring-cloud-consul#553]
Hello guys, I've already create a cluster including 3 server agents as below
`192.168.179.111 (leader)`
`192.168.179.112 (follower)`
`192.168.179.113 (follower)`
And in SpringCloud yml file, there is a config named 

> spring.cloud.consul.host

But I can only give one single agent ip address to this config. If I have 5 micro services which are planed to be registered to `192.168.179.111`. If this agent is down, all registration acts will be failed when they start.
I'm so curious that is there any way to redirect my registration request automatically to one of the other two agents that are still alive if specified agent is unavailable, instead of exception thrown when I start SpringCloud?

Much thanks

**Comment by jasonmcintosh** [comment]
Normally you have a localhost agent that you connect to on Consul.  This local agent joins the cluster and is thus aware of all hosts in the cluster and you make API calls there.  Joining the cluster from a consul agent is documented: 
https://www.consul.io/docs/agent/basics.html

Specifically:
https://www.consul.io/docs/agent/options.html#retry-join

**Comment by Packy1014** [comment]
> Normally you have a localhost agent that you connect to on Consul. This local agent joins the cluster and is thus aware of all hosts in the cluster and you make API calls there. Joining the cluster from a consul agent is documented:
> https://www.consul.io/docs/agent/basics.html
> 
> Specifically:
> https://www.consul.io/docs/agent/options.html#retry-join

Got it. Thanks for your kindly reply

**Comment by SpinSi** [comment]
the config spring.cloud.consul.host  set only one host A (for example )
when this host A server is down, the java application can not connect  A
