### ISSUE TITLE
1 failed service causes the failure of the Consul Service discovery

### ISSUE THREAD

**Issue by terancet** [spring-cloud/spring-cloud-consul#557]
I have the following architecture:
1. Zuul API Gateway taken from `org.springframework.cloud:spring-cloud-dependencies:Greenwich.RELEASE`
2. The API Gateway Application uses the `@EnableDiscoveryClient` from `org.springframework.boot:spring-boot-gradle-plugin:2.1.3.RELEASE`. 
3. 2 services that are registered in Consul using the following configuration files:
```
{
  "service": {
    "name": "serviceA",
    "tags": [
      "nodejs",
      "serviceA"
    ],
    "port": 5001
  },
  "check": {
    "id": "serviceA",
    "name": "Check the status of the serviceA by making get request on 5001 port",
    "http": "http://localhost:5001/serviceA/status",
    "method": "GET",
    "interval": "10s",
    "timeout": "1s"
  }
}
```

The requests  comes to the Zuul. And then Zuul looks up the service instances from Consul and routes the request to the appropriate service instance. 

I've got the following strange behaviour of the Zuul: when the Consul fails to perform the health check of the serviceA then the service discovery mechanizm fails to discover the healthy service. However, when I remove the Consul health-check section in Consul, then the service-discovery works like a charm i.e. I am able to lookup the healthy service. 

Could anyone suggest how to fix this problem?

PS Zuul config in application.properties

```
server.port=8001
spring.application.name=api-gateway

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

zuul.routes.service-a.path=/service-a/**
zuul.routes.service-a.service-id=service-a

zuul.routes.service-b.path=/service-b/**
zuul.routes.service-b.service-id=service-b
```

**Comment by spencergibb** [comment]
If the healthcheck fails, why would you want to route to an unhealthy service?

**Comment by terancet** [comment]
@spencergibb thx for your feedback. In my situation, I do always send the request to the healthy service. The request to the healthy service (via Zuul) is failed when the Consul fails to perform the health check of the un-healthy service.

**Comment by spencergibb** [comment]
I still don't understand how the failing health check of the unhealthy service affects the healthy one.

**Comment by terancet** [comment]
Here is how I register services in Consul. I suspect that there might be Consul specific configuation issues

Normal service (healthy)

```
{
  "service": {
    "name": "weather-service",
    "tags": [
      "weather-service"
    ],
    "port": 5000
  },
  "check": {
    "id": "weath-service-status-api",
    "name": "Check the status of the weather-service by making get request on 5000 port",
    "http": "http://localhost:5000/weather/status",
    "method": "GET",
    "interval": "10s",
    "timeout": "1s"
  }
}
```

Failing service ()
```
{
  "service": {
    "name": "yield-loss-forecasts-service",
    "tags": [
      "nodejs",
      "yield-loss-forecasts-service"
    ],
    "port": 5001
  }, 
  "check": {
    "id": "yield-loss-forecasts-service-api",
    "name": "Check the status of the yield-loss-forecasts-service by making get request on 5001 port",
    "http": "http://localhost:5001/yield-loss-forecasts/status",
    "method": "GET",
    "interval": "10s",
    "timeout": "1s"
  }
}
```

And the exception stack trace from Zuul when I make the `GET` request to the healthy service

`http://localhost:8001/weather-service/weather/status`

```
com.netflix.zuul.exception.ZuulException: Forwarding error
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:191) ~[spring-cloud-netflix-zuul-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:166) ~[spring-cloud-netflix-zuul-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:114) ~[spring-cloud-netflix-zuul-2.1.0.RELEASE.jar:2.1.0.RELEASE]
Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: yLoad balancer does not have available server for client: weather-service
	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
```

**Comment by terancet** [comment]
@spencergibb the issue was in my consul service registration files. Accidentally, I defined the node health check instead of the particular service health check. In order to make it work properly, in `check` section should be present the `serviceId` key with the value of service name.
