### ISSUE TITLE
Consul Retry unexpected behaviour

### ISSUE THREAD

**Issue by PabloAA** [spring-cloud/spring-cloud-consul#560]
Consul Retry behaviour is inconsistent with the configuration.
Versions used:
Spring Boot - 2.1.5.RELEASE
Spring Cloud - Greenwich.RELEASE
Added spring-boot-starter-web, spring-boot-starter-actuator, spring-boot-starter-aop, spring-cloud-starter-consul-discovery and spring-retry starters.

Only if Consul it not available at startup and no custom configuration is used, the behaviour is the expected. If we shut down Consul while the service runs or try to customize the configuration (with spring.cloud.consul.retry.* or through defining a bean of type RetryOperationsInterceptor), the service tries to connect with Consul each two seconds without ending.

**Comment by ryanjbaxter** [comment]
The documentation specifically calls out that the retry configuration is only relevant during startup
http://cloud.spring.io/spring-cloud-static/Greenwich.SR1/single/spring-cloud.html#spring-cloud-consul-retry

**Comment by PabloAA** [comment]
I thought that by saying taking total control of the reply (when you add a bean) could be applied to subsequent falls.
However, custom configuration does not work at startup either

**Comment by spencergibb** [comment]
Duplicates #197

**Comment by PabloAA** [comment]
In this case, the problem is that it seems to ignore the properties of retries for the connection if Consul is not available on startup, not the reregistration
