### ISSUE TITLE
RefreshEventData is package private

### ISSUE THREAD

**Issue by dntbeSris** [spring-cloud/spring-cloud-consul#567]
Question

The ConfigWatch send massage to user application with spring-event-bus ,but user application can't get the event‘s data.

the configwatch:

```
    if (response.getValue() != null && !response.getValue().isEmpty()) {
        Long newIndex = response.getConsulIndex();

        if (newIndex != null && !newIndex.equals(currentIndex)) {
            // don't publish the same index again, don't publish the first time (-1) so index can be primed
            if (!this.consulIndexes.containsValue(newIndex) && !currentIndex.equals(-1L)) {
                RefreshEventData data = new RefreshEventData(context, currentIndex, newIndex);
                this.publisher.publishEvent(new RefreshEvent(this, data, data.toString()));
            }
            this.consulIndexes.put(context, newIndex);
        }
    }

```

my application lisenter

```
    @EventListener
    public void handle(RefreshEvent event) {
        if (this.ready.get()) {
            (RefreshEventData)event.getEvent();
        }
    }
```

but the **RefreshEventData** is a inner static class ,my application can't use it.
So,who can i handle this situation？

**Comment by marcingrzejszczak** [comment]
Hey @spencergibb what was the reason for sending this event? In Spring Cloud Consul repo I can't find any class reading the event.

**Comment by spencergibb** [comment]
It's in commons I believe

**Comment by marcingrzejszczak** [comment]
So we don't any users to operate with that event?

**Comment by spencergibb** [comment]
The event is from commons, but the data class is local to s-c-consul, but it's package private.

@dntbeSris why do you want to use that class?

**Comment by dntbeSris** [comment]
I need listening the consul config changed event more nimble. Although,i can loop the refresh keys 
 like this :
```
 @EventListener()
    public void handle(RefreshEvent event) {
        if (this.ready.get()) {
            Set<String> keys = this.refresh.refresh();
            for(String key : keys){
                if(key.startsWith(MY_CONFIG_PREFIX)){
                     //to do something
                }
            }
        }
    }
```
but spring will handle this expression when consul config value contians symbol like '{}',and will throw exception.

**Comment by dntbeSris** [comment]
I need listening the consul config changed event more nimble. Although,i
can loop the refresh keys
like this :

 @EventListener()
    public void handle(RefreshEvent event) {
        if (this.ready.get()) {
            Set<String> keys = this.refresh.refresh();
            for(String key : keys){
                if(key.startsWith(MY_CONFIG_PREFIX)){
                     //to do something
                }
            }
        }
    }

but spring will handle this expression when consul config value contians
symbol like '{}',and will throw exception.

Spencer Gibb <notifications@github.com> 于2019年7月30日周二 上午3:45写道：

**Comment by cr-kobyisrael** [comment]
Having same issue, need to check for specific key update, but RefreshEventData is package private.
