### ISSUE TITLE
get mulit datacenter's services for health check

### ISSUE THREAD

**Issue by Gsealy** [spring-cloud/spring-cloud-consul#568]
Hi team,

When I test multi datacenters call dc2's sevices from dc1 client agent. I found we should configure datacenter map in `application.yml` before application start. when service and datacenter num increase, use configuration files are not friendly.

We can get [ConsulDiscoveryProperties#datacenters](https://github.com/spring-cloud/spring-cloud-consul/blob/201f1fcc25851cf9ae4f022a90c60938eefd0d08/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryProperties.java#L140) value from [ConsulDiscoveryClient#getServices()](https://github.com/spring-cloud/spring-cloud-consul/blob/201f1fcc25851cf9ae4f022a90c60938eefd0d08/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClient.java#L116) 

plz check this idea, and a implement : https://github.com/Gsealy/spring-cloud-consul/commit/8858404594826772a0bb2ca792cf95e0388b663e

**Comment by Gsealy** [comment]
update:
may be a client don't want to get all services, don't need save multi datacenter's services to Map, use configuration file is fine.
But，get `ConsulDiscoveryClient.getServices()` shoud fetch all datacenter's services, like health check.

https://github.com/Gsealy/spring-cloud-consul/commit/e8b4406e3f915b77f0596d9534da336f168f416b

**Comment by ryanjbaxter** [comment]
So are you basically getting the services from all the configured data centers?  If you would like us to take a look at a code change please submit a PR.

**Comment by Gsealy** [comment]
I think all datacenters services should do health check , create a pr #573, please check it.

**Comment by spencergibb** [comment]
I'm still unsure why you want to get services from all datacenters?

**Comment by Gsealy** [comment]
for old requirement, we should do lb for same service from all datacenters, but get all services is too huge. so change to check all datacenters services health.
Aha, I just think a moment, different datacenter can do health check by themselves.

Thanks for reply, I'll close this issue
