### ISSUE TITLE
spring cloud consul bus questions.Thank you

### ISSUE THREAD

**Issue by dirkmurphy** [spring-cloud/spring-cloud-consul#572]
Question

Hello, we are trying to use spring cloud with consul as registration center and config center.
But we are stopped by a exception when integrate spring cloud consul bus. It seems like the issue [#458 ]

1. If we use consul as service registration center and config center,Do I have to use consul bus?
Can I use spring cloud bus to replace consul bus to implement event?

2. I am hard to find some spring cloud consul bus example on github or google. Can you provide some consul bus example?

Wait for your kindly help. Thank you very much

**Comment by dirkmurphy** [comment]
Users really need spring cloud consul bus detailed tutorial or example .
The tutorial of spring cloud consul bus on spring official site is useless.
[official tutorial](https://cloud.spring.io/spring-cloud-static/spring-cloud-consul/2.1.2.RELEASE/single/spring-cloud-consul.html#spring-cloud-consul-bus)

Thank you

**Comment by ryanjbaxter** [comment]
> If we use consul as service registration center and config center,Do I have to use consul bus?

No you can use Spring Cloud Consul without using Spring Cloud Bus.

> Can I use spring cloud bus to replace consul bus to implement event?

There is no "consul bus" only Spring Cloud Bus.

We don't have a sample that demonstrates the use o Spring Cloud Consul and Spring Cloud Bus, but we are happy to help you work through any questions or issues you might be having.  The best place to do that would be in the Spring Cloud Gitter channel where we can have a more real time discussion.

**Comment by dirkmurphy** [comment]
Hi ryanjbaxter ,
Thanks for your kindly help.
I mean that can I use spring cloud bus amqp with consul as registration center an config center ?
[spring cloud bus with consul ](https://cloud.spring.io/spring-cloud-static/spring-cloud-consul/2.1.2.RELEASE/single/spring-cloud-consul.html#spring-cloud-consul-bus)

Thank you again.

**Comment by spencergibb** [comment]
Yes
