### ISSUE TITLE
spring boot admin + concul   service can not be monitored

### ISSUE THREAD

**Issue by zhujiebing** [spring-cloud/spring-cloud-consul#576]
I use spring cloud version is Greenwich.SR2,  spring boot version is 2.1.6.RELEASE,  spring boot admin version is 2.1.6.    consul  is  Service discovery。    I met a problem，Only services before the admin is started can be monitored。 And A warning appears :  

!!!
Streaming through a reactive type requires an Executor to write to the response.
Please, configure a TaskExecutor in the MVC config under "async support".
The SimpleAsyncTaskExecutor currently in use is not suitable under load.

Controller:	de.codecentric.boot.admin.server.web.ApplicationsController
Method:		applicationsStream
Returning:	reactor.core.publisher.Flux<org.springframework.http.codec.ServerSentEvent<de.codecentric.boot.admin.server.web.ApplicationsController$Application>>
!!!

I hope to get your answer，  thank you very much。

**Comment by TYsewyn** [comment]
I'm not sure this is something we can help you with.
It would be better to post this question over at Codecentric: https://github.com/codecentric/spring-boot-admin
Reopen this ticket in case there is something we need to do.

/cc @joshiste
