### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by kundansdere** [spring-cloud/spring-cloud-consul#580]
Hi, I am using finchley.release version of sprin.cloud.consul with consul agent 1.2.3 and spring boot version 2.0.4. Here I am getting unknownHostException "localhost" for some random property which is not related to the consul at all, at the time of bean creation. While if I start the application with consul agent off then bean gets created successfully.
 Am I using the wrong dependencies? Any help /pointers appreciated

**Comment by spencergibb** [comment]
I don't know what dependencies you are using? Finchley and boot 2.0.x are no longer supported. Can you post the exception?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
