### ISSUE TITLE
Is spring cloud consul bus available now(spring cloud 2.1.x)?

### ISSUE THREAD

**Issue by dirkmurphy** [spring-cloud/spring-cloud-consul#582]
Hi team.

I use spring cloud consul 2.1 and stuck in spring-cloud-consul-bus long time for Issue [#458 ] & [#468 ]
Is spring-cloud-consul-bus available now(2.1.x)?

I searched everything about "spring cloud consul bus" in google and stackoverflow, but the information available is very limited.

**If it is available.** 
**Can you provide a sample for spring-cloud-consul-bus**
**WHY** there are few tutorials for spring cloud consul bus?
**WHY** [ConsulSampleApplication](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-sample/src/main/java/org/springframework/cloud/consul/sample/SampleConsulApplication.java) remove everything about consul bus?

**If it is not available.** 
Can you recommend a better way to implment distributed message for spring cloud?

**Thanks**

**Comment by spencergibb** [comment]
It is available. I think the reason there aren't many tutorials is because it is just a spring-cloud-stream implementation.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
