### ISSUE TITLE
when consul server restart . client not re-registration

### ISSUE THREAD

**Issue by xjr100419** [spring-cloud/spring-cloud-consul#586]
<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-consul</artifactId>
		<version>2.0.0.RELEASE</version>
		<relativePath>..</relativePath>
	</parent>

**Comment by hanct** [comment]
> org.springframework.cloud spring-cloud-consul 2.0.0.RELEASE ..

Hi, may i check why is this closed?  I currently encountered the same issue too
