### ISSUE TITLE
After the service was unregister from consul or eureka, it did not stop update servers

### ISSUE THREAD

**Issue by Fangfeikun** [spring-cloud/spring-cloud-consul#587]
I use ```DynamicServerListLoadBalancer``` to get servers from consul , when i unregister service and never use it, i found ```updateListOfServers``` function still run.

In my case, i will register many services and unregister it, and then not use it anymore, but this will lead to many useless updates.

In DynamicServerListLoadBalancer.java
```
public void updateListOfServers() {
        List<T> servers = new ArrayList<T>();
        if (serverListImpl != null) {
            servers = serverListImpl.getUpdatedListOfServers();
            LOGGER.debug("List of Servers for {} obtained from Discovery client: {}",
                    getIdentifier(), servers);

            if (filter != null) {
                servers = filter.getFilteredListOfServers(servers);
                LOGGER.debug("Filtered List of Servers for {} obtained from Discovery client: {}",
                        getIdentifier(), servers);
            }
        }
        updateAllServerList(servers);
    }
```
In ConsulServerList.java
```
@Override
	public List<ConsulServer> getInitialListOfServers() {
		return getServers();
	}

	@Override
	public List<ConsulServer> getUpdatedListOfServers() {
		return getServers();
	}

	private List<ConsulServer> getServers() {
		if (this.client == null) {
			return Collections.emptyList();
		}
		String tag = getTag(); // null is ok
		Response<List<HealthService>> response = this.client.getHealthServices(
				this.serviceId, tag, this.properties.isQueryPassing(),
				createQueryParamsForClientRequest(), this.properties.getAclToken());
		if (response.getValue() == null || response.getValue().isEmpty()) {
			return Collections.emptyList();
		}
		return transformResponse(response.getValue());
	}

```

Is this reasonable?

**Comment by spencergibb** [comment]
I'm a bit sure what your issue is. What does "many useless updates" mean? Can you please describe what is happening and what you think should happen? Pasting code from ribbon and consul isn't very helpful.

**Comment by Fangfeikun** [comment]
@spencergibb 
In some scenarios, I registered a service and then found it through the ribbon. Next, I unregister the service and never used it again, but the ribbon continues to refresh the instance of the service from the consul.

**Comment by Fangfeikun** [comment]
For example, I use ```spring cloud gateway```, ```ribbon``` and consul,  I sent a request, then ```LoadBalancerClient``` will find the service instance from consul, and refresh this service regularly

**Comment by Fangfeikun** [comment]
Do I have a clear explanation, my English is not very good.

**Comment by Fangfeikun** [comment]
I think it would be nice to provide a way to stop it.

**Comment by spencergibb** [comment]
There are caches in ribbon up to 30 seconds

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
