### ISSUE TITLE
Client side cache

### ISSUE THREAD

**Issue by rafaelrddc** [spring-cloud/spring-cloud-consul#594]
I am doing some testing using spring-cloud-consul for service discovery.

For this test I created a project and used DiscoveryClient to fetch information from services, everything works fine until I simulate a crash of Consul and with that I start getting error when fetching the service.

My doubt if this is expected behavior. Should he always get the information from the consul? No client cache?

**Comment by spencergibb** [comment]
Do you need to use discovery client directly? Load balancer client (via ribbon or spring cloud load balancer) cache instances

**Comment by rafaelrddc** [comment]
I don't need to use it directly. However I was conducting tests between Eureka and Consul and got this behavior with consul.

**Comment by spencergibb** [comment]
caching is an implementation detail of eureka client. The load balancers, ribbon and spring cloud loadbalancer implement caching. There are no plans to add one here.

**Comment by Fangfeikun** [comment]
Can you explain why there are no plans?
It's important  I think.

**Comment by Fangfeikun** [comment]
Can you explain why there are no plans?
It's important  I think.
