### ISSUE TITLE
Service name in the virtual URL is not resolved and hostname is used instead

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-cloud/spring-cloud-consul#600]
I'm using _Hoxton.M3_. In a `CommandLineRunner` I try the following WebClient request for another microservice, but I receive an `UnknownHostException` (see below) because the service name (registered in a _Consul_ registry) is not resolved and used as the hostname within the URL. Querying the Consul registry works fine with `ConsulReactiveDiscoveryClient.getInstances("...")`: the service name is definitely registered.

The code fragment for the invoking WebClient:
```
@Bean
fun webClientKunde(clientBuilder: WebClient.Builder) = CommandLineRunner {
	val client = clientBuilder
		.baseUrl("http://kunde") // <-- "kunde" is the name of a service registered in Consul
		.filter(basicAuthentication("...", "..."))
		.build()
	client.get()
		.uri("/...")
		.retrieve()
		.bodyToMono<Kunde>()
		.subscribe { logger.warn("WebClient request: {}", it) }
}
```

The section of the stacktrace:
```
...
2019-10-24 18:26:24.148  WARN 16816 --- [ctor-http-nio-1] io.netty.util.concurrent.DefaultPromise  : An exception was thrown by reactor.netty.resources.PooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.operationComplete()

reactor.core.Exceptions$ErrorCallbackNotImplemented: java.net.UnknownHostException: Der angegebene Host ist unbekannt (kunde)
Caused by: java.net.UnknownHostException: Der angegebene Host ist unbekannt (kunde)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
...
```

I also tried to exclude `spring-cloud-netflix-hystrix` and/or `spring-cloud-starter-netflix-ribbon` from the dependencies, but this didn't help either.

**Comment by juergenzimmermann** [comment]
@spencergibb I already have:

```
@Bean
@LoadBalanced
fun webClientBuilder() = WebClient.builder()
```

**Comment by juergenzimmermann** [comment]
I also tried:

```
@Bean
fun webClientKunde(clientBuilder: WebClient.Builder, lbFunction: ReactorLoadBalancerExchangeFilterFunction) = CommandLineRunner {
	val client = clientBuilder
		.baseUrl("http://kunde")
		.filter(lbFunction)
		.filter(basicAuthentication("...", "..."))
		.build()
```

Then the console shows:

```
...
2019-10-24 21:58:36.552  INFO 26740 --- [oundedElastic-2] d.h.b.c.dev.LogDiscoveryClientKunde      : Instance of Service kunde: URI = https://iwi-w-ziju01-a:8444
2019-10-24 21:58:36.625  WARN 26740 --- [  restartedMain] c.l.r.LoadBalancerExchangeFilterFunction : Load balancer does not contain an instance for the service kunde
...
```

and the server is shutting down.

**Comment by spencergibb** [comment]
You need the `@LoadBalanced` annotation on the injected builder, not just the bean definition.

**Comment by juergenzimmermann** [comment]
Adding the annotation `@LoadBalanced` at the injection point, doesn't change anything. I still get `WARN 8032 --- [  restartedMain] c.l.r.LoadBalancerExchangeFilterFunction : Load balancer does not contain an instance for the service kunde`.
I also tried to exclude `org.springframework.cloud:spring-cloud-netflix-hystrix` and `org.springframework.cloud:spring-cloud-starter-netflix-ribbon` from `org.springframework.cloud:spring-cloud-starter-consul-discovery` in the Gradle dependencies.

**Comment by spencergibb** [comment]
Hystrix has nothing to do with load balancing. We're going around in circles.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by juergenzimmermann** [comment]
OK, I'll try to provide a testcase in the late afternoon: 2 microservices, config server, Consul, MongoDB, mailserver. I'll see what I can strip away.

**Comment by spencergibb** [comment]
Config server mongodb and mail server should be removed

**Comment by juergenzimmermann** [comment]
[testcase-600.zip](https://github.com/spring-cloud/spring-cloud-consul/files/3777839/testcase-600.zip) @spencergibb The testcase is attached and contains ReadMe.txt.

**Comment by juergenzimmermann** [comment]
[testcase-600.zip](https://github.com/spring-cloud/spring-cloud-consul/files/3777839/testcase-600.zip) @spencergibb The testcase is attached and contains ReadMe.txt.

**Comment by juergenzimmermann** [comment]
@spencergibb Did you have a chance to reproduce the issue?

**Comment by juergenzimmermann** [comment]
See https://github.com/spring-cloud/spring-cloud-commons/issues/637
