### ISSUE TITLE
catalogWatchTaskScheduler spend much time about 10s

### ISSUE THREAD

**Issue by aa138002441** [spring-cloud/spring-cloud-consul#601]
i don't know where the time is go ? please help me 
![image](https://user-images.githubusercontent.com/22810287/67931346-97493b00-fbfc-11e9-9001-9896d41f9747.png)

**Comment by aa138002441** [comment]
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.907  [XNIO-2 task-1] [com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedProperty] [93]  - Flipping property: hystrix.threadpool.RibbonCommand.maximumSize to use NEXT property: hystrix.threadpool.default.maximumSize = 10
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.907  [XNIO-2 task-1] [com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedProperty] [93]  - Flipping property: hystrix.threadpool.RibbonCommand.keepAliveTimeMinutes to use NEXT property: hystrix.threadpool.default.keepAliveTimeMinutes = 1
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.908  [XNIO-2 task-1] [org.springframework.core.env.PropertySourcesPropertyResolver] [115]  - Found key 'hystrix.threadpool.default.maxQueueSize' in PropertySource 'bootstrapProperties' with value of type Integer
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.908  [XNIO-2 task-1] [com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedProperty] [93]  - Flipping property: hystrix.threadpool.RibbonCommand.maxQueueSize to use NEXT property: hystrix.threadpool.default.maxQueueSize = 1000
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.908  [XNIO-2 task-1] [org.springframework.core.env.PropertySourcesPropertyResolver] [115]  - Found key 'hystrix.threadpool.default.queueSizeRejectionThreshold' in PropertySource 'bootstrapProperties' with value of type Integer
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.909  [XNIO-2 task-1] [com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedProperty] [93]  - Flipping property: hystrix.threadpool.RibbonCommand.queueSizeRejectionThreshold to use NEXT property: hystrix.threadpool.default.queueSizeRejectionThreshold = 500
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.909  [XNIO-2 task-1] [com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedProperty] [93]  - Flipping property: hystrix.threadpool.RibbonCommand.metrics.rollingStats.timeInMilliseconds to use NEXT property: hystrix.threadpool.default.metrics.rollingStats.timeInMilliseconds = 10000
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.909  [XNIO-2 task-1] [com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedProperty] [93]  - Flipping property: hystrix.threadpool.RibbonCommand.metrics.rollingStats.numBuckets to use NEXT property: hystrix.threadpool.default.metrics.rollingStats.numBuckets = 10
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.979  [XNIO-2 task-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'ribbonLoadBalancerContext'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.981  [XNIO-2 task-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'ribbonClientConfig'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.985  [XNIO-2 task-1] [com.netflix.loadbalancer.ZoneAwareLoadBalancer] [112]  - Zone aware logic disabled or there is only one zone
[uap-zuul2][ DEBUG] 2019-10-31 12:06:26.986  [XNIO-2 task-1] [org.springframework.retry.support.RetryTemplate] [282]  - Retry: count=0
[uap-zuul2][ DEBUG] 2019-10-31 12:06:27.603  [PollingServerListUpdater-0] [com.netflix.loadbalancer.DynamicServerListLoadBalancer] [241]  - List of Servers for uap-company-user obtained from Discovery client: [192.168.1.83:10010]
[uap-zuul2][ DEBUG] 2019-10-31 12:06:27.603  [PollingServerListUpdater-0] [com.netflix.loadbalancer.DynamicServerListLoadBalancer] [246]  - Filtered List of Servers for uap-company-user obtained from Discovery client: [192.168.1.83:10010]
[uap-zuul2][ DEBUG] 2019-10-31 12:06:27.603  [PollingServerListUpdater-0] [com.netflix.loadbalancer.BaseLoadBalancer] [472]  - LoadBalancer [uap-company-user]: clearing server list (SET op)
[uap-zuul2][ DEBUG] 2019-10-31 12:06:27.603  [PollingServerListUpdater-0] [com.netflix.loadbalancer.BaseLoadBalancer] [488]  - LoadBalancer [uap-company-user]:  addServer [192.168.1.83:10010]
[uap-zuul2][ DEBUG] 2019-10-31 12:06:27.603  [PollingServerListUpdater-0] [com.netflix.loadbalancer.DynamicServerListLoadBalancer] [179]  - Setting server list for zones: {unknown=[192.168.1.83:10010]}
[uap-zuul2][ INFO ] 2019-10-31 12:06:27.603  [PollingServerListUpdater-0] [com.netflix.config.ChainedDynamicProperty] [115]  - Flipping property: uap-company-user.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
[uap-zuul2][ DEBUG] 2019-10-31 12:06:27.604  [PollingServerListUpdater-0] [com.netflix.loadbalancer.BaseLoadBalancer] [147]  - LoadBalancer [uap-company-user_unknown]:  initialized
[uap-zuul2][ DEBUG] 2019-10-31 12:06:27.609  [PollingServerListUpdater-0] [com.netflix.loadbalancer.BaseLoadBalancer] [472]  - LoadBalancer [uap-company-user_unknown]: clearing server list (SET op)
[uap-zuul2][ DEBUG] 2019-10-31 12:06:27.609  [PollingServerListUpdater-0] [com.netflix.loadbalancer.BaseLoadBalancer] [488]  - LoadBalancer [uap-company-user_unknown]:  addServer [192.168.1.83:10010]
[uap-zuul2][ DEBUG] 2019-10-31 12:06:27.609  [PollingServerListUpdater-0] [com.netflix.loadbalancer.BaseLoadBalancer] [811]  - LoadBalancer [uap-company-user]:  forceQuickPing invoking
[uap-zuul2][ DEBUG] 2019-10-31 12:06:27.609  [PollingServerListUpdater-0] [com.netflix.loadbalancer.BaseLoadBalancer] [884]  - LoadBalancer:  PingTask executing [1] servers configured
[uap-zuul2][ DEBUG] 2019-10-31 12:06:28.678  [catalogWatchTaskScheduler-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'discoveryClientConfigServiceBootstrapConfiguration'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:31.783  [catalogWatchTaskScheduler-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'discoveryClientConfigServiceBootstrapConfiguration'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:34.872  [catalogWatchTaskScheduler-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'discoveryClientConfigServiceBootstrapConfiguration'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:37.172  [pool-1-thread-1] [org.springframework.cloud.consul.discovery.ConsulDiscoveryClient] [93]  - Sending consul heartbeat for: service:uap-zuul2-192.168.1.83-10002
[uap-zuul2][ DEBUG] 2019-10-31 12:06:37.953  [catalogWatchTaskScheduler-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'discoveryClientConfigServiceBootstrapConfiguration'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:41.001  [catalogWatchTaskScheduler-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'discoveryClientConfigServiceBootstrapConfiguration'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.240  [XNIO-2 task-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'mvcValidator'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.240  [XNIO-2 task-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'defaultValidator'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.241  [XNIO-2 task-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'mvcValidator'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.241  [XNIO-2 task-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'defaultValidator'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.241  [XNIO-2 task-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'mvcValidator'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.242  [XNIO-2 task-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'defaultValidator'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.242  [XNIO-2 task-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'mvcValidator'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.242  [XNIO-2 task-1] [org.springframework.beans.factory.support.DefaultListableBeanFactory] [254]  - Returning cached instance of singleton bean 'defaultValidator'
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.243  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [97]  - Finding route for path: /api/company/company_users/companies
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.243  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [104]  - servletPath=/
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.243  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [105]  - zuulServletPath=/zuul
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.243  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [106]  - RequestUtils.isDispatcherServletRequest()=true
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.243  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [108]  - RequestUtils.isZuulServletRequest()=false
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.244  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [217]  - adjustedPath=/api/company/company_users/companies
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.244  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [123]  - Matching pattern:/api/auth/**
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.244  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [123]  - Matching pattern:/api/file/**
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.244  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [123]  - Matching pattern:/api/assets/**
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.244  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [123]  - Matching pattern:/api/user/**
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.244  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [123]  - Matching pattern:/api/setting/**
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.245  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [123]  - Matching pattern:/api/super/**
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.245  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [123]  - Matching pattern:/api/import/**
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.245  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [123]  - Matching pattern:/api/h5/**
[uap-zuul2][ DEBUG] 2019-10-31 12:06:42.245  [XNIO-2 task-1] [org.springframework.cloud.netflix.zuul.filters.SimpleRouteLocator] [123]  - Matching pattern:/api/company/**

**Comment by spencergibb** [comment]
it watches the consul catalog blocking for up to 10 seconds.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
