### ISSUE TITLE
Random port will cause service ID to be duplicated

### ISSUE THREAD

**Issue by zhangweikang** [spring-cloud/spring-cloud-consul#602]
* I am a newbie and found problems during the learning process. When I set server.port=0, the id of the registration service is always ${spring.application.name}-0, 
for example: spring-cloud-demo-consul-provider-0

* I looked at the source code, the priority service id is set first, prot is after, but the port is not considered when the service id is assembled and not reformatted.

* version
    * spring-cloud-consul-discovery-2.1.3.RELEASE

* see todo:
    * `org.springframework.cloud.consul.serviceregistry.ConsulAutoRegistration#initializePort`
```
public void initializePort(int knownPort) {
	if (getService().getPort() == null) {
		// not set by properties
		getService().setPort(knownPort);
		
		// todo ...
		// I think this should reformat the service id
	}
	// we might not have a port until now, so this is the earliest we
	// can create a check
	setCheck(getService(), this.autoServiceRegistrationProperties, getProperties(),
			this.context, this.heartbeatProperties);
}
```

* Submit lssue for the first time, write bad, please forgive me

**Comment by spencergibb** [comment]
I'm not keen on adding more support for random ports. You can set the service id yourself.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
