### ISSUE TITLE
application required a bean of type 'org.springframework.cloud.client.loadbalancer.LoadBalancerClient' that could not be found.

### ISSUE THREAD

**Issue by nwang12** [spring-cloud/spring-cloud-consul#603]
Question

I'm following the example file by adding all codes and pom file into my project. 
However when I try to execute the  IDE always shows output APPLICATION FAILED TO START.

Bug report

![image](https://user-images.githubusercontent.com/51484460/68513391-e3bdf780-0248-11ea-8175-b1210c25b8bf.png)

Am I missing any step that I need to do. Apologize if it is a simple question. This is my first time touching spring. Thank you

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
