### ISSUE TITLE
The session problems using the consul

### ISSUE THREAD

**Issue by wanghwtaiji** [spring-cloud/spring-cloud-consul#604]
使用consul时，pom中引入”spring-session-data-redis”,会发现redis中增量的存储session。导致redis崩溃。除了禁用session还有别的解决办法么？产生的具体原因是？

Using a consul, pom introduced in "spring-session-data-redis", will find in the redis incremental storage session. Cause redis to collapse. Is there any alternative to disabling session? What are the specific reasons?

**Comment by spencergibb** [comment]
Sorry, I don't understand your description. Can you post the errors you're seeing?

**Comment by wanghwtaiji** [comment]
Consul as registry, my service introduced the "spring-session-data-redis", and use the redis. After the service is started and registered successfully, you will find that the session has been incrementally saved in redis.Every few seconds, until redis dies
<img width="341" alt="屏幕快照 2019-11-12 下午5 14 27" src="https://user-images.githubusercontent.com/17980037/68658226-05342180-0570-11ea-897e-00addd192ae0.png">

**Comment by spencergibb** [comment]
I don't understand how that is related to Spring Cloud Consul.

**Comment by wanghwtaiji** [comment]
There is no such problems when using the eureka, had been replaced by consul.

**Comment by wanghwtaiji** [comment]
Find out the problem health check。 thank you
