### ISSUE TITLE
org.springframework.cloud.consul.discovery.ConsulCatalogWatch makes Consul high CPU

### ISSUE THREAD

**Issue by letingoo** [spring-cloud/spring-cloud-consul#611]
Based on the branch 2.0.x, I found that ConsulCatalogWatch would make Consul high CPU, it calls "/v1/catalog/services" frequently, nearly caused an accident. When reading codes, I dont't know its usage

**Comment by spencergibb** [comment]
You can disable it if needed `spring.cloud.consul.discovery.catalog-services-watch.enabled=false`. It's useful for a gateway that automatically adds routes when there are new services discovered.

**Comment by letingoo** [comment]
> You can disable it if needed `spring.cloud.consul.discovery.catalog-services-watch.enabled=false`. It's useful for a gateway that automatically adds routes when there are new services discovered.

Thanks

**Comment by arjpaiva** [comment]
Hello, 
I'm having the same issue. I have tried to disable the check with `spring.cloud.consul.discovery.catalog-services-watch.enabled=false` but it didn't work.
