### ISSUE TITLE
how can i use consul high availability

### ISSUE THREAD

**Issue by aeroyu** [spring-cloud/spring-cloud-consul#616]
i know the client can only set one host，and i see the closed issues about it, it suggest host point to the agent
but my question is if the client connect the agent,then this agent will become the single point,how can i make the agent high availability？

**Comment by spencergibb** [comment]
At the point the agent is down shouldn't there system restart the instance or do something to mitigate? The only thing Spring Cloud could do is reconnect and there is an open issue for that.

**Comment by aeroyu** [comment]
> At the point the agent is down shouldn't there system restart the instance or do something to mitigate? The only thing Spring Cloud could do is reconnect and there is an open issue for that.

i know the client can retry to connect the agent,but if the client cannot reset,because it will fail to start.

i mean this solution is not good, it is hard to recover from the fault

i found the other solution  is use nginx load balance

**Comment by spencergibb** [comment]
Not sure how this relates to spring cloud at this point
