### ISSUE TITLE
ConsulAutoRegistration.registration(...) not supported metadata property

### ISSUE THREAD

**Issue by kc4kt4** [spring-cloud/spring-cloud-consul#618]
NewService.class has field
`private meta Map<String, String>`
but no way to init it in the ConsulAutoRegistration by default.

I would like to add new field in ConsulDiscoveryProperties 
```
private Map<String, String> metadata = new HashMap<>();
```
and use this like
```
ConsulAutoRegistration.registration(..) {
  ...
    service.setMeta(properties.getMetadata());
  ...
}
```

**Comment by spencergibb** [comment]
Duplicates #575
