### ISSUE TITLE
consulServiceRegistry created even if consul discovery is disabled

### ISSUE THREAD

**Issue by brempusz** [spring-cloud/spring-cloud-consul#619]
**Describe the bug**
Bean `consulServiceRegistry`  is still created even if consul discovery is disabled.

I would like to use different configuration/discovery on AWS and K8S: 
- use consul for both discovery and configuration on AWS
- use kubernetes for discovery and consul for configuration on kubernetes

I use `kubernetes` profile to disable consul and enable k8s.

 
But even if I disable consul discovery I get bean conflict:
```
Parameter 0 of method serviceRegistryEndpoint in org.springframework.cloud.client.serviceregistry.ServiceRegistryAutoConfiguration$ServiceRegistryEndpointConfiguration required a single bean, but 2 were found:
	- getServiceRegistry: defined by method 'getServiceRegistry' in class path resource [org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientAutoConfiguration.class]
	- consulServiceRegistry: defined by method 'consulServiceRegistry' in class path resource [org/springframework/cloud/consul/serviceregistry/ConsulServiceRegistryAutoConfiguration.class]
```

The only way is to exclude autoconfiguration class:
```
spring.autoconfigure.exclude=org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistryAutoConfiguration
```
Or use property:
`@ConditionalOnProperty(value = "spring.cloud.service-registry.enabled", matchIfMissing = true)` (but, according to the name, this property is generic, not consul-specific).

But then, I have to  disable consul catalog watch: `spring.cloud.consul.discovery.catalog-services-watch.enabled=false` or I will get:

```
Parameter 0 of method consulCatalogWatch in org.springframework.cloud.consul.discovery.ConsulCatalogWatchAutoConfiguration required a bean of type 'org.springframework.cloud.consul.discovery.ConsulDiscoveryProperties' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'consulDiscoveryProperties' in 'ConsulDiscoveryClientConfiguration' not loaded because @ConditionalOnProperty (spring.cloud.consul.discovery.enabled) found different value in property 'spring.cloud.consul.discovery.enabled'
	- Bean method 'consulDiscoveryProperties' in 'ConsulReactiveDiscoveryClientConfiguration' not loaded because @ConditionalOnClass did not find required class 'org.springframework.web.reactive.function.client.WebClient'
	- Bean method 'consulDiscoveryProperties' in 'ConsulServiceRegistryAutoConfiguration' not loaded because auto-configuration 'ConsulServiceRegistryAutoConfiguration' was excluded
```

I would expect `spring.cloud.consul.discovery.enabled=false` to disable not needed consul beans.

**Sample**

https://github.com/brempusz/k8s-profile-issue

**Comment by spencergibb** [comment]
discovery and registration are now separate concerns. so `spring.cloud.service-registry.enabled` should work, but there should be a consul specific option as well.

**Comment by spencergibb** [comment]
@brempusz see #634 for disabling service registry and auto-registration thru consistent properties.

**Comment by brempusz** [comment]
@spencergibb thanks!
