### ISSUE TITLE
Need to remove eureka

### ISSUE THREAD

**Issue by nmarasoiu** [spring-cloud/spring-cloud-consul#62]
Hi,

Currently it is like a non deterministic choice of consul vs eureka.

I think eureka needs to be removed or wired out.
The way we did in our fork is to remove netflix-common which imported eureka but probably it is too brutal.

**Comment by spencergibb** [comment]
how so?  the `com.netflix.eureka:*` dependencies are optional and are not brought in when using maven or the spring dependency management gradle plugin.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
