### ISSUE TITLE
Support rsocket microservice use consul

### ISSUE THREAD

**Issue by xdxiaodao** [spring-cloud/spring-cloud-consul#620]
Now spring supports rsocket, using rsocket development of service system, whether in a planned way through the consul service discovery

**Comment by spencergibb** [comment]
Not sure what this means can you clarify. But the rsocket broker will be able to use consul to look up brokers.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by hsonawane** [comment]
Can you please explain how can we use consul as service discovery for rsocket clients

**Comment by spencergibb** [comment]
Inject a `LoadBalancerClient` and call `choose()`. That gives you a host and port you can use to connect to for rsocket
