### ISSUE TITLE
Investigate test containers for consul, so contributors don't need to go thru ceremony to build

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-consul#623]
@bsideup have you heard of consul for test containers?

**Comment by spencergibb** [comment]
I guess we just need a consul docker image.

https://hub.docker.com/_/consul

**Comment by bsideup** [comment]
@spencergibb sure!

https://github.com/denverx/testcontainers-consul
https://github.com/apache/camel/blob/4c07898ae1477504c2c1ff8bc745131561212616/components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulTestSupport.java#L78

**Comment by spencergibb** [comment]
Closed via #624
