### ISSUE TITLE
[Question] Optional Service Discovery

### ISSUE THREAD

**Issue by mishadoff** [spring-cloud/spring-cloud-consul#63]
Is there a way to enable service discovery optionally?

For example if we have some property like `discovery.enabled = false`, annotation processor skip service registration phase.

**Comment by spencergibb** [comment]
`spring.cloud.consul.discovery.enabled=false`

**Comment by aatarasoff** [comment]
@spencergibb, hi!

There are two settings: first is `spring.cloud.discovery.enabled` that come from spring cloud project, second is `spring.cloud.consul.discovery.enabled` from spring-cloud-consul.
If you set `spring.cloud.discovery.enabled=true` discovery other services will work as well cause `spring.cloud.consul.discovery.enabled` will be ignore. If you set `spring.cloud.consul.discovery.enabled=true` but turn off `spring.cloud.discovery.enabled` you cannot discovery other services but you service will be registered as well.
So we have two options with different behaviors and if `spring.cloud.discovery.enabled` has a predictable behavior, `spring.cloud.consul.discovery.enabled` has a very strange behavior that confused me.
I think that `spring.cloud.consul.discovery.enabled` must be rename cause it affects to service registration in consul, not to discovery other services.
