### ISSUE TITLE
Hashicorp Consul 1.7.2 compatibility with Spring boot 

### ISSUE THREAD

**Issue by venkatvgit** [spring-cloud/spring-cloud-consul#636]
Can you please help to understand if Hashicorp Consul 1.7.2 is compatible with below Spring boot and Spring Cloud Consul Starter versions?
-  Spring boot 1.5.10 with spring-cloud-starter-consul-all 1.3.0.RELEASE
-  Spring boot 2.1.2 with  spring-cloud-starter-consul-all 2.1.2.RELEASE

**Comment by spencergibb** [comment]
spring boot 1.x and spring cloud 1.x are not supported at all.

**Comment by venkatvgit** [comment]
Thanks Spencer for quick reply.

Can you please help to understand if below combinations are compatible with Hashicorp Consul 1.7.2?
Spring boot 2.1.2 with spring-cloud-starter-consul-all 2.1.2.RELEASE
Spring boot 2.2.6 with spring-cloud-starter-consul-all 2.2.2.RELEASE

**Comment by spencergibb** [comment]
They should be. Are you having a problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
