### ISSUE TITLE
support multiple health check at same time

### ISSUE THREAD

**Issue by helloworlde** [spring-cloud/spring-cloud-consul#644]
**Is your feature request related to a problem? Please describe.**
The http health check and the TTL health check can't work at same time,  if set `spring.cloud.consul.discovery.heartbeat.enabled=true`, then the http health check will be ignored. Could you tell me why not support this feature and if it will be support in future?

The code is [ConsulAutoRegistration#createCheck](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/serviceregistry/ConsulAutoRegistration.java#L234)  and [ConsulServiceRegistry#register](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/serviceregistry/ConsulServiceRegistry.java#L73)

**Comment by JellyBo** [comment]
+1
