### ISSUE TITLE
ConsulHealthIndicator should not query the entire service catalog

### ISSUE THREAD

**Issue by csabakos** [spring-cloud/spring-cloud-consul#646]
**Describe the bug**
`ConsulHealthIndicator` does a blanket query for the entire service catalog:
```
		final Response<Map<String, List<String>>> services = this.consul
				.getCatalogServices(QueryParams.DEFAULT);
```

In our system, the response JSON is over 500KB long, so this operation is unnecessarily heavy.

Consider removing this check (since maybe the leader check is sufficient), or replacing with a lighter query, such as `/v1/catalog/datacenters`.

**Comment by spencergibb** [comment]
PRs welcome
