### ISSUE TITLE
ConsulProperties Auto Binding occurs after the property is used

### ISSUE THREAD

**Issue by mulekej** [spring-cloud/spring-cloud-consul#647]
Spring cloud version: Hoxton.SR6

When specifying overrides for the consul host and port in application properties (spring.cloud.consul.host and spring.cloud.consul.port), the values from the properties file are not set on the ConsulProperties until after the ConsulAutoConfiguration has run with the default values used. 

Example project [here](https://github.com/mulekej/spring-consul-auto-config-issue)
```
plugins {
    id 'org.springframework.boot' version '2.3.1.RELEASE'
    id 'io.spring.dependency-management' version '1.0.9.RELEASE'
    id 'groovy'
}

group = 'com.ericmulek'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "Hoxton.SR6")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.codehaus.groovy:groovy'
    implementation 'org.springframework.cloud:spring-cloud-starter-consul-config'
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group:'org.junit.vintage', module:'junit-vintage-engine'
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

test {
    useJUnitPlatform()
}
```
To demonstrate the issue I started docker locally exposing it on port 9000 rather than 8500
![image](https://user-images.githubusercontent.com/2487044/86391460-78091e80-bc5f-11ea-9475-5f7711252fb9.png)

When I run the sample project (see above) with the following configuration, the app fails on startup.
```
spring.application.name=myService
spring.cloud.consul.enabled=true
spring.cloud.consul.host=localhost
spring.cloud.consul.port=9000
spring.cloud.consul.config.enabled=true
```

Exception on Startup:
`com.ecwid.consul.transport.TransportException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect`

When I break point through the startup process with consul running of port 8500, I can see the `ConsulAutoConfiguration` run and create the `ConsulClient` before it sets the property overrides with the Configuration Property Bindings.

**Comment by spencergibb** [comment]
the values need to go in bootstrap.properties

**Comment by mulekej** [comment]
bootstrap.properties was the issue. Thanks! I'll go read up more closely Spring Cloud Context

**Comment by spencergibb** [comment]
https://cloud.spring.io/spring-cloud-static/spring-cloud-consul/2.2.0.RELEASE/reference/html/#customizing
