### ISSUE TITLE
Cannot fire consul event

### ISSUE THREAD

**Issue by dean588** [spring-cloud/spring-cloud-consul#650]
Hi ,
I try to fire an event using below code but it doesn't work.Any suggestions?I use spring boot 2.3.1 version and Hoxton.SR6 spring-cloud -version and Java 8.

EventParams eventParams = new EventParams();
eventParams.setName("ms-event");
Response response = com.ecwid.consul.v1.ConsulClient.consulClient.eventFire("test", "122222", eventParams, QueryParams.DEFAULT);

ERROR LOG
[pool-1-thread-1] o.s.c.c.b.ConsulInboundMessageProducer : Error getting consul events: error occurred in message handler [org.springframework.cloud.consul.binder.ConsulSendingHandler@7e5b5d76]; nested exception is java.lang.ClassCastException: [B cannot be cast to java.lang.String

**Comment by spencergibb** [comment]
Duplicates #641
