### ISSUE TITLE
Option for manual deregistration

### ISSUE THREAD

**Issue by rakshitcgupta** [spring-cloud/spring-cloud-consul#652]
I am using route url of openshift for a service registration and health check. When I increase the pod of the service, these get registered in consul and I can see all instances there. But when the pods decrease, the instances don't get deregistered as the same route url is provided for all.

So a way to manually deregister a service from spring application using **service id** will be beneficial in such cases when the user wants to manually deregister from consul

**Comment by ryanjbaxter** [comment]
Rather than provide a method to unregister a service instance we need to understand why Consul is not removing the service instance in the first place.  Can you tell us how to reproduce the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by rakshitcgupta** [comment]
In my analysis, I found that if the kubernetes pod shuts down gracefully, this problem exists otherwise this deregistration works fine.
