### ISSUE TITLE
ConsulAutoRegistration change the instance-id

### ISSUE THREAD

**Issue by shouzheng** [spring-cloud/spring-cloud-consul#656]
when use spring-cloud-consul, it(class `ConsulAutoRegistration`) change the instance-id when register to consul. forexample, change `task-a.b` to `task-a-b`.

why do like this? consul support DNS format instance-id, we can register with `task-a.b` directly.

if we provide a `DiscoveryHealthIndicator` to check if the service on consul by instance-id, but we cannot find the instance by origin instance-id, unless we change the instance-id in the same way.

**Comment by spencergibb** [comment]
From the exception:

> "Consul service ids must not be empty, must start with a letter, end with a letter or digit, and have as interior characters only letters, digits, and hyphen

https://github.com/hashicorp/consul/blob/f36d77ee4a2fce61db88bdd2feda8f57a05a5d38/agent/agent.go#L2173-L2178
