### ISSUE TITLE
Support consul ACL tokens

### ISSUE THREAD

**Issue by bpgray** [spring-cloud/spring-cloud-consul#66]
It would be helpful to support ACL tokens for consul calls, for the use case where ACLs have been established in Consul and are required for kv store access and/or service registration.

If ACLs are in place, there are two ways to provide the token to consul (per consul.io) - either at the agent level (with the acl_token config parameter), or on a call specific basis. In some use cases, multiple applications/services will share an agent and may have different acl tokens defined. In these cases, setting the acl token at the agent level is not sufficient. By defining the token in a bootstrap.yml file, spring cloud consul could then provide the token for each call.

The Ecwid/consul-api supports providing a token in the KeyValueClient, but currently does not have the same support in the AgentClient. I'll open up an issue with consul-api to support tokens in the AgentClient, and I think that can be resolved by following the same pattern that exists in the KeyValueClient.

**Comment by spencergibb** [comment]
Sounds good. Can you put a link to the `consul-api` issue when you create it?

**Comment by bpgray** [comment]
Issue opened to support tokens in consul-api AgentClient
https://github.com/Ecwid/consul-api/issues/22

**Comment by bpgray** [comment]
ACLs support has been added to the consul-api AgentClient in version 1.1.6.
Commit is here: https://github.com/Ecwid/consul-api/commit/5420831f46a9842218ad652508eff433b8e0f9b2

**Comment by bpgray** [comment]
Ticket opened and pull request submitted to consul-api to support deregistering services with token
https://github.com/Ecwid/consul-api/issues/27

**Comment by spencergibb** [comment]
Closed via 5154b91855fa1521dbd855e47bffcd1cb7c9b5f3
