### ISSUE TITLE
Consul healthcheck always returns 503 with actuator

### ISSUE THREAD

**Issue by chandresh-pancholi** [spring-cloud/spring-cloud-consul#663]
**Describe the bug**
I am using spring boot consul config/discovery for config management. after adding the dependencies health check API started returning 503. tried many things but couldn't find a solution so raising it here. 

We are using Vault/Consul.

```
        compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-consul-config', version: '2.2.3.RELEASE'
        compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-consul-discovery', version: '2.2.3.RELEASE'
        runtime group: 'org.springframework.cloud', name: 'spring-cloud-starter-vault-config', version: '2.2.3.RELEASE'
```
**Sample**
```
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.prometheus=/prometheus/metrics
management.endpoints.web.exposure.include=prometheus,health,refresh
management.security.enabled=false
```

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
