### ISSUE TITLE
Incorrect port registered when using management.port

### ISSUE THREAD

**Issue by bpgray** [spring-cloud/spring-cloud-consul#67]
In some instances it makes sense to run the spring boot management server on a different port from the primary application server. This can be accomplished by setting 'management.port'.
Documented in 41.3 here: http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html

When management.port is set, spring-cloud-consul registers two NewService's with consul, one for the primary application and one for the management. It is helpful to have both services registered in consul separately. However, both services are registered with a port equal to the management.port, making the application service entry in the consul catalog incorrect.

**Comment by spencergibb** [comment]
I'm unable to duplicate.  Do you have a project you can share?

**Comment by bpgray** [comment]
I made a slimmed down project that demonstrates the same behavior:
[link to repo](https://github.com/bpgray/spring-cloud-consul-test)

The application context runs on port 8080 and the management context runs on port 8081

* Both the application and management context are registered with consul on port 8081, rather than their respective ports.
* The consul service ids for both services contain '8080' in their string, rather than their respective ports.
* For the application health check, the url contains port 8081. I'd actually like this health check to be on port 8080, but understand this might be a bit atypcial and can address by overriding the healthCheckUrl with an application.yml entry.

**Comment by spencergibb** [comment]
@bpgray thanks for the repo, very helpful!

**Comment by bpgray** [comment]
Thank you for the very fast response! Tested out great on my end.
