### ISSUE TITLE
Clarification on how ConfigWatch works?

### ISSUE THREAD

**Issue by TwinkleTShah** [spring-cloud/spring-cloud-consul#674]
Hello,

I read in the document https://cloud.spring.io/spring-cloud-consul/reference/html/#spring-cloud-consul-config-watch, that the "ConfigWatch takes advantage to watch functionality of Consul". Per my understanding a watch in Consul takes care of looking for any change in particular key prefix and trigger a callback if any change is detected. 
Does the spring-cloud-consul-config creates a watch in consul with some callback endpoint?

Reading at the code here https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-config/src/main/java/org/springframework/cloud/consul/config/ConfigWatch.java#L158, it looks like the ConfigWatch makes periodic HTTP calls to identify any changes made in Consul KV. So, it's basically polling for any changes and not relying on callback from Consul watch.

Can someone please help clarify this?

**Comment by spencergibb** [comment]
https://www.consul.io/api-docs/features/blocking

**Comment by TwinkleTShah** [comment]
Thanks @spencergibb  for providing this reference.
So, it means there would be periodic calls which would be blocking queries for KV changes. The query will wait for any update or until wait time is expired. Is this correct?

**Comment by spencergibb** [comment]
That is correct

**Comment by TwinkleTShah** [comment]
Thank you so much. I don't have further questions for now.
