### ISSUE TITLE
TTL Checks only report Pass, and ignore real health status from the application

### ISSUE THREAD

**Issue by jdeex** [spring-cloud/spring-cloud-consul#676]
**Describe the bug**
TTL seems to only reports pass, even when there are health indicators failing. Even when the Health Endpoint <aaplication/actuator/health reports DOWN (and HTTP+Interval would show that way in Consul), the TTL check reports OK instead. 

Having a look at the code [it could be because of this ](https://github.com/spring-cloud/spring-cloud-consul/blob/c702c15be7e2588db8d12eeeabbadbeb5cb943e1/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/TtlScheduler.java#L93)

TTL should check the application status and report that using[ Consul TTL endpoints ](https://www.consul.io/docs/discovery/checks#ttl)

**Sample**
Implement a test health indicator that will cause the status to be down:
`public class TestHealthIndicator implements HealthIndicator {
    @Override
    public Health health() {
        return Health
                .down()
                .withDetail("test", "App is failing")
                .build();
    }
}`

Enable TTL in the spring configuration:
`spring:
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
          ttl-value: 30
          ttl-unit: m`

Review /actuator/health Down status and status reported in Consul

**Comment by bono007** [comment]
I picked this one up. I have a working solution - adding tests then will submit proposal.

**Comment by aromanos** [comment]
Hi @bono007 this is also useful for my use case. Is this commit going to be merged?

**Comment by bono007** [comment]
@spencergibb I know you and team are busy doing "all the things" :)  When you can, could you please give this one a review? Thank you.

**Comment by bono007** [comment]
@spencergibb I bit the bullet and did the nasty rebase/merge - should be good now.

**Comment by jdeex** [comment]
Hey, how is it going? thought It was merged already. In what release is this expected to be available?

**Comment by spencergibb** [comment]
@jdeex it is scheduled for later this year.

**Comment by jdeex** [comment]
@spencergibb I saw this one missed the 2021.0.0 release, what's the target for this issue?

**Comment by jdeex** [comment]
Any update on this one??
