### ISSUE TITLE
Consul NewService$Check issue

### ISSUE THREAD

**Issue by santoshmv121** [spring-cloud/spring-cloud-consul#686]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

** Description:
An attempt was made to call a method that does not exist. The attempt was made from following location:

org.springframework.cloud.consul.serviceregistry.ConsulAutoRegistration.createCheck(ConsulAutoRegistration.java.245)

The following method did not exist:
com.ecwid.consul.v1.agent.model.NewService$Check.setHeader(Ljava/util/Map;)V

The method'class, com.ecwid.consul.v1.agent.model.NewService$Check, is available from following location:

jar:path!/BooT-INF/lib/consul-api-1.2.4.SG2.jar!/com/ecwid/consul/v1/agent/model/NewService$Check.class

It was loaded from the following location:

jar:path.jarname.jar!/BOOT-INF/lib/consul-api-1.2.4.SG2.jar!/

Action:

Correct the classpath of your application so that it contains a single, compatible version of com.ecwid.consul.v1.agent.model.NewService$Check
**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.
![16065080356882497535797867555648](https://user-images.githubusercontent.com/59571096/100481775-3d76b580-311b-11eb-99a6-a84043bdc8fe.jpg)

**Comment by santoshmv121** [comment]
I moved from Spring boot 1.x to 2.x version. I am getting this issue after migration. Could you please help me with the issue.

**Comment by santoshmv121** [comment]
![16065083101114578500204544733653](https://user-images.githubusercontent.com/59571096/100481967-defe0700-311b-11eb-8158-87a18450a544.jpg)
bootstrap filw

**Comment by spencergibb** [comment]
Please no pictures of code.

You have an incompatible version of consul-api. Let the bom manage the version

**Comment by santoshmv121** [comment]
even if I am explicitly mentioning the versions its picking older version. Its weird. Could you please suggest me ?

Which version should I use? It it just issue with version because same version were working for Spring boot 1.x , after migration it stopped working.

**Comment by spencergibb** [comment]
Without seeing your full pom (no pictures) I can't help
