### ISSUE TITLE
Shutdown endpoint does not deregister management service

### ISSUE THREAD

**Issue by bpgray** [spring-cloud/spring-cloud-consul#69]
Now that #67 is closed, I've noticed that the management service is not deregistered with consul when calling the spring boot shutdown endpoint. Since the management service is not registered with an http check (or ttl), I believe the service will persist in consul indefinitely, or until a deregister consul api call is made.

**Comment by spencergibb** [comment]
@bpgray so if the management port is set, the `/health` endpoint moves to it, so the normal check fails.  I'm thinking of setting both health check ports to the management port if enabled.  The other option is to use ttl.

**Comment by bpgray** [comment]
@spencergibb moving the health check helps, but I think it's a slightly different issue. If the shutdown endpoint of a spring boot application is called, the application terminates and the primary service is deregistered by spring cloud consul. I would argue that the management service should be deregistered as the same time. With the latest commit, the the management service will presist but now with failing health checks, which doesn't seem representative of an intended application shutdown.

**Comment by spencergibb** [comment]
@bpgray it does attempt to deregister management.  I see:
```
    2015/08/28 14:15:59 [INFO] agent: Deregistered service 'testConsulApp-management'
```
But it doesn't complete or something.

**Comment by spencergibb** [comment]
even running `http :8500/v1/agent/service/deregister/testConsulApp-management` directly doesn't deregister, so either the registration is a bug, or there is a consul bug.

**Comment by spencergibb** [comment]
that's the name, not the id.  fix coming shortly
