### ISSUE TITLE
Behavior of spring.cloud.consul.discovery.enabled is strange

### ISSUE THREAD

**Issue by aatarasoff** [spring-cloud/spring-cloud-consul#71]
@spencergibb, hi!

There are two settings: first is `spring.cloud.discovery.enabled` that come from spring cloud project, second is `spring.cloud.consul.discovery.enabled` from spring-cloud-consul.
If you set `spring.cloud.discovery.enabled=true` discovery other services will work as well cause `spring.cloud.consul.discovery.enabled` will be ignore. If you set `spring.cloud.consul.discovery.enabled=true` but turn off `spring.cloud.discovery.enabled` you cannot discovery other services but your service will be register as well.
So we have two options with different behaviors and if `spring.cloud.discovery.enabled` has a predictable behavior, `spring.cloud.consul.discovery.enabled` has a very strange behavior that confused me.
I think that `spring.cloud.consul.discovery.enabled` should be rename cause it affects to service registration in consul, not to discovery other services.

**Comment by spencergibb** [comment]
The `*.consul.*` properties are mostly for completeness and aren't really documented anywhere. They've also been requested to turn each piece off for testing.

**Comment by spencergibb** [comment]
Sorry for the late reply, btw.

**Comment by aatarasoff** [comment]
Close this issue cause it was fixed in #102 PR
