### ISSUE TITLE
Fix docs for using eclipse w/o m2

### ISSUE THREAD

**Issue by efenderbosch** [spring-cloud/spring-cloud-consul#73]
In this section of README.adoc

https://github.com/spring-cloud/spring-cloud-consul#importing-into-eclipse-without-m2eclipse

>**Importing into eclipse without m2eclipse**

>If you prefer not to use m2eclipse you can generate eclipse project metadata using the following command:
```
$ mvn eclipse:eclipse
```

The ```mvn eclipse:eclipse``` section should be ```mvn --settings .settings.xml eclipse:eclipse```

The build fails otherwise.

**Comment by spencergibb** [comment]
We just are redoing are build infrastracture to use maven wrapper.  After you update, `./mvnw eclipse:eclipse` should work.  Let me know.

Fixed via 0112bf8b56166840c1ff7e60638b40b3c8a9ea8c

**Comment by efenderbosch** [comment]
I still need to pass --settings .settings.xml in to mvnw, otherwise it tries to go through our internal nexus.

**Comment by spencergibb** [comment]
The `./mvnw` command sets a spring profile which has the appropriate repositories defined in `pom.xml`.  Not sure what we can do about your internal nexus.
