### ISSUE TITLE
Error querying consul Key/Values for context 'config/pt,prod/'. Message: Connection pool shut 

### ISSUE THREAD

**Issue by csx-bill** [spring-cloud/spring-cloud-consul#739]
This happens occasionally after the service has been running for a period of time

Error querying consul Key/Values for context 'config/pt,prod/'. Message: Connection pool shut

**Comment by spencergibb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by atithikumari** [comment]
My spring boot application is stopping automatically after this warning comes. And to tackle for now , I had to disable the config watch. It is not an ideal way.

**Comment by atithikumari** [comment]
Tried out by setting fail-fast as false in Spring boot 2.2.0 but still the issue persists? Any idea on the fix or plans to tackle the error
