### ISSUE TITLE
ConsulReactiveDiscoveryClient supports fault when consul cluster unavailable

### ISSUE THREAD

**Issue by chenzhiguo** [spring-cloud/spring-cloud-consul#751]
`ConsulReactiveDiscoveryClient` should support the backup service list function. If the consul cluster is not available, the data should be returned to the last successful request.

**Comment by ryanjbaxter** [comment]
Looks like you have a potential fix in your fork, would you like to submit that as a PR to the project?

**Comment by chenzhiguo** [comment]
Yeah, I have submit the PR(#752).

**Comment by spencergibb** [comment]
See comment here https://github.com/spring-cloud/spring-cloud-consul/pull/752#issuecomment-1462561443
