### ISSUE TITLE
'contextPath' information not added to meta field during Consul registration

### ISSUE THREAD

**Issue by MatthiasZerau** [spring-cloud/spring-cloud-consul#755]
According to the [Spring Cloud Consul documentation](https://docs.spring.io/spring-cloud-consul/docs/2.2.7.RELEASE/reference/html/#official-consul-metadata) support for `meta` field is available and parsing of the `tags` field is deprecated and will be removed in a future version. There's also a configuration property `spring.cloud.consul.discovery.tags-as-metadata` which controls the behavior.

However, when the property is set to `false` not all auto generated meta data is written into the `meta` field. The property `contextPath` is still added as entry in `tags` field c.f. [ConsulServletRegistrationCustomizer](https://github.com/spring-cloud/spring-cloud-consul/blob/main/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/serviceregistry/ConsulServletRegistrationCustomizer.java).

As a result I end up with a Consul service registration for my web application where some data can be found in `meta` and other in `tags`. This makes it unnecessarily complex for clients to consume those properties.

**Comment by spencergibb** [comment]
tags-as-metadata is no longer supported.
