### ISSUE TITLE
UnsatisfiedDependencyException while creating ConfigWatch bean

### ISSUE THREAD

**Issue by omarchenko4j** [spring-cloud/spring-cloud-consul#757]
When the property `spring.cloud.consul.config.watch.enabled` is `true` an exception `UnsatisfiedDependencyException` is thrown in `ConsulRefreshConfiguration` when creating a bean `ConfigWatch` because 2 candidate beans with type `ConsulConfigIndexes` are found:
1. `consulPropertySourceLocator`
2. `configDataConsulConfigIndexes`

This happens because the `ConsulPropertySourceLocator` class implements the `ConsulConfigIndexes` interface as well as `ConsulConfigDataIndexes`, which is registered as a bean dynamically in the `ConsulConfigDataLocationResolver:resolveProfileSpecific()`.

Reproduced in  [this test project](https://github.com/spring-cloud/spring-cloud-consul/files/7429252/spring-cloud-example.zip) on _Spring-Cloud_ version **2020.0.4** with _spring-cloud-starter-consul-config_ version **3.0.4**.

**Comment by topurce** [comment]
you have duplicated configurations for consul:
1. `config:  import: "optional:consul:"`
2. `spring.cloud.consul.config`

the first one will resolve the config from org.springframework.cloud.consul.config.ConsulConfigDataLocationResolver it will register ConsulConfigDataIndexes as bean:
`this.registerAndPromoteBean(resolverContext, ConsulConfigIndexes.class, InstanceSupplier.from(ConsulConfigDataIndexes::new));`

the second one will resolve the config by org.springframework.cloud.consul.config.ConsulConfigAutoConfiguration, and on the configWatch method, it needs the ConsulConfigIndexes bean which implemented by ConsulPropertySourceLocator, also it registered by the first one, so it will throw not unique exception.

two ways to resolve the issue:
1. remove the `config: import: "optional:consul:"`
2. or add below to the config (bootstrap.yml):

`  autoconfigure:`
`    exclude: org.springframework.cloud.consul.config.ConsulConfigAutoConfiguration`

**Comment by spencergibb** [comment]
why do you have `spring.config.import` and bootstrap? Only one is required.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
