### ISSUE TITLE
Consulclient executepreparedquery not using acl

### ISSUE THREAD

**Issue by piesoftsol** [spring-cloud/spring-cloud-consul#769]
I'm working on zuulgateway with consul using consul libraries 3.0.1 with 2 datacenters. when I'm trying to perform the failover to other data center consulclient.executepreparedquery going empty result even the service is available to serve. this issue happening when we are enabling the acl with default policy true.

where as if all is disabled consulclient.executepreparedquery is able to respond with valid services in secondary data center when service in primary data center is down.

I don't see capability to use acl in consulclient.executepreparedquery method.

is there any way that I can configure my zuul gateway uses the consul query instead of consul service.

**Comment by spencergibb** [comment]
zuul is no longer supported. I think you need to make a request here https://github.com/Ecwid/consul-api
