### ISSUE TITLE
How to point to an agent withs spring-cloud-consul ? Is this way really highly available?

### ISSUE THREAD

**Issue by SpinSi** [spring-cloud/spring-cloud-consul#776]
How to point to an agent withs spring-cloud-consul ? Is this way really highly available ?
Are there any examples ？
Beg for your replay ,thank you !

**Comment by spencergibb** [comment]
The default configuration is to point to an agent. Can you describe more of what you are looking for?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
