### ISSUE TITLE
Actuator is required for spring-cloud-consul

### ISSUE THREAD

**Issue by arun0009** [spring-cloud/spring-cloud-consul#78]
I get the below exception when I try to create a Rest client (using Feign) with consul as service discovery/registry. 

<pre>
notificationsapiclient_1 | 2015-09-04 03:12:52.670 ERROR 8 --- [           main] o.s.boot.SpringApplication               : Application startup failed
notificationsapiclient_1 | 
notificationsapiclient_1 | java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.consul.ConsulAutoConfiguration.consulProperties
notificationsapiclient_1 | 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:58)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:190)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:148)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:124)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:318)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:239)
notificationsapiclient_1 | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254)
notificationsapiclient_1 | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94)
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
notificationsapiclient_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
notificationsapiclient_1 | 	at com.capitalone.api.notifications.service.NotificationsApiClient.main(NotificationsApiClient.java:61)
notificationsapiclient_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
notificationsapiclient_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
notificationsapiclient_1 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
notificationsapiclient_1 | 	at java.lang.reflect.Method.invoke(Method.java:497)
notificationsapiclient_1 | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
notificationsapiclient_1 | 	at java.lang.Thread.run(Thread.java:745)
notificationsapiclient_1 | Caused by: java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)
notificationsapiclient_1 | 	at org.springframework.util.Assert.isTrue(Assert.java:65)
notificationsapiclient_1 | 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:232)
notificationsapiclient_1 | 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:93)
notificationsapiclient_1 | 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:45)
notificationsapiclient_1 | 	... 22 common frames omitted
notificationsapiclient_1 | 
notificationsapiclient_1 | 2015-09-04 03:12:52.678  INFO 8 --- [           main] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7691a765: startup date [Fri Sep 04 03:12:47 UTC 2015]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@6a32b6fb
notificationsapiclient_1 | 2015-09-04 03:12:52.679  WARN 8 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception thrown from ApplicationListener handling ContextClosedEvent
notificationsapiclient_1 | 
notificationsapiclient_1 | java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7691a765: startup date [Fri Sep 04 03:12:47 UTC 2015]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@6a32b6fb
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:344)
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:869)
notificationsapiclient_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:150)
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:836)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:342)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
notificationsapiclient_1 | 	at com.capitalone.api.notifications.service.NotificationsApiClient.main(NotificationsApiClient.java:61)
notificationsapiclient_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
notificationsapiclient_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
notificationsapiclient_1 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
notificationsapiclient_1 | 	at java.lang.reflect.Method.invoke(Method.java:497)
notificationsapiclient_1 | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
notificationsapiclient_1 | 	at java.lang.Thread.run(Thread.java:745)
notificationsapiclient_1 | 
notificationsapiclient_1 | 2015-09-04 03:12:52.681  WARN 8 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception thrown from LifecycleProcessor on context close
notificationsapiclient_1 | 
notificationsapiclient_1 | java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7691a765: startup date [Fri Sep 04 03:12:47 UTC 2015]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@6a32b6fb
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:357)
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:877)
notificationsapiclient_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:150)
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:836)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:342)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
notificationsapiclient_1 | 	at com.capitalone.api.notifications.service.NotificationsApiClient.main(NotificationsApiClient.java:61)
notificationsapiclient_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
notificationsapiclient_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
notificationsapiclient_1 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
notificationsapiclient_1 | 	at java.lang.reflect.Method.invoke(Method.java:497)
notificationsapiclient_1 | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
notificationsapiclient_1 | 	at java.lang.Thread.run(Thread.java:745)
notificationsapiclient_1 | 
notificationsapiclient_1 | java.lang.reflect.InvocationTargetException
notificationsapiclient_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
notificationsapiclient_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
notificationsapiclient_1 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
notificationsapiclient_1 | 	at java.lang.reflect.Method.invoke(Method.java:497)
notificationsapiclient_1 | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
notificationsapiclient_1 | 	at java.lang.Thread.run(Thread.java:745)
notificationsapiclient_1 | Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.consul.ConsulAutoConfiguration.consulProperties
notificationsapiclient_1 | 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:58)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:190)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:148)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:124)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:318)
notificationsapiclient_1 | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:239)
notificationsapiclient_1 | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254)
notificationsapiclient_1 | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94)
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
notificationsapiclient_1 | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
notificationsapiclient_1 | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
notificationsapiclient_1 | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
notificationsapiclient_1 | 	at com.capitalone.api.notifications.service.NotificationsApiClient.main(NotificationsApiClient.java:61)
notificationsapiclient_1 | 	... 6 more
notificationsapiclient_1 | Caused by: java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)
notificationsapiclient_1 | 	at org.springframework.util.Assert.isTrue(Assert.java:65)
notificationsapiclient_1 | 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:232)
notificationsapiclient_1 | 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:93)
notificationsapiclient_1 | 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:45)
notificationsapiclient_1 | 	... 22 more
</pre>

**Comment by spencergibb** [comment]
I'm unable to reproduce (6fdd751256b4bf1429a602942904dfae8361c7bb). Do you have a project you can share that reproduces it?

**Comment by arun0009** [comment]
@spencergibb Here's the repo:

https://bitbucket.org/arun0009/microservices

**Comment by spencergibb** [comment]
@arun0009 that repo is not accessible.

**Comment by arun0009** [comment]
@spencergibb Sorry, can you try now? I made it public repo.

**Comment by spencergibb** [comment]
Actuator beans were not guarded by `@ConditionalOnClass(Endpoint.class)`. To work around this, add `spring-boot-starter-actuator`. The latest `1.0.0.BUILD-SNAPSHOT` will have the fix.

**Comment by kapoora** [comment]
I am new to Spring cloud i am using below grade dependency but still getting the above error.

compile 'org.springframework.cloud:spring-cloud-starter-consul-all:1.0.0.M6'

**Comment by spencergibb** [comment]
@kapoora, please open a new issue and describe your error and configuration, this has been closed for six months
