### ISSUE TITLE
Without web dependency, the project cannot be registered in consul

### ISSUE THREAD

**Issue by herestars** [spring-cloud/spring-cloud-consul#791]
Items cannot be registered in consul because I follow your comments. I observed that consul was based on the HTTP protocol, so I tried to join the springboot-web dependency and run successfully. But this is not explained in the README file, who can tell me why.
This is dependency :
```xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-consul-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
```

**Comment by weir2010** [comment]
me too

**Comment by weir2010** [comment]
4.0.0-M3    me too

**Comment by spencergibb** [comment]
consul discovery tries to register using a port that is gathered from the web server. Have you tried setting `spring.cloud.consul.discovery.port`? What are you using for requests if not web?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
