### ISSUE TITLE
Unavailable to specify failures_before_critical parameter for healthcheck configuration

### ISSUE THREAD

**Issue by BarannikovIS** [spring-cloud/spring-cloud-consul#793]
Hello!

**Is your feature request related to a problem? Please describe.**
Needed to have ability to configure trashholds for healthcheck configuration. 

**Describe the solution you'd like**
Native consul API has parameter failures_before_critical but spring-cloud-consul doesn't.

Will be great to support the same parameter and functionality in spring-cloud-consul

**Comment by spencergibb** [comment]
This project depends on https://github.com/Ecwid/consul-api for the consul client, support would be needed there first.
