### ISSUE TITLE
no ILoadBalancer / Consul 

### ISSUE THREAD

**Issue by nmarasoiu** [spring-cloud/spring-cloud-consul#8]
Running the example as given, the localhost:8080 says Error: No ILoadBalancer instance!

So we have seen that:
- the push in Consul (registration) works
- the discovery works
- the load balancer does not work! There is no Consul specific Balancer implementation, and even though there is a ConsulServerList implementation, it is not wired, and attempting to wire it proves a little cumbersome, I wonder if you actually have it working, because me and my colleague could not,,

It seems unfinalized code or configuration, also felt when seeing a commented piece of code with ConsulLoadBalancer, which is a class that no longer exists!

**Comment by spencergibb** [comment]
@nmarasoiu s-c-consul uses the s-c-netflix ribbon load balancer.   See the [pom](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/pom.xml#L23-L38). The sample app works:
https://github.com/spring-cloud/spring-cloud-consul/tree/master/spring-cloud-consul-sample

**Comment by nmarasoiu** [comment]
yes i know but I was saying that in fact the 5 bullet points test mentioned
in readme of spring cloud consul do not cureently work and in fact give
that exceptiin of iloadbalancer no instance found..

the only way i made it work is inject a serverlist in context. even so it
works for single dependency for now

i will check your sample repo and five feedback

it is important for us to have this working elgantly so maybe we will have
some suggested options or pull requests if opportune

thanks

În data de joi, 19 februarie 2015, Spencer Gibb <notifications@github.com>
a scris:

**Comment by spencergibb** [comment]
@nmarasoiu this is a technology preview and is in flux and is not fully supported right now.
