### ISSUE TITLE
Consul token query parameter deprecated in Consul 1.17

### ISSUE THREAD

**Issue by budaestew** [spring-cloud/spring-cloud-consul#809]
In Consul 1.15.0, The following logs were displayed.

![consul](https://user-images.githubusercontent.com/9033564/221427236-49c1fa86-406c-4e56-96f3-ea152052049c.jpg)

It looks like the consul-api library needs to be updated.

[Reference](https://developer.hashicorp.com/consul/docs/upgrading/upgrade-specific#deprecating-authentication-via-token-query-parameter)

**Comment by spencergibb** [comment]
Please open an issue in https://github.com/Ecwid/consul-api

**Comment by budaestew** [comment]
> Please open an issue in https://github.com/Ecwid/consul-api

The last update of ecwid/consul-api was 2 years ago. It seems to be unmaintainable, so I created an issue here.

**Comment by spencergibb** [comment]
We have an open issue to migrate away from that, but otherwise there's nothing I can do.
