### ISSUE TITLE
Broken links on Learn tab

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-consul#839]
On https://spring.io/projects/spring-cloud-consul#learn there are two broken links:

* 4.1.2 links to https://docs.spring.io/spring-cloud-consul/docs/current/reference/html/, which shows documentation for version 4.0.4. I believe the correct link is https://docs.spring.io/spring-cloud-consul/reference/4.1.2
* 4.1.3-SNAPSHOT links to https://docs.spring.io/spring-cloud-consul/docs/4.1.3-SNAPSHOT/reference/html/, which returns 404 Not Found.

I believe the correct link for both of these versions is https://docs.spring.io/spring-cloud-consul/reference/${version}, because these links work:

* 4.1.2: https://docs.spring.io/spring-cloud-consul/reference/4.1.2
* 4.1.3-SNAPSHOT: https://docs.spring.io/spring-cloud-consul/reference/4.1.3-SNAPSHOT

**Comment by ryanjbaxter** [comment]
These should be fixed once the site updates
