### ISSUE TITLE
has plan to Migration to httpclient 5 ?

### ISSUE THREAD

**Issue by little3201** [spring-cloud/spring-cloud-consul#841]
**Is your feature request related to a problem? Please describe.**
Current dependency httpclient 4.x, it dependency commons-logging, httpclient 5.x used sl4j, has plan to migration?

**Describe the solution you'd like**
migration from httpclient4.x, see this [migration-guide](https://hc.apache.org/httpcomponents-client-5.3.x/migration-guide/preparation.html).

**Comment by kzhsw** [comment]
It's a transitive dependency from long unmantained [com.ecwid.consul:consul-api](https://github.com/Ecwid/consul-api), check https://github.com/spring-cloud/spring-cloud-consul/pull/840 for latest work on replacing this.

**Comment by spencergibb** [comment]
closing in favor of #840
