### ISSUE TITLE
Support Netflix feign 8.8.1

### ISSUE THREAD

**Issue by fritzrichter** [spring-cloud/spring-cloud-consul#85]
In my project I have already feign 8.8.1, is there a way to use that as well? It seems that currently there is a dependency to 6.x

**Comment by spencergibb** [comment]
The version in `1.0.0.M2` is [8.6.0](http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-consul/1.0.0.M2/spring-cloud-consul-1.0.0.M2.pom).
