### ISSUE TITLE
DiscoveryClient#getLocalServiceInstance() does not work with random server.port

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-consul#89]
If I set `server.port: 0` and set the `instanceId` as per [the docs](http://cloud.spring.io/spring-cloud-consul/spring-cloud-consul.html#_making_the_consul_instance_id_unique) everything seems to work with a service (foo) calling another service (bar) through Feign.

However, if you try get `discoveryClient.getLocalServiceInstance()` like below:

```
@RestController
@RequestMapping("/bar")
public class BarResource {

    private DiscoveryClient discoveryClient;

    @Autowired
    public BarResource(DiscoveryClient discoveryClient) {
        this.discoveryClient = discoveryClient;
    }

    @RequestMapping(method = GET)
    public String blah() {
        return discoveryClient.getLocalServiceInstance().getUri().toString();
    }
}
```

on the bar service's resource, you get:

```
Internal Server Error","exception":"java.lang.IllegalStateException","message":"Unable to locate service in consul agent: bar-0
```

because [`getLocalServiceInstance()`](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryClient.java#L67) calls [`getServiceId()`](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulLifecycle.java#L113), which uses the `ApplicationContext` Id and not the [`instanceId`](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulLifecycle.java#L76) that was explicitly set.

**Comment by spencergibb** [comment]
Nice catch, thanks!
