### ISSUE TITLE
Non-resolvable parent POM

### ISSUE THREAD

**Issue by mattreyuk** [spring-cloud/spring-cloud-consul#9]
When trying to build this project from a clone I got the error "Non-resolvable parent POM: Could not find artifact org.springframework.cloud:spring-cloud-build:pom:1.0.0.BUILD-SNAPSHOT".

I Googled and found the comment on issue #13 of spring-cloud/spring-cloud-config about using mvn --settings .settings.xml compile to fix this. 

I can create a pull request for the readme to add this between points 3 & 4 if that works for you.

**Comment by spencergibb** [comment]
sure

**Comment by dsyer** [comment]
N.B. all the other projects have an auto-generated README.adoc which includes generic instructions for building etc. Might be a good opportunity to move this project to the same pattern?
