### ISSUE TITLE
Disable all consul functionality with a single flag

### ISSUE THREAD

**Issue by sbuettner** [spring-cloud/spring-cloud-consul#93]
Disabling the consul client via `spring.cloud.consul.enabled=false` leads to an exception since `ConsulConfigBootstrapConfiguration` has a hard dependency on it. Therefore i also need to specifiy `spring.cloud.consul.config.enabled=false`. Maybe it could leverage `@ConditionalOnBean` functionality checking for a `ConsulClient` in this case.

**Comment by spencergibb** [comment]
Unfortunately, because this happens in the bootstrap context, `ConsulConfigBootstrapConfiguration` does `@Import(ConsulAutoConfiguration.class)`, adding `@ConditionalOnBean` breaks config.

**Comment by spencergibb** [comment]
@sbuettner why not remove -config from the classpath?

**Comment by sbuettner** [comment]
Because it would be nice do disable consul with a single flag in integration tests for example.

**Comment by sbuettner** [comment]
:+1:
