### ISSUE TITLE
spring cloud consul high cpu in a spring boot application

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-consul#94]
http://stackoverflow.com/questions/32778760/spring-cloud-consul-high-cpu-in-a-spring-boot-application

Caused by `ConsulCatalogWatch.catalogServicesWatch`. 
`@Scheduled(fixedDelayString = "${spring.cloud.consul.discovery.catalogServicesWatchDelay:10}")`

**Comment by jeffmaury** [comment]
You should reopen it because you've got the same problem with the bus side

**Comment by spencergibb** [comment]
no, a new issue should be opened.

**Comment by jeffmaury** [comment]
Ok I'll open it on Monday
