### ISSUE TITLE
Management check fails when using a non-standard management port

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-consul#99]
If I change my Spring Boot app to use a non-standard management port in application.yml

```
management:
    port: 18202
```

Then spring cloud consul fails when checking the management service

```
/v1/agent/check/pass/service:my-app:18102:management
```

with the error 

```
CheckID does not have associated TTL
```

It appears as though the registerManagement() method in `org.springframework.cloud.consul.discovery.ConsulLifecycle` isn't registering a TTL value:

```
	@Override
	protected void registerManagement() {
		NewService management = new NewService();
		management.setId(getManagementServiceId());
		management.setName(getManagementServiceName());
		management.setPort(getManagementPort());
		management.setTags(properties.getManagementTags());

		register(management);
	}
```

I'm not sure if this is due to the way that my consul instance is set up (I didn't configure it). but I suspect that the Spring cloud consul library needs tweaking to support a TTL value.

**Comment by spencergibb** [comment]
ttl is set if `spring.cloud.consul.discovery.heartbeat.enabled=true`.

**Comment by spencergibb** [comment]
What version of spring-cloud-consul and consul are you using? I don't see that error when I set the `management.port`.

**Comment by spencergibb** [comment]
Spring-cloud-consul doesn't call `/v1/agent/check/pass/service/{id}` that I'm aware of.

**Comment by nickcodefresh** [comment]
I'm using 1.0.0.M1 and I have `spring.cloud.consul.discovery.heartbeat.enabled` set to true

**Comment by spencergibb** [comment]
consul version?

**Comment by nickcodefresh** [comment]
Consul v0.4.1

**Comment by spencergibb** [comment]
can you try with a later version of consul?

**Comment by nickcodefresh** [comment]
The latest version of Consul fixed this issue! Happy days! Thanks

**Comment by nickcodefresh** [comment]
Actually I've just checked this and it still doesn't work (using 1.0.0.M2). Event though my application.yml says

```
server:
    port: 18113

management:
    port: 18213
    security:
        enabled: false
```

Consul is reporting the following using ```http://dockermachine:8500/v1/catalog/service/mio-events-service```

```
[
    {
        Node: "dockermachine",
        Address: "192.168.99.100",
        ServiceID: "mio-events-service-docker-compose-18113",
        ServiceName: "mio-events-service",
        ServiceTags: [ ],
        ServiceAddress: "",
        ServicePort: 18213,
        ServiceEnableTagOverride: false,
        CreateIndex: 45,
        ModifyIndex: 509
    }
]
```
Note that the ServicePort is 18213, whereas it should be 18113. ```http://dockermachine:8500/v1/catalog/service/mio-events-service-management``` gives the same ServicePort, which is correct.

**Comment by spencergibb** [comment]
Try with the latest, 1.0.0.M5

**Comment by nickcodefresh** [comment]
Yes that appears to fix it, thanks
